### ISSUE TITLE
error when compiling futurerestore

### ISSUE THREAD

**Issue by iFred09** [tihmstar/futurerestore#105]
Hi,

How I can fix this error ? I have all dependencies installed.
I do sudo ldconfig but nothing happens.

![image](https://cloud.githubusercontent.com/assets/22419166/24827984/6ae07202-1c54-11e7-90d8-072539b6f190.png)

Thx.

**Comment by tihmstar** [comment]
It is impossible to find the issue providing only a screenshot of the final error, instead of describing all steps taken and providing all commands and logs.
