### ISSUE TITLE
iPhone 6 downgrade ios 10.2.1 to 10.2 (linux) "failed to load ap ticket at.

### ISSUE THREAD

**Issue by avdovic** [tihmstar/futurerestore#107]
How to fix it? :/

futurerestore -t 1528107027374118_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: 99da4c33526e5dff9b2841a782a6cf9cc41c0aae - 116
[INFO] 64bit device detected
futurerestore init done
[Error] failed to load apticket at 1528107027374118_iPhone7,2_n61ap_10.2-14C92.shsh2
[Error] Fail code=-9
Failed with errorcode=-9

**Comment by tihmstar** [comment]
looks like your apticket is bad, have you checked it with img4tool? can you upload it?

**Comment by avdovic** [comment]
I have not checked  apticket on img4tool.

This shsh2 blob I used.

**Comment by onesentinel** [comment]
You can check it yourself on https://tsssaver.1conan.com/check.php

Make sure it is valid and an Erase one

**Comment by avdovic** [comment]
File is valid!

**Comment by onesentinel** [comment]
May you post the first couple lines?

The ECID you can cover up if you want.

**Comment by avdovic** [comment]
This?

sri, 3. svi 2017. u 01:24 onesentinel <notifications@github.com> napisao je:

**Comment by onesentinel** [comment]
No, the first couple lines of the output you get when you check the shsh2 on the link I have you

**Comment by avdovic** [comment]
sri, 3. svi 2017. u 17:57 onesentinel <notifications@github.com> napisao je:
