### ISSUE TITLE
iPhone 4S 32 Bit Error code 77

### ISSUE THREAD

**Issue by AustinZdawg** [tihmstar/futurerestore#108]
Austin$ /Users/Austin/Desktop/futurerestore-latest/futurerestore_macos -t /Users/Austin/Desktop/futurerestore-latest/iPhone4\,1_3595542191437_12H321.shsh -b /Users/Austin/Desktop/futurerestore-latest/Trek-6.0.00.Release.bbfw -p /Users/Austin/Desktop/futurerestore-latest/BuildManifest.plist -s --is-32bit -w /Users/Austin/Desktop/futurerestore-latest/iPhone4\,1_8.4.1_12H321_Restore.ipsw
Version: e2d0d263e560103a064866c2953cb744080b2142 - 117
[INFO] 32bit device detected
futurerestore init done
reading ticket /Users/Austin/Desktop/futurerestore-latest/iPhone4,1_3595542191437_12H321.shsh done
Did set sep+baseband path and firmware
[TSSC] opening /Users/Austin/Desktop/futurerestore-latest/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is C8WKHDA8DT9V
[Error] Error: waitForNonce is not supported on 32bit devices
[Error] Fail code=-77
Failed with errorcode=-77
  

I have tried so many different ways but overtime i keep on getting this. I have no idea why.

**Comment by albyvar** [comment]
Try without -w
