### ISSUE TITLE
[Error] TSS request failed (iPhone 6+)

### ISSUE THREAD

**Issue by raznator** [tihmstar/futurerestore#109]
Got the following error when trying to upgrade from 9.3.3 to 10.2 with saved blobs. The ipsw is for 10.2 and I know it isn't being signed anymore, so which IPSW do I need to get the SEP files from? Thanks!

My-MacBook-Pro:downgrade Rasit$ ./futurerestore_macos -t 2297129718564538_iPhone7,1_n56ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n56.RELEASE.im4p -m BuildManifest.plist -w iPhone_5.5_10.2_14C92_Restore.ipsw
Version: 36be0769f2eb48290bdc7b57c912458c3b334fb4 - 92
futurerestore init done
reading ticket 2297129718564538_iPhone7,1_n56ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... [Error] sep firmware isn't signed
Failed with errorcode=-3

**Comment by Lucaso123a** [comment]
Apple is no longer signing SEP for 10.2.1, so you cannot use 10.2.1 SEP. I think 10.3.1 SEP do not work on iOS 10.2, so the only option for you is to restore 10.3.1 (iTunes or idevicerestore whatever).

**Comment by raznator** [comment]
Looks like it is, I'll give it a shot anyway! https://www.reddit.com/r/jailbreak/comments/64mm58/discussion_has_anybody_tried_prometheus_with_1031/

**Comment by Lucaso123a** [comment]
If 10.3.1 SEP is compatible with 10.2, that's good.

**Comment by osxusr** [comment]
you should update future restore

**Comment by andybrunoproductions** [comment]
can someone tell me if its possible to downgrade iOS 14.6 at all
