### ISSUE TITLE
Failed with errorcode=-3 ; (sep firmware isn't signed)

### ISSUE THREAD

**Issue by Momoske** [tihmstar/futurerestore#111]
Since many days/weeks, i'm trying to downgrade my iphone from 10.2.1 to 10.2 (i have my blobs) with futurerestore. I've got this errorcode=-3 since 10.2.1 isn't signed by Apple anymore, so i tried using 10.3.1 sep file. I don't know if it shuold work, but i was wondering if anyone knew if that was possible, because i'm getting the same error with 10.3.1's sep file, which futurerestore says that it isn't signed. If we can't downgrade from unsigned to unsigned firmware in any case, then thank you for letting me know. I didn't find any fix/solution on google, so i post this on tihmstar's github.
I hope someone can help ; people reading this, have a nice day!
![2017-04-23 13-27-19 0200](https://cloud.githubusercontent.com/assets/27915933/25313155/81b312ce-2829-11e7-8bb1-d95d54d980e8.jpg)

**Comment by tihmstar** [comment]
Are you using the correct BuildManifest for SEP?

**Comment by Momoske** [comment]
As i'm running 10.2.1 , i used every file needed for futurerestore from the 10.2.1 ipsw. Unfortunately, i got this error (since 10.2.1 isn't signed anymore i guess), so i tried to use 10.3.1 sep file just to test out it futurerestore would say that it's signed, but i got the same error. I didn't test out with every file from the 10.3.1 ipsw because i'm not running it on my phone right now. I'm on an iPhone 6 so i use n61ap sep file, and 5.32.00 BuildManifest file. But as we see pangu jailbreaking 10.3.1, i'll upgrade to this, and try with 10.3.1 to downgrade to 10.2 and tell you if this problem got fixed :D
Thanks for answering!

**Comment by Momoske** [comment]
*oops, just said 5.32.00 BuildManifest file for some reason, but i meant 5.32.00 baseband file and 10.2.1 BuildManifest file.

**Comment by tihmstar** [comment]
you need to pass the BuildManifest.plist from 10.3.1 to sepmanifest parameter if you're using 10.3.1 sep file

**Comment by Momoske** [comment]
Oh alright! Thanks, it fixed it. If i never get collisions, my only hope is 10.3.1 pangu jailbreak with tfp0 and open ssh enabled :/

**Comment by cptalpdeniz** [comment]
Is it possible to use 10.3.3 SEP/buildmanifest/baseband file to upgrade to 10.2? I receive the same error even though I use the correct files from 10.3.3
