### ISSUE TITLE
Error when compiling futurerestore v122

### ISSUE THREAD

**Issue by zweed4u** [tihmstar/futurerestore#117]
When I go to make after running the autogen shell script I get the following errors running `make`:

`futurerestore.cpp:546:27: error: invalid conversion from ‘char*’ to ‘const unsigned char*’ [-fpermissive]`
`futurerestore.cpp:548:29: error: invalid conversion from ‘char*’ to ‘const unsigned char*’ [-fpermissive]`

Can I just go into the c++ file and cast them accordingly? 
How would I rectify this?

Cheers,

[User info]
OS: GalliumOS (Xubuntu variant)
Current futurerestore v117
tsschecker v223
img4tool v93

**Comment by tihmstar** [comment]
fixed this in 80c0eee322a8822ff36c207e6c2e68ab81fd51d0
