### ISSUE TITLE
I always get same nonce after each reboot when trying to restore!

### ISSUE THREAD

**Issue by onesentinel** [tihmstar/futurerestore#119]
My i6+ is on 10.2.1 bc I messed up my jailbreak (bootloop cause of AppSync) so I updated my device via iTunes.
Now I want to downgrade back to 10.2, and I still have 2 valid erase install shsh2 blobs.
When using the buildmanifest, baseband and sep from 10.3.1, bc 10.2.1 sep isn't signed, obviously, I always get an Error or something doesn't work.

In the screenshot below, I always get the same ap-nonce after each reboot!
Everyone is telling me I simply just installed NonceEnabler, but 100% I haven't.
Now, should I update to 10.3.1 and try if I can downgrade (are there even collisions at 10.3.1??) , or wait for 10.2.1 Jailbreak?

What did I do wrong?

Please help! 

<img width="732" alt="futurerestore-bugs" src="https://cloud.githubusercontent.com/assets/21205288/25566370/a06006e2-2dd7-11e7-8f4a-ea06af6cf44c.png">

**Comment by NotAlexNoyle** [comment]
The iPhone 6+ does not get noncecollisions. Just the iPad Air and iPhone 5s. I couldn't tell you why your device is generating the same blob over and over -- but the bottom line is, unless you can set your nonce in nvram (which requires a jailbreak with host_get_special_port), you aren't going to be able to downgrade.

**Comment by onesentinel** [comment]
Are you sure I6+ doesn't get collisions bc I think qwertyoruiop twittered something about this month ago

**Comment by RandomAsianHoe** [comment]
I had this problem with my 5s also when I was on 10.3 beta 1 so I couldn't downgrade. It's an issue that apple messed up in iOS 10. Here's some more info if you want to know about the 100% noncecollision.   http://blog.tihmstar.net/2017/01/halp-i-get-same-nonce100-nonce-collision.html?m=1

**Comment by onesentinel** [comment]
Thank you for your comment but sadly too late, I already reseted to 10.3.1.
But one thing I didn't understand in the article, how do you request a nonce in normal mode bc noncestatistics Auto-boots in recovery?
