### ISSUE TITLE
Cannot Put Device into Recovery Mode

### ISSUE THREAD

**Issue by RandomAsianHoe** [tihmstar/futurerestore#120]
I have an iPhone 5s on ios 10.2.1. This is the error i get when i try to restore to ios 10.2. It puts my device into recovery and then i wait for a while and i get the error. Any help as to why this happens would be appreciated.

./futurerestore_linux -t 0dc448240696866b0cc1b2ac3eca4ce22af11cb3.shsh -t 9e4c518009d00df190a450b3b47691768812360c.shsh -t 9f4aeec726e7c682339ddb3c6c2dec52662dc517.shsh -t 42c88f5a7b75bc944c288a7215391dc9c73b6e9f.shsh -t 352dfad1713834f4f94c5ff3c3e5e99477347b95.shsh -t 603be133ff0bdfa0f83f21e74191cf6770ea43bb.shsh -t 9804d99e85bbafd4bb1135a1044773b4df9f1ba3.shsh -b Mav7Mav8-7.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n51.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.0_64bit_10.2_14C92_Restore.ipsw 
Version: c271a71524d05d181c099c426264809c7e1c3917 - 100
futurerestore init done
reading ticket 0dc448240696866b0cc1b2ac3eca4ce22af11cb3.shsh done
reading ticket 9e4c518009d00df190a450b3b47691768812360c.shsh done
reading ticket 9f4aeec726e7c682339ddb3c6c2dec52662dc517.shsh done
reading ticket 42c88f5a7b75bc944c288a7215391dc9c73b6e9f.shsh done
reading ticket 352dfad1713834f4f94c5ff3c3e5e99477347b95.shsh done
reading ticket 603be133ff0bdfa0f83f21e74191cf6770ea43bb.shsh done
reading ticket 9804d99e85bbafd4bb1135a1044773b4df9f1ba3.shsh done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
ERROR: Unable to connect to device in recovery mode
ERROR: Unable to enter recovery mode
[Error] Unable to place device into recovery mode from Normal mode
[Error] Fail code=-2
Failed with errorcode=-2

**Comment by onesentinel** [comment]
You can't restore bc the baseband error isn't fixed yet by tihmstar.

Otherwise, for your Recovery Mode problem try putting it to recovery before, manually or with the program 'ReiBoot'.
If this doesn't work there are just 2 possible reasons.
One is that drivers for your device on your pc doesn't work or the data wires in your USB-cable are damaged somehow.
I don't know on which system ur on but on Mac drivers can't normally be broken. So MacOS is not affected.

If all this doesn't fix it then your firmware on your device is broken.
The Firmware can just be fixed if it is still signed by apple!

**Comment by RandomAsianHoe** [comment]
Alright thanks I'll wait for tihmstar to fix the baseband error and I'll try again

**Comment by tihmstar** [comment]
This sounds like the tool doesn't detect your device in recovery mode, even though it did send the device in recovery mode, right?
Are you using a virtual machine like virtual box?

**Comment by chriscrutt** [comment]
> This sounds like the tool doesn't detect your device in recovery mode, even though it did send the device in recovery mode, right?
> Are you using a virtual machine like virtual box?

i am having the same issue on my mac pro where futurerestore is able to put my iPhone X into recovery mode, then says "ERROR: Failed to place device in recovery mode"
