### ISSUE TITLE
i7 downgrade 10.3.1 to 10.1.1

### ISSUE THREAD

**Issue by forzabatur** [tihmstar/futurerestore#124]
Hi, I have tried to downgrade my i7 10.3.1 to 10.1.1.
I did save my blobs (appnonce and nonce) shsh2 tickets.
But it keeps finding my apnonce....
waiting for nonce: 16 8d d1 46 76 be a5 1d cc 02 59 51 e4 21 b1 0e a9 55 85 ba
Got ApNonce from device: 16 8d d1 46 76 be a5 1d cc 02 59 51 e4 21 b1 0e a9 55 85 ba 
This string keeps coming, its in a loop....

**Comment by NotAlexNoyle** [comment]
I don't think this is possible, you can't set your nonce on 10.3.1 because there is no jailbreak (and by extension, no way to set nvram variables). It's weird that the nonce it expects is the one it's getting, though, don't know what's going on there.

**Comment by bryanbridges** [comment]
I believe there is a daily request limit with nonce. I noticed this with my
6s+ when it was in my possession. Give it a good 12 hours and hours set. Or
wait until the next day.
