### ISSUE TITLE
Fail code=-9

### ISSUE THREAD

**Issue by skatinc** [tihmstar/futurerestore#128]
Help me please !!!
Iphone 6     downgrade 10.3.1->10.2

Mac-Admin:~ admin$ futurerestore_macos -t 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: de907d3fa854275b296af0e18818467d72cc59fa - 126
[INFO] 64bit device detected
futurerestore init done
[Error] failed to load apticket at 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2
[Error] Fail code=-9
Failed with errorcode=-9

**Comment by skatinc** [comment]
Apnonce: 303046d58ae3816fee5ba92b949fe1116a6cfe64

Build Number: 14C92

Board Configuration: n61ap

Restore Behaviour: Erase

Rosi Tag: true


[IMG4TOOL] file is valid!

**Comment by goodboydheeraj** [comment]
shsh2 file should be 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2.plist

rename the file to .plist

I wonder how you're gonna successfully downgrade to 10.2 when you're on 10.3.1?

**Comment by skatinc** [comment]
Mac-Admin:/ admin$ /Users/admin/Desktop/Новая\ папка\ 2/futurerestore_macos -t 6236790868887590_iPhone7,2_n61ap_10.2-14C92.plist -b Mav10-5.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: de907d3fa854275b296af0e18818467d72cc59fa - 126
[INFO] 64bit device detected
futurerestore init done
[Error] failed to load apticket at 6236790868887590_iPhone7,2_n61ap_10.2-14C92.plist
[Error] Fail code=-9
Failed with errorcode=-9
Mac-Admin:/ admin$ 


the same ;-((((((

**Comment by skatinc** [comment]
/Users/admin/Desktop/Новая\ папка\ 2/futurerestore_macos -t 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2.plist -b Mav10-5.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw

the same ;-(

**Comment by skatinc** [comment]
Mac-Admin:/ admin$ /Users/admin/Desktop/Новая\ папка\ 2/futurerestore_macos -t 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2.plist -b Mav10-5.51.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: de907d3fa854275b296af0e18818467d72cc59fa - 126
[INFO] 64bit device detected
futurerestore init done
[Error] failed to load apticket at 6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2.plist
[Error] Fail code=-9
Failed with errorcode=-9
Mac-Admin:/ admin$ 

the same ;-(

**Comment by tihmstar** [comment]
Beside the fact that you can't downgrade from 10.3.1 right now anyways,
i can take a look at you shsh file if you upload it

**Comment by skatinc** [comment]
ok -->

**Comment by skatinc** [comment]
Ok !

**Comment by skatinc** [comment]
don't send  as .zip - error
rename to .txt

thanks !!!!!!!!!!!!



[3945425823867430_iPad6,4_j128ap_10.2-14C92.txt](https://github.com/tihmstar/futurerestore/files/1083372/3945425823867430_iPad6.4_j128ap_10.2-14C92.txt)

**Comment by skatinc** [comment]
[1.txt](https://github.com/tihmstar/futurerestore/files/1083373/1.txt)

don't send as .zip - error
 rename to .txt

thanks !!!!!!!!!!!!

**Comment by tihmstar** [comment]
The log you sent in the first post says "6236790868887590_iPhone7,2_n61ap_10.2-14C92.shsh2", but the file you sent me is "3945425823867430_iPad6,4_j128ap_10.2-14C92.shsh2".
Closing this nonsense now.
You can't downgrade 10.3.1 with nonce collision method anyways.
