### ISSUE TITLE
Tried to upgrade iPhone 6s to iOS 10.1.1 and futurerestore requests wrong baseband ticket

### ISSUE THREAD

**Issue by kotonemesis** [tihmstar/futurerestore#13]
I entered command:
./futurerestore -t iPhone8,1_10.1.1-14B150.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71m.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.1.1_14B150_Restore.ipsw (Tried to upgrade my iPhone 6s (iPhone8,1) to iOS 10.1.1 with shsh2 blob that is confirmed to be valid (rosi tag found))

The result was:
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for **iPhone7,2** (Wrong device, should be **iPhone 8,1**)
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for **iPhone7,2** (Wrong device, should be **iPhone 8,1**)
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[TSSC] opening bbgcid.json
[DOWN] downloading file http://api.tihmstar.net/bbgcid?condensed=1
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=126&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=126, message=An internal error occurred.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed

On build manifest of iOS 10.2 file, I found that n61ap was located above than n71map (iPhone 6s TSMC). Its first 34 lines were like this:

<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>BuildIdentities</key>
	<array>
		<dict>
			<key>ApBoardID</key>
			<string>0x06</string>
			<key>ApChipID</key>
			<string>0x7000</string>
			<key>ApSecurityDomain</key>
			<string>0x01</string>
			<key>BbActivationManifestKeyHash</key>
			<data>
			jLFe5MgAIZkHDZUAu4+xg7AnE6XKKmuS2151zhVTYYI=
			</data>
			<key>BbChipID</key>
			<string>0x007F50E1</string>
			<key>BbFDRSecurityKeyHash</key>
			<data>
			</data>
			<key>BbProvisioningManifestKeyHash</key>
			<data>
			u+/tcCwvaQ+1Y9t40I4yegCEmB28mALlaROhaIVGBWo=
			</data>
			<key>Info</key>
			<dict>
				<key>BuildNumber</key>
				<string>14C92</string>
				<key>BuildTrain</key>
				<string>Corry</string>
				<key>DeviceClass</key>
				<string>**n61ap**</string>

**Comment by tihmstar** [comment]
This was an issue with tsschecker, which should be fixed by now
