### ISSUE TITLE
Fail code=-22 & -20

### ISSUE THREAD

**Issue by ScknCbt** [tihmstar/futurerestore#132]
MacBookPro:Downgrade ScknCbt$ ./futurerestore_macos -t iPhone5,2.shsh --latest-baseband -u iPhoneRestore.ipsw 
Version: de907d3fa854275b296af0e18818467d72cc59fa - 126
[INFO] 32bit device detected
futurerestore init done
reading ticket iPhone5,2.shsh done
user specified to use latest signed baseband (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 10.3.2
[TSSC] got firmwareurl for iOS 10.3.2 build 14F89
100 [===================================================================================================>]
[Error] [LFZP] failed to download file (-13)
[Error] could not get buildmanifest of latest firmware
[Error] Fail code=-22
Failed with errorcode=-22
MacBookPro:Downgrade ScknCbt$ 

MacBookPro:futurerestore ScknCbt$ futurerestore -t iPhone5,2.shsh --latest-baseband -u iPhoneRestore.ipsw 
Version: 5879ea81321e5c35c0e64f7ea19b08d39d536cf6 - 134
[INFO] 32bit device detected
futurerestore init done
reading ticket iPhone5,2.shsh done
[Error] unexpected device mode=4
[Error] Fail code=-20
Failed with errorcode=-20
MacBookPro:futurerestore ScknCbt$

**Comment by tihmstar** [comment]
same as #136
