### ISSUE TITLE
im Trying to restore my ip6s on 10.3.1 to 10.2 and i get this error Plz Help

### ISSUE THREAD

**Issue by aboagzail1** [tihmstar/futurerestore#136]
pc@pc-ThinkPad-E520:~/Desktop/Downgrade$ ./futurerestore_linux -t 4626914853320_iPhone8,1_10.2-14C92.shsh2 -b Mav13-2.54.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: b3f684d61ba7ec246869119dde552ef62cf8f051 - 140
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket 4626914853320_iPhone8,1_10.2-14C92.shsh2 done
[Error] unexpected device mode=4
[Error] Fail code=-20
Failed with errorcode=-20
pc@pc-ThinkPad-E520:~/Desktop/Downgrade$

**Comment by tihmstar** [comment]
In what mode is your device?
Normal mode?
Recovery mode?
DFU mode?

**Comment by Anuj79** [comment]
reading ticket ??????_iPhone8,1_10.2-14C92.shsh2 done
[Error] unexpected device mode=4
[Error] Fail code=-20
Failed with errorcode=-20
i am getting the same message .. the device is iphone6s+ and in normal mode.

**Comment by aboagzail1** [comment]
Normal Mode

**Comment by Zeynoh** [comment]
I am getting this as well tihmstar, please help as soon as you can
[![809a56df7362158e53b6478c73c4e0a2](https://user-images.githubusercontent.com/29391785/27064629-349c05b2-4fad-11e7-9514-cda9fdbc481b.png)](url)

**Comment by ChillNL** [comment]
I'm having the exact same issue.
Running VM Workstation on Windows 10. Does the phone need to be in recovery mode?

**Comment by ScknCbt** [comment]
put your device first in Recovery mode and than try again the futurerestore. 
But i get the same Error in Normal mode, maybe @tihmstar can fix this :)

**Comment by tihmstar** [comment]
should be fixed in 231bdc251c0e1a655ee8125e95b8b30e821651b6
