### ISSUE TITLE
Error -2 

### ISSUE THREAD

**Issue by RyoTakei** [tihmstar/futurerestore#141]
I tried to use this on my ubuntu(not on VM), and its giving me an error. 

WARNING: user specified not to flash a baseband. This can make the restore fail 
if the device needs a baseband! 
if you added this flag by mistake you can press CTRL-C now to cancel 
continuing restore in 5 4 3 2 1 
Found device in Normal mode 
Entering recovery mode...
ERROR: Unable to connect to device in recovery mode 
ERROR: Unable to enter recovery mode 
[Error] Unable to place device into recovery mode from Normal mode 
[Error] Fail code=-2 Failed with errorcode=-2

any ideas???

**Comment by RoyalGraphX** [comment]
can you specify device, model number, and iOS versions you're on and trying to go to?

**Comment by RyoTakei** [comment]
yes, Im on the latest version of iOS(iOS 10.3.2) and trying to go to 10.2 on iPod Touch 6th.

**Comment by RoyalGraphX** [comment]
Are you running a fully unboxed version of Ubuntu? or a live boot?

If so, do you know if that version is compatible with your hardware? it might just not be detecting the iPod once it reconnects as it doesn't have the driver for it

**Comment by RyoTakei** [comment]
I have fully unboxed Ubuntu.(Ive been using Arch for a while now, but since i couldnt find a way to install libzip.so.2, I decided to install Ubuntu on my external drive)

Im using Thinkpad x1 carbon 4th, and i think its fully compatible.

**Comment by RoyalGraphX** [comment]
Is the external drive a usb drive? as in it was installed onto a usb drive?

**Comment by RyoTakei** [comment]
Yes. It is USB external drive.

**Comment by tihmstar** [comment]
Have you tried running futurerestore as root?

**Comment by RoyalGraphX** [comment]
Okay well I suggest running a live version off of a USB and format that external hardddrive and only have the IPSW, SHSH Blob, Futurerestore binary and any other files needed like Mav file or sep file

**Comment by RoyalGraphX** [comment]
and yeah run the binary as 'sudo' or 'root'
