### ISSUE TITLE
Onboard Blobs error 

### ISSUE THREAD

**Issue by toniqyteza** [tihmstar/futurerestore#142]
Futurerestore+libipatcher
iPhone 4s iOS 8.4 with onboard blobs
http://www.mediafire.com/file/4znle44oj3vg297/276758154540_iPhone4%2C1_8.4-12H143.shsh
![ddberj-xyaegseg](https://user-images.githubusercontent.com/25407594/27658610-e822d9c6-5c50-11e7-9aa7-6b4fa3fa9847.jpg)

**Comment by RoyalGraphX** [comment]
Seems the blob is invalid?

**Comment by jihyo-song** [comment]
are you using converted blobs with apticket.der ? it seems your blobs only have ApImg4Ticket/APTicket shsh. Need APTicket and LLB shsh for this tools worked. Try use [Odysseus Dumped Blobs Method,](https://www.youtube.com/watch?v=2GBLYPqM-XQ) dump blobs from Odysseus have APTicket and LLB shsh, so it will worked. Use 6.1.3 ipsw + 6.1.3 bundles for dump blobs A5 device.

**Comment by toniqyteza** [comment]
Oh thanks, I lost jb already :/

**Comment by jihyo-song** [comment]
how can be ? when you want to dumped blobs ? :/

**Comment by RoyalGraphX** [comment]
Then this issue is invalid, the blobs weren't correct then, Please close this issue asap

**Comment by toniqyteza** [comment]
Oh yeah but i talked to tohnstar and he said open an issue and send me your blobs
But im closing it

**Comment by toniqyteza** [comment]
Oh yeah but i talked to tohnstar and he said open an issue and send me your blobs
But im closing it
