### ISSUE TITLE
downgrade iPad2,1 from 9.2.1 ----->7.0

### ISSUE THREAD

**Issue by 2Klasic** [tihmstar/futurerestore#144]
attempting to downgrade using future restore _macos version 150 with libipatcher vs 32..the device gets to Sending iBEC 100% then it reboots the device

iMac:iPhone5,2 2Klasic$ ./futurerestore_macos --use-pwndfu -t iPad2,1_7.0-11A465.shsh --no-baseband iPad2,1_7.0_11A465_Restore.ipsw 
Version: f068ddb0576e9401b93a9ac9498313c2e35b862e - 150
Libipatcher Version: e72c0c9f622a149f506ca1a35cae0555c4d05c69 - 32
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket iPad2,1_7.0-11A465.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as k93ap, iPad2,1
Extracting BuildManifest from IPSW
Product Version: 7.0
Product Build: 11A465 Major: 11
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting iBSS.k93ap.RELEASE.dfu...
iBoot32Patch: iBoot-1940 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_5_6_7: Entering...
find_bl_verify_shsh_5_6_7: Found MOVW instruction at 0x6704
find_bl_verify_shsh_5_6_7: Found BL verify_shsh at 0x6a30
find_bl_verify_shsh_5_6_7: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x6a30...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Extracting iBEC.k93ap.RELEASE.dfu...
iBoot32Patch: iBoot-1940 inputted.
patch_ticket_check: Entering...
patch_ticket_check: Found iboot_vers_str at 0x280
patch_ticket_check: Found str_pointer at 0x308
patch_ticket_check: Found iboot_str_3_xref at 0x1ea50
patch_ticket_check: Found ldr_intruction at 0x1e9aa
patch_ticket_check: Found last_good_bl at 0x1e9b2...
patch_ticket_check: Patching in eor r1, r5, #0x1 at 0x1e9b6...
patch_ticket_check: Patching in mov.w r0, #0 at 0x1e9ba...
patch_ticket_check: NOPing useless stuff at 0x1e9be to 0x1ea48 ...
patch_ticket_check: Leaving...
patch_rsa_check: Entering...
find_bl_verify_shsh_5_6_7: Entering...
find_bl_verify_shsh_5_6_7: Found MOVW instruction at 0x1a0a0
find_bl_verify_shsh_5_6_7: Found BL verify_shsh at 0x1a67c
find_bl_verify_shsh_5_6_7: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x1a67c...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Sending iBSS (73920 bytes)...
[==================================================] 100.0%
Sending iBEC (291008 bytes)...
[==================================================] 100.0%
ERROR: Unable to connect to device in recovery mode
[Error] ERROR: Unable to connect to recovery device
Done: restoring failed.
Failed with errorcode=-93

**Comment by tihmstar** [comment]
I figured out what the issue is. For some reason it detects the wrong functionlayout and applies the wrong patch. I need to take a closer look at this so i can fix it without fucking up every other working iOS.

**Comment by 2Klasic** [comment]
Thank you tihmstar

**Comment by tihmstar** [comment]
Can you check if libipatcher v37 fixed the issue tihmstar/libipatcher@1f5e67b ?

**Comment by 2Klasic** [comment]
ok will do sorry for the late response

**Comment by 2Klasic** [comment]
This issue has been resolved I'm closing the ticket now..thank you for rectifying the issue.
