### ISSUE TITLE
futurerestore stops and phone left in bootloop

### ISSUE THREAD

**Issue by heroinfather** [tihmstar/futurerestore#145]
before i state the issue, i know how to get out of a bootloop, its just that futurerestore stops after a while
~/Desktop/futurerestore$ sudo ./futurerestore_linux -t 2.shsh -b Mav7Mav8-7.60.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n51.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.0_64bit_10.2_14C92_Restore.ipsw 
[sudo] password for juan: 
Version: f068ddb0576e9401b93a9ac9498313c2e35b862e - 150
Libipatcher Version: e72c0c9f622a149f506ca1a35cae0555c4d05c69 - 32
Odysseus Support: yes
INFO: device serial number is
[INFO] 64bit device detected
futurerestore init done
reading ticket 2.shsh done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
waiting for nonce: 98 04 d9 9e 85 bb af d4 bb 11 35 a1 04 47 73 b4 df 9f 1b a3 
Got ApNonce from device: eb 43 06 19 4a 88 4c 52 41 12 a5 94 6d 38 6a e3 1c 22 82 48 
Got ApNonce from device: 59 6e b8 3c 68 0a 80 72 2a 59 30 5f 8e f1 d6 24 bf f1 cf 05 
Got ApNonce from device: 89 e7 b2 b0 86 b9 b3 ee 14 73 55 fd 8e 0a 1e d9 3b 1a 9c 8a 
Got ApNonce from device: 53 c0 af 3c 34 03 0f b0 d7 50 04 e8 6f bc 73 ca 43 92 53 6d 
Got ApNonce from device: f3 36 27 5a be 5f 58 1e 55 31 ac f0 0d 6a 8d db d3 ba ed 06 
Got ApNonce from device: 52 4b f2 38 83 64 27 45 0e 1a 36 8c 42 3c ee 1f 76 a6 60 89 
Got ApNonce from device: 1a ed 9f c9 84 94 a6 d8 e0 85 34 1a 51 92 02 bc 52 f6 f0 93 
Got ApNonce from device: 68 2d a2 e9 85 fe 0b c1 45 17 d6 88 ef a0 85 63 eb 1a d3 40 

i am on iphone 5s 10.3.2, and using linux ubuntu

**Comment by RyoTakei** [comment]
the same issue here. FutureRestore just stops after 15th try of getting the ApNonce.
