### ISSUE TITLE
error while downgrading iPhone4,1 to 5.1.1

### ISSUE THREAD

**Issue by um5566** [tihmstar/futurerestore#146]
Seems to be an error extracting restoreramdisk
Here is the log:

seolhyun@seolhyun-GS63VR-6RF ~/Downloads $ sudo./futurerestore_linux -t '/media/seolhyun/8640292D40292581/shsh/00000080081D5D2A_5.0.1r1-9A406_cydia.shsh' --latest-baseband --use-pwndfu ~/Desktop/iPhone4\,1_5.0.1_9A406_Restore.ipsw
bash: sudo./futurerestore_linux: No such file or directory
seolhyun@seolhyun-GS63VR-6RF ~/Downloads $ sudo ./futurerestore_linux -t '/media/seolhyun/8640292D40292581/shsh/00000080081D5D2A_5.0.1r1-9A406_cydia.shsh' --latest-baseband --use-pwndfu ~/Desktop/iPhone4\,1_5.0.1_9A406_Restore.ipsw
Version: 231bdc251c0e1a655ee8125e95b8b30e821651b6 - 142
Libipatcher Version: eb170f9b6e28604bec1bf04648f744215418255b - 29
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket /media/seolhyun/8640292D40292581/shsh/00000080081D5D2A_5.0.1r1-9A406_cydia.shsh done
user specified to use latest signed baseband (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 9.3.5
[TSSC] got firmwareurl for iOS 9.3.5 build 13G36

[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in DFU mode
requesting to get into pwnRecovery later
Found device in DFU mode
Identified device as n94ap, iPhone4,1
Extracting BuildManifest from IPSW
Product Version: 5.0.1
Product Build: 9A406 Major: 9
Device supports Image4: false
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[WARNING] skipping ramdisk hash check, since device is in pwnDFU according to user
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting iBSS.n94ap.RELEASE.dfu...
iBoot32Patch: iBoot-1219 inputted.
patch_rsa_check: Entering...
find_bl_verify_shsh_5_6_7: Entering...
find_bl_verify_shsh_5_6_7: Found MOVW instruction at 0x6696
find_bl_verify_shsh_5_6_7: Found BL verify_shsh at 0x6c28
find_bl_verify_shsh_5_6_7: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x6c28...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Extracting iBEC.n94ap.RELEASE.dfu...
iBoot32Patch: iBoot-1219 inputted.
patch_ticket_check: Entering...
patch_ticket_check: Found iboot_vers_str at 0x280
patch_ticket_check: Found str_pointer at 0x308
patch_ticket_check: Found iboot_str_3_xref at 0x1767c
patch_ticket_check: Found ldr_intruction at 0x175e2
patch_ticket_check: Found last_good_bl at 0x175ea...
patch_ticket_check: Patching in eor r1, r5, #0x1 at 0x175ee...
patch_ticket_check: Patching in mov.w r0, #0 at 0x175f2...
patch_ticket_check: NOPing useless stuff at 0x175f6 to 0x1765c ...
patch_ticket_check: Leaving...
patch_rsa_check: Entering...
find_bl_verify_shsh_5_6_7: Entering...
find_bl_verify_shsh_5_6_7: Found MOVW instruction at 0x140be
find_bl_verify_shsh_5_6_7: Found BL verify_shsh at 0x148d8
find_bl_verify_shsh_5_6_7: Leaving...
patch_rsa_check: Patching BL verify_shsh at 0x148d8...
patch_rsa_check: Leaving...
iBoot32Patch: Quitting...
Sending iBSS (72016 bytes)...
[==================================================] 100.0%
Sending iBEC (227664 bytes)...
[==================================================] 100.0%
INFO: device serial number is C39H4E5ADTD7
Using cached filesystem from '/home/seolhyun/Desktop/iPhone4,1_5.0.1_9A406_Restore/038-3763-001.dmg'
Sending APTicket (2745 bytes)

Getting ApNonce in recovery mode... 24 78 29 bf d6 f3 79 99 20 39 2d 89 f8 ff de 45 1d 5f b3 24 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Sending APTicket (2745 bytes)
Recovery Mode Environment:
iBoot build-version=iBoot-1219.43.32
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo-640x960.s5l8940x.img3...
Sending RestoreLogo (15008 bytes)...
ramdisk-size=RELEASE
Extracting 038-3789-001.dmg...
[Error] ERROR: libipatcher failed with reason 
Done: restoring failed.
Failed with errorcode=277

**Comment by tihmstar** [comment]
Looks like you're using an outdated version of libipatcher.
Please retry with version 32 and post log here in case it fails

**Comment by um5566** [comment]
I looked in iphonedevwiki it says the ramdisks are not encrypted.

**Comment by tihmstar** [comment]
indeed. I'll fix this :)

**Comment by tihmstar** [comment]
Can you check whether it is fixed in https://github.com/tihmstar/libipatcher/commit/8a067e6a0d81ef704057383b4a2ec3d64a0da771

**Comment by um5566** [comment]
I can't right now. Try restoring to 9A405 and got "ramrod_ticket_update: invalid ticket". Maybe futurerestore doesn't work when downgrading to ios 5?

**Comment by tihmstar** [comment]
If you are sure that your ticket is fine, than this is probably an issue with libipatcher. 
I need to check whether the patches are correct. Sounds like one of them is wrong.

**Comment by um5566** [comment]
Yep, ticket verified by ifaith.

**Comment by cj123** [comment]
in certain cases, ramdisks weren't encrypted (around iOS 5/6 iirc) - so keys don't exist for those as they're not required ;)

**Comment by tihmstar** [comment]
Can you check if libipatcher v37 fixed the issue https://github.com/tihmstar/libipatcher/commit/1f5e67ba921fba493524b62e430d08f775310554 ?

**Comment by um5566** [comment]
Error while compiling:
/usr/bin/ld: cannot find -lcommon
/usr/bin/ld: cannot find -lxpwn
