### ISSUE TITLE
iOS 10.2.1 generating the same nonce

### ISSUE THREAD

**Issue by toniqyteza** [tihmstar/futurerestore#148]
I have just seen a post in reddit that a guy used yalu 102 and kernel paniced when he went to try futurerestore it was generating the same nonce. I tried that too and worked. Is this useful for anything?
Note: I am on iOS 10.2.1 ip5s 
![00000](https://user-images.githubusercontent.com/25407594/28413720-f4e22d5c-6d48-11e7-864b-d88242e385d9.png)

**Comment by toniqyteza** [comment]
sorry this isn't an issue but i hope you can do something for this

**Comment by jihyo-song** [comment]
Well, actually you lucky, because you can save blobs 10.3.2 & 10.3.3 with that nonce. So basically you can upgrade to 10.3.2/10.3.3 without jailbreak because that nonce still there forever. Don't know actually what's wrong, try reset all content and setting for clear nonce/generator in nvram. Correct me if i'm wrong.

**Comment by toniqyteza** [comment]
You are partialy right.
I did this on purpose i think this is a bug that its fixed on 10.3.1 i can do that actually it is stuck on the same nonce actually and i can take advantage of it but i hope tihmstar can take advantage of it too.

**Comment by jihyo-song** [comment]
I think it's bug on all ios 10.x, because my device 5s was keep [generated same nonce in 10.3.1](https://ghostbin.com/paste/3c389) But now i can't do that again, because i accidentally re-restoring my device to 10.3.1 via itunes while 10.3.1 still signed :/

**Comment by toniqyteza** [comment]
Well i do that every time i just press go on yalu102 for 5 times and when it says failed, retry it reboots and nonce is the same
Try this modified yalu, it worked for me.
https://www.mediafire.com/file/5y308xcxc5q8in9/modified_yalu.zip
