### ISSUE TITLE
It requests imobiledevice >= 1.2.1, but 1.2.0 is the latest version

### ISSUE THREAD

**Issue by Elronnd** [tihmstar/futurerestore#15]

**Comment by meinname** [comment]
Just edit the configure.ac ;)

**Comment by nicnic2001** [comment]
sudo apt install checkinstall

run that^
./autogen.sh or ./configure (don't remember which) then run sudo checkinstall then you'll see you can change the version. change it to 1.2.1.

**Comment by Elronnd** [comment]
Yeah, but still, it should be in base.  Also, nicnic2001, why do you assume I run a debian variant!  That's OSist!  I'm so tired of all the *misogyny* on teh internets!

**Comment by tihmstar** [comment]
i tested it with the latest version of libimobiledevice which is 1.2.1
if it's not available in your repositories, just compile from github.
