### ISSUE TITLE
iOS 9.3.5 to 6.1.3 downgrade error -3

### ISSUE THREAD

**Issue by BlackCatTB** [tihmstar/futurerestore#152]
hi i need help i wached this vid: https://youtu.be/oSvburpZoI8 
and after going some trubbleshuting but now i'm stuck here HELP:

 ./futurerestore_macos -p BuildManifest.plist -b Trek-3.4.03.Release.bbfw --use-pwndfu -t blob.shsh2 iPad2,1_6.1.3_10B329_Restore.ipsw
Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: a6cc5cfa8d421987d06f6157130ef3c75391efa4 - 39
Odysseus Support: yes
[INFO] 32bit device detected
futurerestore init done
reading ticket blob.shsh2 done
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=94&MESSAGE=This device isn't eligible for the requested build.
ERROR: TSS request failed (status=94, message=This device isn't eligible for the requested build.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed
Failed with errorcode=-3

HELP

**Comment by Lucaso123a** [comment]
you must use "--use-pwndfu" for odysseus method (your iPad2,1 also must be in kdfu mode); also, I don't think iPad2,1 has a baseband, so just use "--no-baseband." I recommend use OdysseusOTA for just downgrading 6.1.3 (OTA)

**Comment by shp0ng13** [comment]
use kDFUapp and futurerestore together, you need to use both "--use-pwndfu" & "--no-baseband"
