### ISSUE TITLE
Stuck on DFU mode after successful downgrade

### ISSUE THREAD

**Issue by larxene066** [tihmstar/futurerestore#154]
I'm trying to take my 9.3.5 iPad3,1 to 6.1.2 (because I have the blobs for 6.1.2 and not 6.1.3 apparently). All goes well until the very end. Terminal reads: "Got status message Status: Restore Finished Cleaning up... DONE Done: restoring succeeded." ...but my iPad remains in DFU mode mode and won't respond to anything (even holding lock and home). This is about my tenth time trying, on my machine and three others - same thing. I've tried kicking it out of DFU with rec/reiboot and nothing happens, I just have to endlessly restore. Any ideas what's going on?

**Comment by Lucaso123a** [comment]
You may want to use validate (a executable in odysseus to check whether your blobs are valid) to check your blobs. It looks like your blobs are invalid since you stuck in DFU after restore. If I am not wrong, there is an accident at that time (all blobs for iOS 6.0-6.1.2 saved by cydia are broken).

**Comment by Blu3DevGit** [comment]
Are your blobs from Cydia? If yes, they are corrupt. [Read here](https://www.theiphonewiki.com/wiki/Cydia_SHSH_Server#iOS_6_update)

**Comment by larxene066** [comment]
Thank you so much for the comments guys - my blobs were the issue. I ended up finding a 5.1.1 blob and successfully restoring to that. Thanks again!!

**Comment by tihmstar** [comment]
Yep, unfortunatelly futurerestore does not validate SHSH blobs for LLB and APTicket for pwndfu downgrade :(
