### ISSUE TITLE
Linux Building Issue (Debain 7)

### ISSUE THREAD

**Issue by xnuos** [tihmstar/futurerestore#16]
When I execute 'make' in the 'futurerestore/'  directory and got the response:  

root@localhost:/home/eclipse/.iOS/futurerestore# make
make  all-recursive
make[1]: Entering directory '/home/eclipse/.iOS/futurerestore'
Making all in external/idevicerestore
make[2]: Entering directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
make  all-recursive
make[3]: Entering directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
Making all in src
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore/src'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore/src'
Making all in docs
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore/docs'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore/docs'
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
make[3]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
make[2]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/idevicerestore'
Making all in external/img4tool
make[2]: Entering directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
make  all-recursive
make[3]: Entering directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
Making all in img4tool
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/img4tool/img4tool'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/img4tool/img4tool'
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
make[3]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
make[2]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/img4tool'
Making all in external/tsschecker
make[2]: Entering directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
make  all-recursive
make[3]: Entering directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
Making all in tsschecker
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/tsschecker/tsschecker'
make[4]: Nothing to be done for 'all'.
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/tsschecker/tsschecker'
make[4]: Entering directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
make[4]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
make[3]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
make[2]: Leaving directory '/home/eclipse/.iOS/futurerestore/external/tsschecker'
Making all in futurerestore
make[2]: Entering directory '/home/eclipse/.iOS/futurerestore/futurerestore'
g++ -DHAVE_CONFIG_H -I. -I..    -I/usr/include/libxml2 -I/usr/lib/x86_64-linux-gnu/libzip/include -I/usr/local/include -I/usr/include/libxml2 -I/usr/local/include -I/usr/local/include -I/usr/include/libusb-1.0 -I../external/tsschecker/tsschecker -I../external/img4tool/img4tool -I../external/idevicerestore/src -std=c++11 -g -O2 -MT futurerestore-futurerestore.o -MD -MP -MF .deps/futurerestore-futurerestore.Tpo -c -o futurerestore-futurerestore.o `test -f 'futurerestore.cpp' || echo './'`futurerestore.cpp
futurerestore.cpp: In member function ‘int futurerestore::doRestore(const char*, bool)’:
futurerestore.cpp:336:13: error: ‘struct idevicerestore_client_t’ has no member named ‘bbfwtmp’
     client->bbfwtmp = (char*)_basebandPath;
             ^
futurerestore.cpp:453:36: error: ‘struct idevicerestore_client_t’ has no member named ‘sepnonce’
     get_sep_nonce(client, &client->sepnonce, &client->sepnonce_si
                                    ^
futurerestore.cpp:453:55: error: ‘struct idevicerestore_client_t’ has no member named ‘sepnonce_size’
     get_sep_nonce(client, &client->sepnonce, &client->sepnonce_si
                                                       ^
futurerestore.cpp:467:63: error: ‘struct idevicerestore_client_t’ has no member named ‘septss’
 get_tss_response(client, sep_build_identity, &client->septss) < 0
                                                       ^
futurerestore.cpp:472:13: error: ‘struct idevicerestore_client_t’ has no member named ‘basebandBuildIdentity’
     client->basebandBuildIdentity = getBuildidentity(_basebandbui
             ^
futurerestore.cpp:474:19: error: ‘struct idevicerestore_client_t’ has no member named ‘basebandBuildIdentity’
     if (!_client->basebandBuildIdentity)
                   ^
futurerestore.cpp:478:19: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if (!_client->sepfwdatasize || !_client->sepfwdata)
                   ^
futurerestore.cpp:478:46: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if (!_client->sepfwdatasize || !_client->sepfwdata)
                                              ^
futurerestore.cpp:495:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:46:27: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                           ^
futurerestore.cpp:495:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:46:37: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                                     ^
futurerestore.cpp:495:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:46:43: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                                           ^
futurerestore.cpp: In member function ‘void futurerestore::loadSep(const char*)’:
futurerestore.cpp:623:14: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     _client->sepfwdatasize = ftell(fsep);
              ^
futurerestore.cpp:626:20: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if (!(_client->sepfwdata = (char*)malloc(_client->sepfwdatasi
                    ^
futurerestore.cpp:626:55: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if (!(_client->sepfwdata = (char*)malloc(_client->sepfwdatasi
                                                       ^
futurerestore.cpp:629:24: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if (fread(_client->sepfwdata, 1, _client->sepfwdatasize, fsep
                        ^
futurerestore.cpp:629:47: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if (fread(_client->sepfwdata, 1, _client->sepfwdatasize, fsep
                                               ^
futurerestore.cpp:629:80: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
 pfwdata, 1, _client->sepfwdatasize, fsep) != _client->sepfwdatasi
                                                       ^
Makefile:451: recipe for target 'futurerestore-futurerestore.o' failed
make[2]: *** [futurerestore-futurerestore.o] Error 1
make[2]: Leaving directory '/home/eclipse/.iOS/futurerestore/futurerestore'
Makefile:419: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/eclipse/.iOS/futurerestore'
Makefile:351: recipe for target 'all' failed
make: *** [all] Error 2

Now my idevicerestore (which is a separate libimobiledevice issue) experiences a core dump on execution. (I'm fixing that issue which hopefully will resolve this, but if you see anything else in my log that would make the install fail can you let me know please).

What should I do?

**Comment by tihmstar** [comment]
this should be fixed with the new autotools build system

**Comment by kabnaj** [comment]
same on Debian 8 (Jessie)
# cat /etc/debian_version 
8.7
(and I even tried on Debian testing with the same result)

$ make
g++ -DHAVE_CONFIG_H -I. -I..    -I/usr/local/include  -I/usr/lib/x86_64-linux-gnu/libzip/include  -I/usr/local/include  -I/usr/local/include  -I/usr/local/include -I/usr/include/libusb-1.0  -I../external/tsschecker/tsschecker -I../external/img4tool/img4tool -I../external/idevicerestore/src -std=c++11 -g -O2 -MT futurerestore-futurerestore.o -MD -MP -MF .deps/futurerestore-futurerestore.Tpo -c -o futurerestore-futurerestore.o `test -f 'futurerestore.cpp' || echo './'`futurerestore.cpp
futurerestore.cpp: In member function ‘int futurerestore::doRestore(const char*, bool)’:
futurerestore.cpp:368:23: error: ‘struct idevicerestore_client_t’ has no member named ‘basebandBuildIdentity’
         if (!(client->basebandBuildIdentity = getBuildidentityWithBoardconfig(_basebandbuildmanifest, client->device->hardware_model, noerase)))
                       ^
futurerestore.cpp:370:17: error: ‘struct idevicerestore_client_t’ has no member named ‘bbfwtmp’
         client->bbfwtmp = (char*)_basebandPath;
                 ^
futurerestore.cpp:372:59: error: ‘struct idevicerestore_client_t’ has no member named ‘basebandBuildIdentity’
         plist_t bb_manifest = plist_dict_get_item(client->basebandBuildIdentity, "Manifest");
                                                           ^
futurerestore.cpp:376:23: error: ‘struct idevicerestore_client_t’ has no member named ‘basebandBuildIdentity’
         if (!_client->basebandBuildIdentity)
                       ^
futurerestore.cpp:507:36: error: ‘struct idevicerestore_client_t’ has no member named ‘sepnonce’
     get_sep_nonce(client, &client->sepnonce, &client->sepnonce_size);
                                    ^
futurerestore.cpp:507:55: error: ‘struct idevicerestore_client_t’ has no member named ‘sepnonce_size’
     get_sep_nonce(client, &client->sepnonce, &client->sepnonce_size);
                                                       ^
futurerestore.cpp:528:63: error: ‘struct idevicerestore_client_t’ has no member named ‘septss’
     if (get_tss_response(client, sep_build_identity, &client->septss) < 0) {
                                                               ^
futurerestore.cpp:534:19: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if (!_client->sepfwdatasize || !_client->sepfwdata)
                   ^
futurerestore.cpp:534:46: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if (!_client->sepfwdatasize || !_client->sepfwdata)
                                              ^
futurerestore.cpp:551:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:58:27: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                           ^
futurerestore.cpp:551:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:58:37: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                                     ^
futurerestore.cpp:551:22: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     safeFree(client->sepfwdata);
                      ^
futurerestore.cpp:58:43: note: in definition of macro ‘safeFree’
 #define safeFree(buf) if (buf) free(buf), buf = NULL
                                           ^
futurerestore.cpp: In member function ‘void futurerestore::loadSep(const char*)’:
futurerestore.cpp:692:14: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     _client->sepfwdatasize = ftell(fsep);
              ^
futurerestore.cpp:695:20: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if (!(_client->sepfwdata = (char*)malloc(_client->sepfwdatasize)))
                    ^
futurerestore.cpp:695:55: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if (!(_client->sepfwdata = (char*)malloc(_client->sepfwdatasize)))
                                                       ^
futurerestore.cpp:699:36: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdata’
     if ((freadRet = fread(_client->sepfwdata, 1, _client->sepfwdatasize, fsep)) != _client->sepfwdatasize)
                                    ^
futurerestore.cpp:699:59: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if ((freadRet = fread(_client->sepfwdata, 1, _client->sepfwdatasize, fsep)) != _client->sepfwdatasize)
                                                           ^
futurerestore.cpp:699:93: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
     if ((freadRet = fread(_client->sepfwdata, 1, _client->sepfwdatasize, fsep)) != _client->sepfwdatasize)
                                                                                             ^
In file included from futurerestore.cpp:23:0:
futurerestore.cpp:700:88: error: ‘struct idevicerestore_client_t’ has no member named ‘sepfwdatasize’
         reterror(-15, "failed to load SEP. size=%zu but fread returned %zu\n",_client->sepfwdatasize,freadRet);
                                                                                        ^
../external/tsschecker/tsschecker/all_tsschecker.h:18:48: note: in definition of macro ‘error’
 #define error(a ...) printf("[Error] "),printf(a)
                                                ^
futurerestore.cpp:700:9: note: in expansion of macro ‘reterror’
         reterror(-15, "failed to load SEP. size=%zu but fread returned %zu\n",_client->sepfwdatasize,freadRet);
         ^
Makefile:440: recipe for target 'futurerestore-futurerestore.o' failed
make: *** [futurerestore-futurerestore.o] Error 1

which tool from autotools and which version should be fixing this?
error: ‘struct idevicerestore_client_t’ has no member named ‘some_name'

**Comment by kabnaj** [comment]
only FYI, compilation errors appeared when I cloned latest external repos: idevicerestore,img4tool,tsschecker
If I'm using correct commits, everything is fine:
$ cd futurerestore/external
$ git submodule update --init --recursive
