### ISSUE TITLE
trying to downgrade a iPad mini 2,5 (wifi) to iOS 8.4.1 using a ota shsh blob

### ISSUE THREAD

**Issue by jst9n** [tihmstar/futurerestore#164]
MacBook-Pro:desktop name$ /Users/name/Desktop/futurerestore_macos -t /Users/name/Desktop/ECID_iPad2\,5_8.4.1-12H321_9dea48a0cd6a5c539a09042ce84c8e886bea1f7b.shsh2 --use-pwndfu --no-baseband /Users/name/Desktop/iPad2\,5_8.4.1_12H321_Restore.ipsw 
Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: a6cc5cfa8d421987d06f6157130ef3c75391efa4 - 39
Odysseus Support: yes
ERROR: Device is in an invalid state
[INFO] 32bit device detected
[Error] can't init, no device found
Failed with errorcode=-3

**Comment by jst9n** [comment]
fixed by myself, sorry.

**Comment by vbachani** [comment]
Hi, I am getting the same error but can't seem to fix it—how did you fix it?

**Comment by nstuj** [comment]
try unpluging the device and pluging it back in

**Comment by vbachani** [comment]
Thanks, that did seem to work, but then it stalled on "Unknown data request 'DeviceTree' received" and I had to restore to the latest iOS (11.2.2). Oh well.
