### ISSUE TITLE
GENERATING SAME NONCE

### ISSUE THREAD

**Issue by alukarulz** [tihmstar/futurerestore#17]
Everything works fine until futurerestore starts generating **same nonce** each time it reboots into recovery. downgrading from **10.2 to 10.1.1** iphone 6s+.
I have the **shsh** files. And here is my command

`./futurerestore_macos -t 1.shsh2 -t 2.shsh2 -t 3.shsh2 -t 4.shsh2 -t 5.shsh2 -t 6.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n66.RELEASE.im4p -m BuildManifest.plist -w iPhone_5.5_10.1.1_14B150_Restore.ipsw`

**Comment by d3vilsn0w** [comment]
Getting the same issue.

**Comment by tihmstar** [comment]
Same nonce is not a futurerestore issue. 
Apple has fucked something up in iOS 10. For some reason the generator is not clear from nvram when the device reboots into/from recovery. This is why it generates the same nonce over and ober again. 
Besides, iPhone6s is afaik not vulnerable to the collision attack anayways.
