### ISSUE TITLE
Error 132

### ISSUE THREAD

**Issue by justin2926** [tihmstar/futurerestore#170]
When I try downgrading my iPhone 7 from 11.0.2 to 10.2.1, it gives me this error.
My SHSH2 Blobs are valid. Can you guys help me fix this issue?

Version: b99eb8140d8e6c23f34e950102bb79e61c72384d - 152
Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
Odysseus Support: yes
[INFO] 64bit device detected
futurerestore init done
reading ticket iPhone9,3_d101ap_10.2.1_14D27.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=132&MESSAGE=An internal error occurred.
ERROR: tss_send_request: Unhandled status code 132
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2

**Comment by justin2926** [comment]
> When I try downgrading my iPhone 7 from 11.0.2 to 10.2.1, it gives me this error.
> My SHSH2 Blobs are valid. Can you guys help me fix this issue?
> 
> Version: b99eb81 - 152
> Libipatcher Version: f32e41d850f51448bd6c588ead9c7d6455733f3c - 44
> Odysseus Support: yes
> [INFO] 64bit device detected
> futurerestore init done
> reading ticket iPhone9,3_d101ap_10.2.1_14D27.shsh2 done
> [TSSC] opening BuildManifest.plist
> WARNING: Unable to find BbSkeyId node
> [TSSR] User specified not to request a Baseband ticket.
> Request URL set to https://gs.apple.com/TSS/controller?action=2
> Sending TSS request attempt 1... response successfully received
> Did set sep+baseband path and firmware
> [TSSC] opening BuildManifest.plist
> WARNING: Unable to find BbSkeyId node
> [TSSR] User specified to request only a Baseband ticket.
> ERROR: Unable to get BasebandFirmware node
> ERROR: Unable to find required BbGoldCertId in parameters
> Request URL set to https://gs.apple.com/TSS/controller?action=2
> TSS server returned: STATUS=132&MESSAGE=An internal error occurred.
> ERROR: tss_send_request: Unhandled status code 132
> Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2

**EDIT:** It now says 

> Sending TSS request attempt 15... [Error] baseband firmware isn't signed
> Failed with errorcode=-3

**Comment by Lucaso123a** [comment]
noncecollision method has already been patched; you will need jailbreak to downgrade.

iOS 11 SEP is not compatible with iOS 10 (not tested but should be true); even if you are super lucky to get matched nonce, your device still cannot boot normally.

**Comment by justin2926** [comment]
Ok thanks!
