### ISSUE TITLE
Downgrade ios 11.2 to ios 10.3.3 with blobs on iohone 6s

### ISSUE THREAD

**Issue by ijamsahidon** [tihmstar/futurerestore#190]
Hello tihmstar ..can you teach me how to downgrade ios 11.2 to ios 10.3.3 using blobs because when i downgrade always show error code =-3 and always detected 32 bit device ?and show same apNonce when i downgrade that ..thanks tihmstar ..

**Comment by sazhj** [comment]
Hello tihmstar ..can you teach me how to downgrade iphone 7 plus ios 11.2 to ios 11.00 using shsh2 blobs  tks
