### ISSUE TITLE
Assertion failed: (data), function plist_copy_node, file plist.c, line 323. Abort trap: 6

### ISSUE THREAD

**Issue by diggitydogg** [tihmstar/futurerestore#20]
Using v67 I am getting this error. 
![screen shot 2017-01-02 at 9 11 14 am](https://cloud.githubusercontent.com/assets/7000045/21591663/dacd1ebe-d0cb-11e6-9992-7a04e789028c.png)

**Comment by tihmstar** [comment]
Does that issue still exist in latest version (v84) ?

**Comment by diggitydogg** [comment]
The latest build is unavailable to download. I tried building from here, but I have't ever done it and don't understand the errors that arise when I try. This is where it fails out: http://pastebin.com/dYvrHVaU

**Comment by diggitydogg** [comment]
It now gets through to a point where it fails due to the wrong board config for the ticket. It saved a ticket for an iPad Air (j71ap) instead of iPad Mini 2 (j85ap). Obv this was saved before it came to light about the board configs. I'd say this can be closed now. Thanks!
