### ISSUE TITLE
Stuck at "Unknown data request 'DeviceTree' received"

### ISSUE THREAD

**Issue by KpwnZ** [tihmstar/futurerestore#204]
iOS 10.2 -> iOS 11.1.2 with shsh2

Extracting kernelcache.release.iphone6...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
Unknown data request 'DeviceTree' received...

Generator was reset, updated to the latest version.

**Comment by goodboydheeraj** [comment]
You should have known better :( tihmstar's futurerestore isn't updated for iOS 11 yet!

use this next time https://github.com/encounter/futurerestore/releases/

**Comment by liyang-bsy** [comment]
Me too T^T

**Comment by Anonymous341** [comment]
Perhaps tihmstar should discontinue his fork. I saw his readme.md I downloaded the precompiled version, just two weeks ago I downloaded  encounter's version and it was nowhere to be found until now. I just restored to 11.2.6 after wanting a fresh start on 11.1.2, things were working well, until I went and restore. I'm so pissed now, I lost my jailbreak which makes the phone unusable.

**Comment by goodboydheeraj** [comment]
You should use encounter’s ipdated futurerestore fork that works with iOS 11. Don’t blame others for your mistake
