### ISSUE TITLE
Puts my device into recovery mode and then says "Unable to place device into recovery mode from Normal mode"

### ISSUE THREAD

**Issue by Elronnd** [tihmstar/futurerestore#21]
I get the following:

    $ ../.futurerestore-install/bin/futurerestore -t ../shsh-i6s/10.1.1/apnonce-0dc448240696866b0cc1b2ac3eca4ce22af11cb3/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 -t ../shsh-i6s/10.1.1/apnonce-352dfad1713834f4f94c5ff3c3e5e99477347b95/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 -t ../shsh-i6s/10.1.1/apnonce-42c88f5a7b75bc944c288a7215391dc9c73b6e9f/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 -t ../shsh-i6s/10.1.1/apnonce-603be133ff0bdfa0f83f21e74191cf6770ea43bb/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 -t ../shsh-i6s/10.1.1/apnonce-9804d99e85bbafd4bb1135a1044773b4df9f1ba3/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.1.1_14B150_Restore.ipsw
    Version: bdc7cc1542c5fecb9ddac4c9134a0c546687caa9 - 52
    futurerestore init done
    reading ticket ../shsh-i6s/10.1.1/apnonce-0dc448240696866b0cc1b2ac3eca4ce22af11cb3/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 done
    reading ticket ../shsh-i6s/10.1.1/apnonce-352dfad1713834f4f94c5ff3c3e5e99477347b95/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 done
    reading ticket ../shsh-i6s/10.1.1/apnonce-42c88f5a7b75bc944c288a7215391dc9c73b6e9f/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 done
    reading ticket ../shsh-i6s/10.1.1/apnonce-603be133ff0bdfa0f83f21e74191cf6770ea43bb/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 done
    reading ticket ../shsh-i6s/10.1.1/apnonce-9804d99e85bbafd4bb1135a1044773b4df9f1ba3/3903291615516_iPhone8,1_10.1.1-14B150.shsh2 done
    Did set sep+baseband path and firmware
    [TSSC] opening BuildManifest.plist
    WARNING: Unable to find BbSkeyId node
    [TSSR] User specified not to request a Baseband ticket.
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    [TSSC] opening BuildManifest.plist
    WARNING: Unable to find BbSkeyId node
    [TSSR] User specified to request only a Baseband ticket.
    ERROR: Unable to get BasebandFirmware node
    ERROR: Unable to find required BbGoldCertId in parameters
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    Found device in Normal mode
    Entering recovery mode...

At this point my device rebooted and then entered recovery mode.  Then futurerestore hung for a while.  Finally, 

    ERROR: Unable to connect to device in recovery mode
    ERROR: Unable to enter recovery mode
    [Error] Unable to place device into recovery mode from Normal mode
    [Error] Fail code=-2
    Failed with errorcode=-2
    $ 

Then I have to flash 10.2 from itunes to make the phone boot again.

**Comment by tihmstar** [comment]
iPhone 6s is not vulnerable to collision attack

**Comment by Elronnd** [comment]
You sure?  Someone on reddit said they got collisions after 8000 tries or something like that.

**Comment by aToxyD** [comment]
Thank you for this great tool.
I have the same problem with IPhone SE

**Comment by Elronnd** [comment]
Are you running as root?

**Comment by DistinctCancer** [comment]
what do you mean by running as root?
