### ISSUE TITLE
Error 11 Stuck cant enter phone tried -w

### ISSUE THREAD

**Issue by CptJacksCarro** [tihmstar/futurerestore#219]
C:\Users\andyc\Downloads\futurerestore_win64_v173\futurerestore_win64_v173>futurerestore -t my.shsh2 -i signed.ipsw restoreto.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket my.shsh2 done
Found device iPhone8,1 n71map
Extracting SEP from IPSW...
Extracting sep-firmware.n71m.RELEASE.im4p...
Extracted SEP with size 5206159
[TSSC] opening download/sepManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Extracting baseband from IPSW...
Extracting Mav13-4.30.02.Release.bbfw...
Extracted BasebandFirmware with size 31604124
[TSSC] opening download/basebandManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is F4GRL1W3GRXY
Found device in Recovery mode
Identified device as n71map, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 11.1.2
Product Build: 15B202 Major: 15
Device supports Image4: true
Got APNonce from device: 48 50 f9 0b b0 9d 56 9e 5d f0 9e 43 ee 9d e1 18 d0 36 60 dc
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.n71m.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (354519 bytes)...
waiting for device to reconnect...
Getting SepNonce in recovery mode... e3 a5 3f 7a 54 49 0a 74 5e d9 1c a0 2b a8 5e c1 b5 41 10 42
Getting ApNonce in recovery mode... 48 50 f9 0b b0 9d 56 9e 5d f0 9e 43 ee 9d e1 18 d0 36 60 dc
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4076.20.48
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12214 bytes)...
ramdisk-size=0x20000000
Extracting 058-84556-102.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (59139669 bytes)...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (133395 bytes)...
Extracting kernelcache.release.n71...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (14093292 bytes)...
Trying to fetch new SHSH blob
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device ffffffffffffffffffffffffffffffff00000066 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000066 has successfully entered restore mode
Hardware Information:
BoardID: 4
ChipID: 32771
UniqueChipID: 2902917401510438
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.n71m.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.n71m.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
Done sending filesystem
Verifying restore (14)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
About to send KernelCache...
Extracting kernelcache.release.n71...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
About to send DeviceTree...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component DeviceTree...
Sending DeviceTree now...
Done sending DeviceTree
Certifying Savage (61)
Flashing firmware (18)
Updating gas gauge software (47)
Updating gas gauge software (47)
Updating Stockholm (55)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-s8000aop.im4p...
Personalizing IMG4 component AOP...
Sending FUD data now...
Done sending FUD data
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-s8000aop.im4p...
Personalizing IMG4 component AOP...
Sending FUD data now...
Done sending FUD data
Updating baseband (19)
About to send BasebandData...
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
ERROR: Could not open ZIP archive 'C:\Users\andyc\AppData\Local\Temp\ffffffffffffffffffffffffffffffff000000662': 19
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

Absolutely no clue what happened here it seemed to be going well until first error could not open zip archive

**Comment by CptJacksCarro** [comment]
Going from ios 10.0.2 Jailbroken to Ios 11.1.2. I did set nonace before doing so and there shouldnt be any problems with the shsh file.

**Comment by pauls85** [comment]
I just had the same issue yesterday. iPhone 6s on 10.2 going to 11.1.2. Everything seemed normal until the end.  

Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
[INFO] 64bit device detected
futurerestore init done
reading ticket my.shsh2 done
Found device iPhone8,1 n71map
Extracting SEP from IPSW...
Extracting sep-firmware.n71m.RELEASE.im4p...
Extracted SEP with size 5206159
[TSSC] opening download/sepManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Extracting baseband from IPSW...
Extracting Mav13-4.30.02.Release.bbfw...
Extracted BasebandFirmware with size 31604124
[TSSC] opening download/basebandManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is 
Found device in Recovery mode
Identified device as n71map, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 11.1.2
Product Build: 15B202 Major: 15
Device supports Image4: true
Got APNonce from device: bd 11 85 29 f0 da 4c 9c 70 66 4f 09 9a f8 46 30 f0 13 9e 8f
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.n71m.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (354519 bytes)...
waiting for device to reconnect...
Getting SepNonce in recovery mode... 8a 1d cd 77 45 30 db 63 49 ba 22 f0 6a 6a ae 68 be 40 b6 1d
Getting ApNonce in recovery mode... bd 11 85 29 f0 da 4c 9c 70 66 4f 09 9a f8 46 30 f0 13 9e 8f
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4076.20.48
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12214 bytes)...
ramdisk-size=0x20000000
Extracting 058-84556-102.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (59139669 bytes)...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (133395 bytes)...
Extracting kernelcache.release.n71...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (14093292 bytes)...
Trying to fetch new SHSH blob
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device ffffffffffffffffffffffffffffffff00000004 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000004 has successfully entered restore mode
Hardware Information:
BoardID: 4
ChipID: 32771
UniqueChipID: 3461477767963578
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.n71m.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component DeviceTree...
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.n71m.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
Done sending filesystem
Verifying restore (14)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
About to send KernelCache...
Extracting kernelcache.release.n71...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
About to send DeviceTree...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component DeviceTree...
Sending DeviceTree now...
Done sending DeviceTree
Certifying Savage (61)
Flashing firmware (18)
Updating gas gauge software (47)
Updating gas gauge software (47)
Updating Stockholm (55)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-s8000aop.im4p...
Personalizing IMG4 component AOP...
Sending FUD data now...
Done sending FUD data
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-s8000aop.im4p...
Personalizing IMG4 component AOP...
Sending FUD data now...
Done sending FUD data
Updating baseband (19)
About to send BasebandData...
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
ERROR: Could not open ZIP archive 'C:\Users\Tara\AppData\Local\Temp\ffffffffffffffffffffffffffffffff000000042': 19
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by DaveCaro** [comment]
Has anyone found a solution?  I cannot get my phone to boot now
