### ISSUE TITLE
./futurerestore_linux: error while loading shared libraries: libzip.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by TheR3dDuck** [tihmstar/futurerestore#24]
Every time i try to do this on:
3 MacBooks on macos Sierra
2 Linux Machines
I get the same error.
I have made modifications on all systems to try to make it work, but no luck.

"./futurerestore_linux: error while loading shared libraries: libzip.so.2: cannot open shared object file: No such file or directory" error code.

**Comment by nicogibbons** [comment]
You need libzip.

**Comment by superE03** [comment]
I have this problem too, with libzip installed
