### ISSUE TITLE
dyld: Library not loaded: /opt/local/lib/libcrypto.1.0.0.dylib

### ISSUE THREAD

**Issue by adi2k17** [tihmstar/futurerestore#25]
Help when I try to run futurestore it says dyld: Library not loaded: /opt/local/lib/libcrypto.1.0.0.dylib
  Reason: image not found
Abort trap: 6) Help please

**Comment by nicogibbons** [comment]
You need more dependencies.

**Comment by adi2k17** [comment]
How can I get more dependencies

**Comment by derobi** [comment]
do you have lib crypto installed already 

if not let me know so i can help you

**Comment by derobi** [comment]
![screen shot 2017-01-26 at 6 08 27 pm](https://cloud.githubusercontent.com/assets/14483283/22355785/78c41c9c-e3f2-11e6-8579-5e3982ca34b2.jpg)

**Comment by adi2k17** [comment]
Yeah Thank You But I got It>:)

**Comment by khoahuynh47** [comment]
thank 2Klasic
