### ISSUE TITLE
Failed with errorcode=-11

### ISSUE THREAD

**Issue by jerryliu1011** [tihmstar/futurerestore#257]
C:\Users\jerry>cd C:\Users\jerry\Desktop\futurerestore_win64_v173

C:\Users\jerry\Desktop\futurerestore_win64_v173>futurerestore -t 4618524445762854_iPhone9,3_d101ap_11.3.1-15E302_d1c174a75d7af39a3c8e6c0677c2b3f7c241d05f1dba8bf1a6aea7c1469d6f9b.shsh2 -b Mav16-3.70.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.d101.RELEASE.im4p -m BuildManifest.plist iPhone_4.7_P3_11.0_11.3.1_15E302_Restore.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
INFO: device serial number is C6KS9LM8HG7Q
[INFO] 64bit device detected
futurerestore init done
reading ticket 4618524445762854_iPhone9,3_d101ap_11.3.1-15E302_d1c174a75d7af39a3c8e6c0677c2b3f7c241d05f1dba8bf1a6aea7c1469d6f9b.shsh2 done
Found device iPhone9,3 d101ap
[TSSC] opening BuildManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as d101ap, iPhone9,3
Extracting BuildManifest from IPSW
Product Version: 11.3.1
Product Build: 15E302 Major: 15
Device supports Image4: true
Got APNonce from device: d1 c1 74 a7 5d 7a f3 9a 3c 8e 6c 06 77 c2 b3 f7 c2 41 d0 5f 1d ba 8b f1 a6 ae a7 c1 46 9d 6f 9b
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.d10.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (439094 bytes)...
waiting for device to reconnect...
Getting SepNonce in recovery mode... cc 99 ec 2d 17 40 1b e4 ad 2b 56 97 47 ac 53 cf 77 8c 54 51
Getting ApNonce in recovery mode... d1 c1 74 a7 5d 7a f3 9a 3c 8e 6c 06 77 c2 b3 f7 c2 41 d0 5f 1d ba 8b f1 a6 ae a7 c1 46 9d 6f 9b
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4076.50.126
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12820 bytes)...
ramdisk-size=0x20000000
Extracting 058-97541-138.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (79287987 bytes)...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (153126 bytes)...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (15630385 bytes)...
Trying to fetch new SHSH blob
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device...
Waiting for device...
Device ffffffffffffffffffffffffffffffff00000003 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000003 has successfully entered restore mode
Hardware Information:
BoardID: 12
ChipID: 32784
UniqueChipID: 4618524445762854
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d10.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1334~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d10.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
Done sending filesystem
Verifying restore (14)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
About to send KernelCache...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
About to send DeviceTree...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component DeviceTree...
Sending DeviceTree now...
Done sending DeviceTree
Certifying Savage (61)
Flashing firmware (18)
Updating gas gauge software (47)
Updating gas gauge software (47)
Updating Stockholm (55)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D101.im4p...
Personalizing IMG4 component Homer...
Sending FUD data now...
Done sending FUD data
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D101.im4p...
Personalizing IMG4 component Homer...
Sending FUD data now...
Done sending FUD data
Updating baseband (19)
About to send BasebandData...
sending request without baseband nonce
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
ERROR: can't locate 'psi_ram.bin' in 'C:\Users\jerry\AppData\Local\Temp\ffffffffffffffffffffffffffffffff000000032'
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

C:\Users\jerry\Desktop\futurerestore_win64_v173>futurerestore

**Comment by BatrakovSV** [comment]
Hello. How did you solve this question?

**Comment by Nosskirneh** [comment]
Also getting this:
```
~/Unsynced documents/futurerestoring » ./futurerestore -t 379348986626086_iPhone9,3_d101ap_13.3-17C54_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2 -s sep-firmware.d101.RELEASE.im4p -b Mav16-7.30.01.Release.bbfw -m BuildManifest_1331.plist -p BuildManifest_1331.plist ipsw/iPhone_4.7_P3_13.3_17C54_Restore.ipsw
Version: 81b98e0425e17250cc83d5badaf9a8cc6399f481 - 245
Libipatcher version: 3159a387584e352f690cca859e013c3a4683f3e8 - 69
Odysseus support: yes
INFO: device serial number is DX3WR7LCHG7F
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket 379348986626086_iPhone9,3_d101ap_13.3-17C54_27325c8258be46e69d9ee57fa9a8fbc28b873df434e5e702a8b27999551138ae.shsh2 is done
Found device iPhone9,3 d101ap
[TSSC] opening BuildManifest_1331.plist
[TSSR] User specified not to request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set SEP+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest_1331.plist
[TSSR] User specified to request only a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as d101ap, iPhone9,3
Extracting BuildManifest from iPSW
Product version: 13.3
Product build: 17C54 Major: 17
Device supports IMG4: true
Got ApNonce from device: 27 32 5c 82 58 be 46 e6 9d 9e e5 7f a9 a8 fb c2 8b 87 3d f4 34 e5 e7 02 a8 b2 79 99 55 11 38 ae 
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from iPSW
[==================================================] 100.0%
Extracting iBEC.d10.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (474503 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 59 7e f3 9e 3b 78 da ed 98 51 9e 82 7d 7d 95 7a 59 a3 97 c0 
Getting ApNonce in recovery mode... 27 32 5c 82 58 be 46 e6 9d 9e e5 7f a9 a8 fb c2 8b 87 3d f4 34 e5 e7 02 a8 b2 79 99 55 11 38 ae 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-5540.60.11
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (13090 bytes)...
Extracting 038-02406-072.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (10949 bytes)...
ramdisk-size=0x20000000
Extracting 038-02406-072.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (102052293 bytes)...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (162899 bytes)...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (14205135 bytes)...
Trying to fetch new signing tickets
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received signing tickets
About to restore device... 
Waiting for device...
Device ffffffffffffffffffffffffffffffff00000245 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000245 has successfully entered restore mode
Hardware Information:
BoardID: 12
ChipID: 32784
UniqueChipID: 379348986626086
ProductionMode: true
Starting FDR listener thread
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d10.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@2x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@2x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1334~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1334~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1334~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d10.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
About to send filesystem...
Connected to ASR
Validating the filesystem
Filesystem validated
Sending filesystem now...
[==================================================] 100.0%
Done sending filesystem
Verifying restore (14)
[==================================================] 100.0%
Checking filesystems (15)
Unknown operation (67)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Checking filesystems (15)
Mounting filesystems (16)
Mounting filesystems (16)
Mounting filesystems (16)
About to send KernelCache...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component KernelCache...
Sending KernelCache now...
Done sending KernelCache
Installing kernelcache (27)
About to send DeviceTree...
Extracting DeviceTree.d101ap.im4p...
Personalizing IMG4 component DeviceTree...
Sending DeviceTree now...
Done sending DeviceTree
Certifying Savage (61)
Flashing firmware (18)
[==================================================] 100.0%
Unknown operation (36)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D101.im4p...
Personalizing IMG4 component Homer...
Found FUD component 'RestoreTrustCache'
Extracting 038-02406-072.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Found FUD component 'StaticTrustCache'
Extracting 038-02762-069.dmg.trustcache...
Personalizing IMG4 component StaticTrustCache...
Sending FUD data now...
Done sending FUD data
Updating gas gauge software (47)
Updating gas gauge software (47)
Updating Stockholm (55)
Unknown operation (36)
About to send FUD data...
Found FUD component 'AOP'
Extracting aopfw-t8010aop.im4p...
Personalizing IMG4 component AOP...
Found FUD component 'Homer'
Extracting homer_D101.im4p...
Personalizing IMG4 component Homer...
Found FUD component 'RestoreTrustCache'
Extracting 038-02406-072.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Found FUD component 'StaticTrustCache'
Extracting 038-02762-069.dmg.trustcache...
Personalizing IMG4 component StaticTrustCache...
Sending FUD data now...
Done sending FUD data
Updating baseband (19)
About to send BasebandData...
sending request without baseband nonce
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs
ERROR: can't locate 'psi_ram.bin' in '/var/tmp/ffffffffffffffffffffffffffffffff00000245bhv9hc'
ERROR: Unable to send baseband data
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11
```

**Comment by Nosskirneh** [comment]
So, I assumed [245 was the latest version](https://github.com/s0uthwest/futurerestore/releases), when in reality, 180 was the latest version](https://github.com/tihmstar/futurerestore/releases). I get the same error with 180.
