### ISSUE TITLE
Error -55 when trying to restore to iOS 10.2 from 9.3.3

### ISSUE THREAD

**Issue by leo98gomez** [tihmstar/futurerestore#26]
Im trying to update to iOS 10.2 from iOS 9.3.3 on my iPhone 6s+, but when i run future restore i get Error -55. Here is the screenshot of what shows in terminal. 
This is what I'm running in terminal after setting the nonce with nonceEnabler: /futurerestore -t 7375184523592_iPhone8,2_n66ap_10.2-14C92.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n66.RELEASE.im4p -m BuildManifest.plist restore102.ipsw

<img width="728" alt="screen shot 2017-01-26 at 6 09 50 pm" src="https://cloud.githubusercontent.com/assets/15682607/22355912/34c99124-e3f3-11e6-98d2-282b39415082.png">

**Comment by ewald02100** [comment]
le m aime problème iphone SE n69uap 
![teste](https://cloud.githubusercontent.com/assets/25393938/22395725/57ab9832-e546-11e6-8813-7000d6f1a9a0.png)

**Comment by ewald02100** [comment]
./futurerestore_macos -t xxxxxxxxx_iPhone8,4_n69uap_10.2-14C92.shsh -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n69u.RELEASE.im4p -m BuildManifest.plist -w iPhoneSE_10.2_14C92_Restore.ipsw

**Comment by ewald02100** [comment]
ust pushed futurerestore v89 which should fix the can't find boardconfig error.
warning: untested https://mobile.twitter.com/tihmstar

**Comment by leo98gomez** [comment]
@ewald02100 have you tried it? I didn't wait and went ahead and updated via iTunes

**Comment by ewald02100** [comment]
Slt sa fonctionne avec futurerestore v89

Envoyé de mon iPhone
