### ISSUE TITLE
Unable to enter recovery mode

### ISSUE THREAD

**Issue by Swaggasocks** [tihmstar/futurerestore#264]
device enter in recovery mode but i`m getting -2 error
https://pastecode.xyz/view/723d27db

Ios 10.2.1 IPhone 5s , n53ap   

i tried to put in recovery mode and then start but it says that he dont see device

**Comment by s0uthwest** [comment]
You use iOS 12 sep, but you'll use OTA 10.3.3 sep with BuildManifest.

**Comment by Swaggasocks** [comment]
it also dont work, don`t see device
