### ISSUE TITLE
[Error] argument parsing failed!

### ISSUE THREAD

**Issue by fikretsengul** [tihmstar/futurerestore#27]
Hello, I installed all dependencies but when I try to use this code,

"./futurerestore –t iPhone7,2_10.2-14C92.shsh –b Mav10-5.32.00.Release.bbfw –p BuildManifest.plist –s sep-firmware.n61.RELEASE.im4p –m BuildManifest.plist –w iPhone_4.7_10.2_14C92_Restore.ipsw"

The terminal says,

"Version: 89b019300f31fa1c4482e026befab65d6172f9e4 - 87
[Error] argument parsing failed! agrc=13 optind=1"

What Should I do? Thank you.

**Comment by fikretsengul** [comment]
PS: I use Mac OS.

**Comment by fikretsengul** [comment]
Ok. I fixed it by using specific path of files. Ex code.

"./futurerestore_macos -t /Users/fikretsengul/Desktop/downgrade/iPhone7\,2_10.2-14C92.shsh -b /Users/fikretsengul/Desktop/downgrade/Mav10-5.32.00.Release.bbfw -p /Users/fikretsengul/Desktop/downgrade/BuildManifest.plist -s /Users/fikretsengul/Desktop/downgrade/sep-firmware.n61.RELEASE.im4p -m /Users/fikretsengul/Desktop/downgrade/BuildManifest.plist -w /Users/fikretsengul/Desktop/downgrade/iPhone_4.7_10.2_14C92_Restore.ipsw"

**Comment by ceedveed** [comment]
In case anyone else sees this: the dashes must be short dashes (next to the equal sign). I don't think the specific path fixed the parsing error, but the use of short dashes did.
