### ISSUE TITLE
Puts my device into recovery mode then says "Unable to place device into recovery mode from Normal mode"

### ISSUE THREAD

**Issue by Elronnd** [tihmstar/futurerestore#28]
Like #21, but this is on an iphone 5s.

    $ ../.futurerestore/bin/futurerestore -t /home/elronnd/ios/shsh-i5s/10.2/apnonce-0dc448240696866b0cc1b2ac3eca4ce22af11cb3/7762269402704_iPhone8,1_10.2-14C92.shsh2 -t /home/elronnd/ios/shsh-i5s/10.2/apnonce-352dfad1713834f4f94c5ff3c3e5e99477347b95/7762269402704_iPhone8,1_10.2-14C92.shsh2 -t /home/elronnd/ios/shsh-i5s/10.2/apnonce-42c88f5a7b75bc944c288a7215391dc9c73b6e9f/7762269402704_iPhone8,1_10.2-14C92.shsh2 -t /home/elronnd/ios/shsh-i5s/10.2/apnonce-603be133ff0bdfa0f83f21e74191cf6770ea43bb/7762269402704_iPhone8,1_10.2-14C92.shsh2 -t /home/elronnd/ios/shsh-i5s/10.2/apnonce-9804d99e85bbafd4bb1135a1044773b4df9f1ba3/7762269402704_iPhone8,1_10.2-14C92.shsh2 -b Mav7Mav8-7.21.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n53.RELEASE.im4p -m BuildManifest.plist -w ../Downloads/iPhone_4.0_64bit_10.2_14C92_Restore.ipsw
    Version: 6aa188cd06789de1573263aa301a4242db044ceb - 89
    futurerestore init done
    reading ticket /home/elronnd/ios/shsh-i5s/10.2/apnonce-0dc448240696866b0cc1b2ac3eca4ce22af11cb3/7762269402704_iPhone8,1_10.2-14C92.shsh2 done
    reading ticket /home/elronnd/ios/shsh-i5s/10.2/apnonce-352dfad1713834f4f94c5ff3c3e5e99477347b95/7762269402704_iPhone8,1_10.2-14C92.shsh2 done
    reading ticket /home/elronnd/ios/shsh-i5s/10.2/apnonce-42c88f5a7b75bc944c288a7215391dc9c73b6e9f/7762269402704_iPhone8,1_10.2-14C92.shsh2 done
    reading ticket /home/elronnd/ios/shsh-i5s/10.2/apnonce-603be133ff0bdfa0f83f21e74191cf6770ea43bb/7762269402704_iPhone8,1_10.2-14C92.shsh2 done
    reading ticket /home/elronnd/ios/shsh-i5s/10.2/apnonce-9804d99e85bbafd4bb1135a1044773b4df9f1ba3/7762269402704_iPhone8,1_10.2-14C92.shsh2 done
    [TSSC] opening BuildManifest.plist
    WARNING: Unable to find BbSkeyId node
    [TSSR] User specified not to request a Baseband ticket.
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    Did set sep+baseband path and firmware
    [TSSC] opening BuildManifest.plist
    WARNING: Unable to find BbSkeyId node
    [TSSR] User specified to request only a Baseband ticket.
    ERROR: Unable to get BasebandFirmware node
    ERROR: Unable to find required BbGoldCertId in parameters
    Request URL set to https://gs.apple.com/TSS/controller?action=2
    Sending TSS request attempt 1... response successfully received
    Found device in Normal mode
    Entering recovery mode...
    ERROR: Unable to connect to device in recovery mode
    ERROR: Unable to enter recovery mode
    [Error] Unable to place device into recovery mode from Normal mode
    [Error] Fail code=-2
    Failed with errorcode=-2

**Comment by Elronnd** [comment]
I had to run it as root, it works now.

**Comment by TheWhiteEvil502** [comment]
how can i run it as root?
