### ISSUE TITLE
ERROR: Unable to receive message from FDR 0x7f97d5996ba0 (-2). 0/2 bytes

### ISSUE THREAD

**Issue by TheDarrenn** [tihmstar/futurerestore#288]
Kindly help been stuck with this problem after using futurerestore to update my iPhone XS Max from 12.1.2 to 12.4.

Version: 81b98e0425e17250cc83d5badaf9a8cc6399f481 - 245
Libipatcher version: 3159a387584e352f690cca859e013c3a4683f3e8 - 69
Odysseus support: yes
[INFO] 64-bit device detected
futurerestore init done
reading signing ticket /Volumes/Darren Mac OS/FR/12.4/5639618503376954_iPhone11,6_d331pap_12.4-16G77_b62ed018ba1d2c13956194b61c3d0db15bfdbe4f2c01e94d86f43f5b61bb1552.shsh2 is done
Found device iPhone11,6 d331pap
[TSSC] opening /Volumes/Darren Mac OS/FR/BuildManifest.plist
[TSSR] User specified not to request a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set SEP+baseband path and firmware
[TSSC] opening /Volumes/Darren Mac OS/FR/BuildManifest.plist
[TSSR] User specified to request only a baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is G6TX9HSYKPH5
Found device in Recovery mode
Identified device as d331pap, iPhone11,6
Extracting BuildManifest from iPSW
Product version: 12.4
Product build: 16G77 Major: 16
Device supports IMG4: true
Got ApNonce from device: b6 2e d0 18 ba 1d 2c 13 95 61 94 b6 1c 3d 0d b1 5b fd be 4f 2c 01 e9 4d 86 f4 3f 5b 61 bb 15 52 
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from iPSW
[==================================================] 100.0%
Extracting iBEC.d331p.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (1063761 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... af 4f 57 5d a7 67 a9 c0 68 14 b0 ea 69 5c 83 ca 54 f2 9c e1 
Getting ApNonce in recovery mode... b6 2e d0 18 ba 1d 2c 13 95 61 94 b6 1c 3d 0d b1 5b fd be 4f 2c 01 e9 4d 86 f4 3f 5b 61 bb 15 52 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4513.270.14
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2688~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (26721 bytes)...
Extracting h11_ane_fw_quin.im4p...
Personalizing IMG4 component ANE...
Sending ANE (9394569 bytes)...
Extracting aopfw-iphone11aop.im4p...
Personalizing IMG4 component AOP...
Sending AOP (1396097 bytes)...
Extracting AppleAVE2FW.im4p...
Personalizing IMG4 component AVE...
Sending AVE (1111233 bytes)...
Extracting armfw_g11p.im4p...
Personalizing IMG4 component GFX...
Sending GFX (1555697 bytes)...
Extracting adc-petra-d3x.im4p...
Personalizing IMG4 component ISP...
Sending ISP (14639185 bytes)...
Extracting 048-76361-092.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (11402 bytes)...
Extracting SmartIOFirmwareT8020.im4p...
Personalizing IMG4 component SIO...
Sending SIO (1355957 bytes)...
Extracting WirelessPower.iphone11.im4p...
Personalizing IMG4 component WCHFirmwareUpdater...
Sending WCHFirmwareUpdater (28636 bytes)...
ramdisk-size=0x20000000
Extracting 048-76361-092.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (91691396 bytes)...
Extracting DeviceTree.d331pap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (193674 bytes)...
Extracting kernelcache.release.iphone11...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (17959141 bytes)...
Trying to fetch new signing tickets
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received signing tickets
About to restore device... 
Waiting for device...
Device 00008020-001409340190003A is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device 00008020-001409340190003A has successfully entered restore mode
Hardware Information:
BoardID: 26
ChipID: 32800
UniqueChipID: 5639618503376954
ProductionMode: true
Starting FDR listener thread
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating S3E Firmware (58)
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d331p.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@2688~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@2688~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@2688~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@2688~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d331pap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting lowpowermode@2688~iphone-lightning.im4p...
Personalizing IMG4 component LowPowerWallet0...
Extracting recoverymode@2688~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d331p.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
ERROR: Unable to receive message from FDR 0x7f97d5996ba0 (-2). 0/2 bytes

**Comment by saury** [comment]
I met the same issue and fixed it.
Try reseting your device and make sure no apple id sign in.
