### ISSUE TITLE
ERROR: Device is in an invalid state

### ISSUE THREAD

**Issue by maxduke** [tihmstar/futurerestore#29]
I was trying to restore my iPhone 5S  to 10.2 from 9.3.3 and I was using NonceEnabler.
I've tried manually enter the recovery mode by setting auto-boot and reboot or automatically by futurerestore.
No matter which method I used when it gets into the recovery mode it will stuck at sending iBEC.
following is the log"

> ./futurerestore_macos -t dummy_iPhone6,2_10.2-14C92.shsh2 -b Mav7Mav8-7.21.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n53.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.0_64bit_10.2_14C92_Restore.ipsw

```
Version: 6aa188cd06789de1573263aa301a4242db044ceb - 89
futurerestore init done
reading ticket dummy_iPhone6,2_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is dummy SN
waiting for nonce: dummy match
Got ApNonce from device: dummy match
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n53ap, iPhone6,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_4.0_64bit_10.2_14C92_Restore/058-54548-094.dmg'
Extracting iBEC.n53.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (627863 bytes)...
Getting SepNonce failed
ERROR: Device is in an invalid state
Getting ApNonce failed
ERROR: Device is in an invalid state
ERROR: Device is in an invalid state
Segmentation fault: 11
```

**Comment by maxduke** [comment]
found someone is facing the same issue 
https://www.reddit.com/r/jailbreak/comments/5pu8x4/tutorial_how_to_upgradedowngrade_to_ios_102_using/dd4zigf/

when "Sending iBEC (627863 bytes)..." is displayed, the screen turns to black from iTunes restore screen

**Comment by Scunkaneli** [comment]
Having exact the same issue. I'm trying to go from 9.3.3 -> 10.2 on iPad4,4 (WIFI only) via NonceEnabler. Device throws the same error messages, but I was able to get it out of recovery mode (with black screen) by setting the auto-boot flag to true. 

Additional Information: I was restoring without baseband and I tried the program using the latest version of macOS and ofc futurerestore in a *Virtual Machine*! May this be the issue?

**Comment by maxduke** [comment]
I don't think so. I'm facing this issue in the real machine with the latest macos version.

**Comment by DrD00der** [comment]
I'm having this same error.  hoping someone has some insight!

**Comment by conath** [comment]
I am also trying to restore from 9.3.3 to 10.2 using valid .shsh2 blobs and facing the very same issue of invalid state (using nonceenabler). Terminal output is here: http://pastebin.com/26VTGXrc

**Comment by tihmstar** [comment]
If you're using a Virtual Machine one issue could be that when the device reboots it reconnects as a different USB device. Maybe that USB device isn't properly forwarded to the VM and that's why it doesn't find it.

**Comment by conath** [comment]
I'm using an actual Mac Mini on the latest macOS Sierra. Killed iTunesHelper (to prevent iTunes launch) and connected iPhone 5S to USB port on the mac using a brand new Apple cable. Used Luca's jbme and then patched the boot nonce using 
    nvram com.apple.System.boot-nonce=0xeec3ad42b38b6df7
Finally I execute the command
    ./futurerestore_macos -t 6279397345616_iPhone6,2_10.2-14C92.shsh2 -b Mav7Mav8-7.21.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n53.RELEASE.im4p -m BuildManifest.plist iPhone_4.0_64bit_10.2_14C92_Restore.ipsw
The iPhone's screen turns **black** while the Terminal states "Sending iBEC (627863 bytes)..." and then after a few seconds it prints:
    Getting SepNonce failed
    ERROR: Device is in an invalid state
    Getting ApNonce failed
    ERROR: Device is in an invalid state
    ERROR: Device is in an invalid state
    Segmentation fault: 11

**Comment by maxduke** [comment]
Exactly the same phenomenon as conath described on a MBP with latest version of Sierra.

**Comment by DrD00der** [comment]
I screwed the pooch big time.  I tried some random things to fix this and ended up in a bootloop.  Instead of using Reiboot to get out of it (which I didn't know about until now) I restored to 10.2.1.  I tried running futurerestore from 10.2.1 but it ran for 8 hours without finding the right generator/nonce.  Gonna try again tonight for another 8 hours and see if I get lucky and am able to downgrade.

**Comment by KoetseJ** [comment]
I ran into the same issue, I did mange to solve it for myself. 

What I did was:
(Re)Enable Code Lock
(Re)Enable Find My iPhone
Disable Find My iPhone
Sign out of iCloud
Disable Code Lock

It almost looks like something did not properly update.

**Comment by conath** [comment]
@KoetseJ I tried this but ended up with exactly the same error. I also tried putting in a SIM card into the iPhone but that didn't help.

**Comment by tihmstar** [comment]
Can you check whether the issue is still in the latestversion?
The commit b35d3e1245da49950028d753b1bdb40fce5d21d5 is supposed to fixed this

**Comment by maxduke** [comment]
@tihmstar You made it! Just compiled the latest version of futurerestore. Now my 5s is on iOS 10.2.
Thanks!

**Comment by conath** [comment]
Thanks for the fix tihmstar, unfortunately I can't figure out how to compile futurerestore properly. When running autogen.sh I get: *Requested 'libimobiledevice-1.0 >= 1.2.1' but version of libimobiledevice is 1.2.0*

**Comment by maxduke** [comment]
@conath I removed the libimobiledevice v1.2.0 in homebrew and compiled libimobiledevice from the source https://github.com/libimobiledevice bymyself.

**Comment by conath** [comment]
@maxduke Trying that and now facing an issue while compiling libimobiledevice: 

    Making all in src
      CCLD     libimobiledevice.la
    Undefined symbols for architecture x86_64:

**Comment by maxduke** [comment]
@tihmstar try
`CFLAGS=-I/usr/local/opt/openssl/include LDFLAGS=-L/usr/local/opt/openssl/lib ./autogen.sh`
before make

**Comment by conath** [comment]
@maxduke That didn't help unfortunately.

**Comment by Scunkaneli** [comment]
@maxduke Atm, I'm also not able to compile the fix myself. 
Am I right, you have been able to compile futurerestore and the new version fixed your issue?
If so, are you allowed to share your compiled file with us or is this forbidden?

Thank you :)

**Comment by maxduke** [comment]
@Scunkaneli @conath 
You can try the binary file which I compiled.
https://dl.dropboxusercontent.com/u/2224832/futurerestore_v90
I cannot guarantee that my binary file will work on your machine since I compiled that with dynamic link library.

**Comment by conath** [comment]
@maxduke Yep that's not working because the libimobiledevice.6.dylib is missing >.< Thanks anyways!

**Comment by maxduke** [comment]
@conath I tried to recompile that with "--enable-static" but no luck. I think @tihmstar will release the V90 binary soon, just be patient. :)

**Comment by Scunkaneli** [comment]
Can confirm, also getting the error conath reported. Thank you anyway! :)

I guess I can wait a little longer for v90, so that shouldn't be a problem.

**Comment by rennersantana** [comment]
The same problem here does anyone know how to solve? it gets black and can not return to recovery mode.

checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
Extracting iBEC.d10.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (439094 bytes)...
waiting for device to reconnect... ........................................
Getting SepNonce failed
ERROR: Device is in an invalid state
Getting ApNonce failed
ERROR: Device is in an invalid state
ERROR: Device is in an invalid state
