### ISSUE TITLE
downgrade iPhoneX failed

### ISSUE THREAD

**Issue by fr3ns1s** [tihmstar/futurerestore#290]
Version: 265c1bbca07b924f2f03a315983f7d23094cca35 - 171
Odysseus Support: no
INFO: device serial number is xxxxxxx
[INFO] 64bit device detected
futurerestore init done
reading ticket 12_4.shsh2 done
user specified to use latest signed sep
[TSSC] opening firmware.json
[DOWN] downloading file https://api.ipsw.me/v2.1/firmwares.json/condensed
[TSSC] selecting latest iOS: 13.2
[TSSC] got firmwareurl for iOS 13.2 build 17B84
100 [===================================================================================================>]
downloading SEP
100 [===================================================================================================>]
[TSSC] opening /tmp/futurerestore/sepManifest.plist
[TSSR] User specified doesn't to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
user specified to use latest signed baseband (WARNING, THIS CAN CAUSE A NON-WORKING RESTORE)
downloading Baseband
100 [===================================================================================================>]
ERROR: Unable to connect to device?!
ERROR: Unable to get FirmwarePreflightInfo
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /tmp/futurerestore/basebandManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as d221ap, iPhone10,6
Extracting BuildManifest from IPSW
Product Version: 12.4
Product Build: 16G77 Major: 16
Device supports Image4: true
Got APNonce from device: 27 32 5c 82 58 be 46 e6 9d.........
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
P?
  X?
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (found "aopf" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "AudioCodecFirmware"      OK (found "acfw" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "Multitouch"              OK (found "mtfw" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SE,UpdatePayload"        IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "Savage,B0-Dev-Patch"     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B0-Dev-PatchVT"   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B0-Prod-Patch"    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B0-Prod-PatchVT"  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B2-Dev-Patch"     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B2-Dev-PatchVT"   BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B2-Prod-Patch"    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,B2-Prod-PatchVT"  BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,BA-Dev-Patch"     BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "Savage,BA-Prod-Patch"    BAD! (hash not found in im4m)
[IMG4TOOL] checking hash for "StaticTrustCache"        OK (found "trst" with matching hash)
[IMG4TOOL] checking hash for "ftap"                    IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "ftsp"                    IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
[IMG4TOOL] checking hash for "rfta"                    IGN (ignoring due to whitelist)
[IMG4TOOL] checking hash for "rfts"                    IGN (ignoring due to whitelist)
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone10,3,iPhone10,6_12.4_16G77_Restore/048-77461-092.dmg'
Extracting iBEC.d22.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (988280 bytes)...
waiting for device to reconnect... Getting SepNonce in recovery mode... 9b 69 f3....
Getting ApNonce in recovery mode... 27 32 5c 82 58 be 46 e6 9d .....
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4513.270.14
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (19932 bytes)...
ramdisk-size=0x20000000
Extracting 048-78047-092.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (91609659 bytes)...
Extracting 048-78047-092.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (10561 bytes)...
Extracting DeviceTree.d221ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (181249 bytes)...
Extracting kernelcache.release.iphone10b...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (17855777 bytes)...
getting sep ticket
Trying to fetch new SHSH blob
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000092 has successfully entered restore mode
Hardware Information:
BoardID: 14
ChipID: 32789
UniqueChipID: 395549.......
ProductionMode: true
Starting FDR listener thread
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating NAND Firmware (58)
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d22.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@2436~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d221ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@2436~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting recoverymode@2436~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d22.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
Checking filesystems (15)
ERROR: Unable to receive message from FDR 0x7feb58330730 (-4). 0/2 bytes
ERROR: Could not read data (-256). Aborting.
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=70058001
line=1069
file=futurerestore.cpp
commit count=26:
commit sha  =4c96389db50eeb7411f6e4c62eb073ef401ca6bd:
Done: restoring failed!

**Comment by s0uthwest** [comment]
SEP is incompatible.
