### ISSUE TITLE
when downgrade with 13.3 to 12.1.3 ,get error:ERROR: Unable to receive message from FDR 0x7fae25851560 (-2). 0/2 bytes

### ISSUE THREAD

**Issue by xyx208** [tihmstar/futurerestore#297]
when i do 13.3 ->12.1.3 with my iphone7 plus it seem not ok.

System :MacOS 10.15.2
Model:iphone7 plus(iphone9,2)
IOS Version:13.3
target IOS Version:12.1.3
log:
> 
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
checking APTicket to be valid for this restore...
Verified ECID in APTicket matches device ECID
[IMG4TOOL] checking buildidentity 0:
[IMG4TOOL] checking buildidentity matches board ... NO
[IMG4TOOL] checking buildidentity 1:
[IMG4TOOL] checking buildidentity matches board ... YES
[IMG4TOOL] checking buildidentity has all required hashes:
[IMG4TOOL] checking hash for "AOP"                     OK (found "aopf" with matching hash)
[IMG4TOOL] checking hash for "AppleLogo"               OK (found "logo" with matching hash)
[IMG4TOOL] checking hash for "BasebandFirmware"        IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "BatteryCharging0"        OK (found "chg0" with matching hash)
[IMG4TOOL] checking hash for "BatteryCharging1"        OK (found "chg1" with matching hash)
[IMG4TOOL] checking hash for "BatteryFull"             OK (found "batF" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow0"             OK (found "bat0" with matching hash)
[IMG4TOOL] checking hash for "BatteryLow1"             OK (found "bat1" with matching hash)
[IMG4TOOL] checking hash for "BatteryPlugin"           OK (found "glyP" with matching hash)
[IMG4TOOL] checking hash for "DeviceTree"              OK (found "dtre" with matching hash)
[IMG4TOOL] checking hash for "Homer"                   OK (found "homr" with matching hash)
[IMG4TOOL] checking hash for "KernelCache"             OK (found "krnl" with matching hash)
[IMG4TOOL] checking hash for "LLB"                     OK (found "illb" with matching hash)
[IMG4TOOL] checking hash for "Liquid"                  OK (found "liqd" with matching hash)
[IMG4TOOL] checking hash for "OS"                      OK (found "rosi" with matching hash)
[IMG4TOOL] checking hash for "RecoveryMode"            OK (found "recm" with matching hash)
[IMG4TOOL] checking hash for "RestoreDeviceTree"       OK (found "rdtr" with matching hash)
[IMG4TOOL] checking hash for "RestoreKernelCache"      OK (found "rkrn" with matching hash)
[IMG4TOOL] checking hash for "RestoreLogo"             OK (found "rlgo" with matching hash)
[IMG4TOOL] checking hash for "RestoreRamDisk"          OK (found "rdsk" with matching hash)
[IMG4TOOL] checking hash for "RestoreSEP"              OK (found "rsep" with matching hash)
[IMG4TOOL] checking hash for "RestoreTrustCache"       OK (found "rtsc" with matching hash)
[IMG4TOOL] checking hash for "SE,Bootloader"           IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,Firmware"             IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,MigrationOS"          IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SE,OS"                   IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "SEP"                     OK (found "sepi" with matching hash)
[IMG4TOOL] checking hash for "StaticTrustCache"        OK (found "trst" with matching hash)
[IMG4TOOL] checking hash for "ftap"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "ftsp"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "iBEC"                    OK (found "ibec" with matching hash)
[IMG4TOOL] checking hash for "iBSS"                    OK (found "ibss" with matching hash)
[IMG4TOOL] checking hash for "iBoot"                   OK (found "ibot" with matching hash)
[IMG4TOOL] checking hash for "rfta"                    IGN (no digest in BuildManifest)
[IMG4TOOL] checking hash for "rfts"                    IGN (no digest in BuildManifest)
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from iPSW
[==================================================] 100.0%
Extracting iBEC.d11.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (457160 bytes)...
waiting for device to reconnect... Getting SepNonce in recovery mode... 13 5f a9 39 ea 15 fb 96 f4 70 e6 60 40 05 aa 4f 31 29 a5 4f 
Getting ApNonce in recovery mode... 73 9c 3d e0 3a 97 8d 17 3d 0d 48 c5 b8 f9 d5 cf fd 92 86 46 b5 cc e0 d1 c9 f4 41 8c 86 74 03 d3 
[WARNING] Setting bgcolor to green! If you don't see a green screen, then your device didn't boot iBEC correctly
Recovery Mode Environment:
iBoot build-version=iBoot-4513.230.10
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (19814 bytes)...
ramdisk-size=0x20000000
Extracting 048-48002-039.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (106784709 bytes)...
Extracting 048-48002-039.dmg.trustcache...
Personalizing IMG4 component RestoreTrustCache...
Sending RestoreTrustCache (10443 bytes)...
Extracting DeviceTree.d11ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (153107 bytes)...
Extracting kernelcache.release.iphone9...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (16734969 bytes)...
getting SEP ticket
Trying to fetch new SHSH blob
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Connecting now...
Connected to com.apple.mobile.restored, version 15
Device ffffffffffffffffffffffffffffffff00000010 has successfully entered restore mode
Hardware Information:
BoardID: 10
ChipID: 32784
UniqueChipID: 2626622417554726
ProductionMode: true
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest from build identity
Extracting LLB.d11.RELEASE.im4p...
Personalizing IMG4 component LLB...
Extracting applelogo@3x~iphone.im4p...
Personalizing IMG4 component AppleLogo...
Extracting batterycharging0@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging0...
Extracting batterycharging1@3x~iphone.im4p...
Personalizing IMG4 component BatteryCharging1...
Extracting batteryfull@3x~iphone.im4p...
Personalizing IMG4 component BatteryFull...
Extracting batterylow0@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow0...
Extracting batterylow1@3x~iphone.im4p...
Personalizing IMG4 component BatteryLow1...
Extracting glyphplugin@1920~iphone-lightning.im4p...
Personalizing IMG4 component BatteryPlugin...
Extracting DeviceTree.d11ap.im4p...
Personalizing IMG4 component DeviceTree...
Extracting liquiddetect@1920~iphone-lightning.im4p...
Personalizing IMG4 component Liquid...
Extracting recoverymode@1920~iphone-lightning.im4p...
Personalizing IMG4 component RecoveryMode...
Extracting iBoot.d11.RELEASE.im4p...
Personalizing IMG4 component iBoot...
Personalizing IMG4 component RestoreSEP...
Personalizing IMG4 component SEP...
Sending NORData now...
Done sending NORData
About to send RootTicket...
Sending RootTicket now...
Done sending RootTicket
Waiting for NAND (28)
Updating NAND Firmware (58)
Checking filesystems (15)
Checking filesystems (15)
About to send FDR Trust data...
Sending FDR Trust data now...
Done sending FDR Trust Data
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Unmounting filesystems (29)
Creating partition map (11)
Creating filesystem (12)
ERROR: Unable to receive message from FDR 0x7fae25851560 (-2). 0/2 bytes
ERROR: Could not read data (-256). Aborting.
Cleaning up...
[exception]:
what=ERROR: Unable to restore device

code=67895313
line=1036
file=futurerestore.cpp
commit count=29:
commit sha  =2994651a10d8176a298b31e7706b4b6af97975d1:
Done: restoring failed!

>

**Comment by s0uthwest** [comment]
SEP is uncompatible.

**Comment by xyx208** [comment]
> SEP

what should i do ?Please help me.

**Comment by s0uthwest** [comment]
Nothing. You can't downgrade.

**Comment by xyx208** [comment]
> Nothing. You can't downgrade.

No.......
