### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by alukarulz** [tihmstar/futurerestore#3]
[TSSC] opening Mav10-5.32.00.Release.bbfw
Entity: line 1: parser error : Start tag expected, '<' not found
PK
^
[Error] [TSSR] ERROR: device wasn't specified and could not be fetched from BuildManifest
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,2
Segmentation fault: 11

**Comment by IntricateD** [comment]
./futurerestore_osx -t iPhone9,2_10.1.1-14B150.shsh2 -b Mav16-1.33.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.d11.RELEASE.im4p -m BuildManifest.plist -w iPhone_7Plus_10.1.1_14B150_Restore.ipsw
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone9,2
Segmentation fault: 11

**Comment by anykernelpanic** [comment]
Can verify that this has been fixed in the latest build, I got it from [here](https://www.reddit.com/r/jailbreak/comments/5kwddt/release_future_restore_os_xprometheus_compiled/).

**Comment by spockers** [comment]
No, but now I get a different error ;( 

Tims-MacBook-Pro:futurerestore spockers$ ./futurerestore_macos -t 7656463012912_iPhone6,1_10.1.1-14B150.shsh2 -b sep-firmware.n51.RELEASE.im4p -p BuildManifest.plist -s sep-firmware.n51.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.0_64bit_10.1.1_14B150_Restore.ipsw 
dyld: Library not loaded: /opt/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /Volumes/Stuff//futurerestore/./futurerestore_macos
  Reason: image not found
Trace/BPT trap: 5

**Comment by alukarulz** [comment]
That was easy to fix. 
Asumming you have homebrew installed.
Go to terminal and type "brew install openssl"
Then head to /user/local/ and search for libcrypto.1.0.0.dylib.
Copy that and paste it into /opt/local/lib/ 
If you can't find that directory then make it.

**Comment by spockers** [comment]
Thanks, that did the trick.

**Comment by alukarulz** [comment]
Closing error has been fixed by update.

**Comment by adi2k17** [comment]
Help me please I don't have that diractory

**Comment by Conoize** [comment]
I am having trouble getting that directory too... here's what I got

 ./futurerestore_osx -t 2296988119901222_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1
Segmentation fault: 11

**Comment by faisalkhan313** [comment]
No, but now I get a different error ;(

Tims-MacBook-Pro:futurerestore spockers$ ./futurerestore_macos -t 7656463012912_iPhone8,2_10.2.-.shsh2 -b sep-firmware.n51.RELEASE.im4p -p BuildManifest.plist -s sep-firmware.n51.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.0_64bit_10.2_Restore.ipsw
dyld: Library not loaded: /usr/local/lib/libzip.dylib
Reason: image not found
Trace/BPT trap: 5

**Comment by msh2050** [comment]
this may be caused by error in  Bundles.
I get same this error with ipws tool(because of bad Bundle)
