### ISSUE TITLE
[Error] argument parsing failed! agrc=13 optind=1

### ISSUE THREAD

**Issue by TechnicLab** [tihmstar/futurerestore#30]
Hello!
./futurerestore_macos –t iPhone6,2_9.3.3-13G34.shsh –b Mav7Mav8-6.02.00.Release.bbfw –p BuildManifest.plist –s sep-firmware.n53.RELEASE.im4p –m BuildManifest.plist –w iPhone6,2_9.3.3_13G34_Restore.ipsw
returns this error:
Version: 6aa188cd06789de1573263aa301a4242db044ceb - 89
[Error] argument parsing failed! agrc=13 optind=1

**Comment by alanci2003** [comment]
i have some problem here. and I can't solve it by using specific path method which provided by @fikretsengul.

**Comment by fikretsengul** [comment]
Oh but firstly, let me warn you about my fuckin' bad english. However, I
can try to help you. Just inform me when you are available. I can check it
by TeamWiever. I hope we can fix it.


[image: logo]
*Fikret Şengül* *Software Engineer Student**, (Bilkent University)*
zer0-day@fikretsengul.com | www.fikretsengul.com
<http://facebook.com/fikretsengui>  <http://twitter.com/fikretsengui>
<http://instagram.com/fikretsengui>  <http://snapchat.com/add/fikretsengul>
<http://us.linkedin.com/in/fikretsengul>  <http://github.com/fikretsengul>

2017-01-31 19:41 GMT+03:00 alanci2003 <notifications@github.com>:

**Comment by TechnicLab** [comment]
We can communicate via Jabber(Jitsi, Adium, etc).

**Comment by TechnicLab** [comment]
Ok, skype is an option. Already sended my skype name to your email.

**Comment by fikretsengul** [comment]
​Where was it ? I couldn't find, can you send it again ?​


[image: logo]
*Fikret Şengül* *Software Engineer Student**, (Bilkent University)*
zer0-day@fikretsengul.com | www.fikretsengul.com
<http://facebook.com/fikretsengui>  <http://twitter.com/fikretsengui>
<http://instagram.com/fikretsengui>  <http://snapchat.com/add/fikretsengul>
<http://us.linkedin.com/in/fikretsengul>  <http://github.com/fikretsengul>

2017-02-01 22:16 GMT+03:00 TechnicLab <notifications@github.com>:

**Comment by phhai1710** [comment]
please help me, i get this error too. My skype : phhai1710@ gmail.com .

**Comment by tihmstar** [comment]
This is likely related to my buildsystem, have you tried building from source?
Or does the problem still exist in version 95? (i changed my buildsystem)

**Comment by tof205** [comment]
still the same
i also get a malloc error it doesn't matter the version if i compile i get the malloc.
i tried in a vm but pretty sure i'll get the same if i boot on my linux
tofs-Mac:down tof$ ./futurerestore –t _iPhone6,2_10.2-14C92.shsh2 –b Mav7Mav8-7.21.00.Release.bbfw –p BuildManifest.plist –s sep-firmware.n53.RELEASE.im4p –m BuildManifest.plist –w iPhone_4.0_64bit_10.2_14C92_Restore.ipsw
Version: 9fcf613f8fe68b15be7fd19c267e7351523eb387 - 95
[Error] argument parsing failed! agrc=13 optind=1
futurerestore(533,0x7fffaaf003c0) malloc: *** error for object 0x7fe283d00950: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

**Comment by tihmstar** [comment]
same as #48
