### ISSUE TITLE
lib crypto error

### ISSUE THREAD

**Issue by RealIronDev** [tihmstar/futurerestore#31]
Hi, I keep getting this error on futurerestore:

dyld: Library not loaded: /opt/local/lib/libcrypto.1.0.0.dylib
  Referenced from: /Users/*******/Desktop/downgrade/./futurerestore_macos
  Reason: image not found
Abort trap: 6

**Comment by maxduke** [comment]
if you are able to find /usr/local/Cellar/openssl/1.0.2j/lib/libcrypto.1.0.0.dylib, then you can link that by using 
`ln -s /usr/local/Cellar/openssl/1.0.2j/lib/libcrypto.1.0.0.dylib /opt/local/lib/libcrypto.1.0.0.dylib`

**Comment by latinti81** [comment]
I have the same issue !  pls Help 

./futurerestore –t 4016551287718438_iPad5,1_j96ap_10.2-14C92.shsh2 –b Mav7Mav8-7.21.00.Release.bbfw –pBuildManifest.plist –s sep-firmware.j81.RELEASE.im4p –m BuildManifest.plist –w iPad_64bit_TouchID_10.2_14C92_Restore.ipsw -w
Found device in Recovery mode
Device already in Recovery mode
[Error] No IM4M loaded
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6

**Comment by tickietackie** [comment]
try this
http://www.ipodhacks142.com/how-to-fix-prometheus-futurerestore-errors-and-frequently-asked-questions/

**Comment by dev135** [comment]
Delete the -w at the end

**Comment by latinti81** [comment]
My iPad has been looking for a collision past 3  days... when is it the right time to give up ?

**Comment by dev135** [comment]
What iPad

**Comment by dev135** [comment]
Nvm ctrl + c it probably won't work with those blobs

**Comment by latinti81** [comment]
That's iPad mini 4 .

**Comment by tihmstar** [comment]
This problem was related to my buildsystem and shouldn't exist when building from source yourself.
Also i updated my buildsystem so this should be fixed my now
