### ISSUE TITLE
Ipad4,8 iPad Mini 3 (Cellular) isn't documented

### ISSUE THREAD

**Issue by SjGuk** [tihmstar/futurerestore#32]
i get ERROR: device "iPad4,8" is not in bbgcid.json, Which means it's BasebandGoldCertID isn't documented yet, is there any chance to support this device, thanks for your help

I Believe the id is 3554301762 (retrieved from redsnow)

**Comment by tihmstar** [comment]
Thanks.
added this in tihmstar/tsschecker@2659743560d512ad9be41d91e5ca38ce0aebe75d
