### ISSUE TITLE
iPhone 6 restore_is_current_device: device 7d800d4f674fef7ef586b48f5d2103b8718f8ad5 is not in restore mode error when restoring 

### ISSUE THREAD

**Issue by dev135** [tihmstar/futurerestore#33]
Last login: Tue Jan 31 17:19:26 on ttys001
Hacks-MacBook-Pro:~ hackme$ /Users/hackme/Desktop/downgrade/futurerestore -t /Users/hackme/Desktop/downgrade/3614582318028886_iPhone7\,2_10.2-14C92.shsh2 -b /Users/hackme/Desktop/downgrade/Mav13-2.41.00.Release.bbfw -p /Users/hackme/Desktop/downgrade/BuildManifest.plist -s /Users/hackme/Desktop/downgrade/sep-firmware.n61.RELEASE.im4p -m /Users/hackme/Desktop/downgrade/BuildManifest.plist -w /Users/hackme/Desktop/downgrade/iPhone_4.7_10.2.ipsw 
Version: 89b019300f31fa1c4482e026befab65d6172f9e4 - 87
futurerestore init done
reading ticket /Users/hackme/Desktop/downgrade/3614582318028886_iPhone7,2_10.2-14C92.shsh2 done
[TSSC] opening /Users/hackme/Desktop/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware

[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /Users/hackme/Desktop/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is your face
waiting for nonce: e6 a4 88 c5 f1 a9 77 16 d3 4c f6 2c 39 6a de 4f 87 c2 e2 e2 
Got ApNonce from device: e6 a4 88 c5 f1 a9 77 16 d3 4c f6 2c 39 6a de 4f 87 c2 e2 e2 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from '/Users/hackme/Desktop/downgrade/iPhone_4.7_10.2/058-54986-095.dmg'
Extracting iBEC.n61.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (632436 bytes)...
Getting SepNonce in recovery mode... c4 76 74 06 14 3f e8 c2 92 1f 94 41 28 ce e5 bc fb 49 3e ad 
Getting ApNonce in recovery mode... e6 a4 88 c5 f1 a9 77 16 d3 4c f6 2c 39 6a de 4f 87 c2 e2 e2 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.30.8
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.t7000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12116 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330739 bytes)...
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (123929 bytes)...
Extracting kernelcache.release.n61...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12368816 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
restore_is_current_device: device 7d800d4f674fef7ef586b48f5d2103b8718f8ad5 is not in restore mode
restore_is_current_device: device 8e4d5a0a50b5436d2a65b7eb7d08f2a644a93d67 is not in restore mode
restore_is_current_device: device 8e4d5a0a50b5436d2a65b7eb7d08f2a644a93d67 is not in restore mode
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by tihmstar** [comment]
Did your iPhone show iTunes logo when you got the error?
Did you see the green screen flashing?
Did it reboot?

Can you tried to describe what happened to the phone during the procedure?

**Comment by dev135** [comment]
It got stuck in recovery no green screen or reboot

**Comment by dev135** [comment]
The phone I was using was my testing phone

**Comment by tihmstar** [comment]
I attemted to fix this in b35d3e1245da49950028d753b1bdb40fce5d21d5
Can you please check, whether the issue still exists?

**Comment by dev135** [comment]
Thanks for fixing

**Comment by TChenGH** [comment]
how to use this？

**Comment by brymonster** [comment]
im having the same issue. but i dont know how to use the branch supplied. how do i compile into `futurerestore_macos` executable?
>About to restore device... 
Waiting for device...
restore_is_current_device: device 075941b2bdaf70aa731d42b1e5e2f1121167c29a is not in restore mode
restore_is_current_device: device 075941b2bdaf70aa731d42b1e5e2f1121167c29a is not in restore mode
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by brymonster** [comment]
@dev135 anyway i could get a compiled version of this branch? i have the exact same issue u had..

**Comment by brymonster** [comment]
i am sOO close! can anyone help?!
[newest ERROR11.txt](https://github.com/tihmstar/futurerestore/files/853853/newest.ERROR11.txt)

**Comment by ABABREPO** [comment]
iPad AIR 2 iOS 9.0.2 JB futurerestore He's stuck with the Apple logo
Hey, I've been working Futururestore upgrade from iOS 9.0.2 to iOS 11.3.1
and iPad stuck with the Apple logo,
stuck with the Apple logo. I put the Ipad in Recover And I did it again futurerestore

./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw

/Desktop/futurerestoregood
daniel-macbook-air:futurerestoregood danielpalicka$ ./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw
Version: a0113a4 - 173
Odysseus Support: no
INFO: device serial number is DMPQ524UG5YL
[INFO] 64bit device detected
futurerestore init done
reading ticket blobs.shsh2 done
Found device iPad5,4 j82ap
[TSSC] opening BuildManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as j82ap, iPad5,4
Extracting BuildManifest from IPSW
Product Version: 11.3.1
Product Build: 15E302 Major: 15
Device supports Image4: true
Got APNonce from device: 38 a2 a7 d5 6c 34 71 a7 5a 31 ff 8c 8c 4c 32 bc b4 b8 ea 5c
[Error] Devicenonce does not match APTicket nonce
[Error] maybe you forgot -w ?
Done: restoring failed.
Failed with errorcode=-20

Pleas Help me
I don't want to go to iOS 11.4.1
Thank you very much

**Comment by brymonster** [comment]
Sorry man. I got rid of my iPad Air. 
Maybe you need to use the -w (wait) like the error suggests. Or your blobs are not valid.

**Comment by ABABREPO** [comment]
- W isn't working. I'm stuck at the logo aool and nothing. I don't want to go to the ios 11.4.1

./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist -w iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw

egood 
daniel-macbook-air:futurerestoregood danielpalicka$ ./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist -w iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
INFO: device serial number is DMPQ524UG5YL
[INFO] 64bit device detected
futurerestore init done
reading ticket blobs.shsh2 done
Found device iPad5,4 j82ap
[TSSC] opening BuildManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
waiting for nonce: 35 b6 8f 41 ac 47 97 28 90 a0 54 2d 80 12 4c ce 48 86 64 36 
Got ApNonce from device: ee b3 5e 25 07 e0 70 65 bf 56 11 64 b7 ca f8 d2 d1 cf 5b de 
Got ApNonce from device: bd b3 4c de 04 fc 09 15 75 4c 88 78 ec 0b 75 ef d8 1c 74 fa 
Got ApNonce from device: 7e f3 6c 49 53 d6 03 ce c6 7f 42 fc c8 e5 9f ac db fb cd fb 
Got ApNonce from device: 57 6f dd c0 6b 40 ed 79 f3 61 d0 91 95 4e 1e 85 14 db e4 8f 
Got ApNonce from device: 8a db ee d9 7e 49 a4 f8 08 f7 ca 1e 7f b9 bd d9 36 b2 56 ce 



./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw


daniel-macbook-air:futurerestoregood danielpalicka$ ./futurerestore_macos -t Pad5,4_j82ap_11.3.1-15E302_35b68f41ac47972890a0542d80124cce48866436.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
INFO: device serial number is DMPQ524UG5YL
[INFO] 64bit device detected
futurerestore init done
[Error] failed to load apticket at Pad5,4_j82ap_11.3.1-15E302_35b68f41ac47972890a0542d80124cce48866436.shsh2
[Error] Fail code=-9
Failed with errorcode=-9
daniel-macbook-air:futurerestoregood danielpalicka$ ./futurerestore_macos -t blobs.shsh2 -b Mav10-6.80.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_11.3.1_15E302_Restore.ipsw
Version: a0113a4e46bfd00962cd25e3af548fc8b0bd21fd - 173
Odysseus Support: no
INFO: device serial number is DMPQ524UG5YL
[INFO] 64bit device detected
futurerestore init done
reading ticket blobs.shsh2 done
Found device iPad5,4 j82ap
[TSSC] opening BuildManifest.plist
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as j82ap, iPad5,4
Extracting BuildManifest from IPSW
Product Version: 11.3.1
Product Build: 15E302 Major: 15
Device supports Image4: true
Got APNonce from device: a8 17 fd 95 e7 98 8a 46 8a f3 89 06 8a 7e c3 df 4d 2b 83 51 
[Error] Devicenonce does not match APTicket nonce
[Error] maybe you forgot -w ?
Done: restoring failed.
Failed with errorcode=-20
