### ISSUE TITLE
Trying to Downgrade from 10.2.1 to 10.2, I seem to have no collisions 

### ISSUE THREAD

**Issue by mdau2508** [tihmstar/futurerestore#35]
I even tried using all the saved SHSH2 files saved, any luck I will get a collision still running it, its been 2hrs thus far

Version: 6aa188cd06789de1573263aa301a4242db044ceb - 89
futurerestore init done
reading ticket apt1.shsh2 done
reading ticket apt2.shsh2 done
reading ticket apt3.shsh2 done
reading ticket apt4.shsh2 done
reading ticket apt5.shsh2 done
reading ticket apt6.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is ;)
waiting for nonce: 0d c4 48 24 06 96 86 6b 0c c1 b2 ac 3e ca 4c e2 2a f1 1c b3 
waiting for nonce: 42 c8 8f 5a 7b 75 bc 94 4c 28 8a 72 15 39 1d c9 c7 3b 6e 9f 
waiting for nonce: 35 2d fa d1 71 38 34 f4 f9 4c 5f f3 c3 e5 e9 94 77 34 7b 95 
waiting for nonce: 60 3b e1 33 ff 0b df a0 f8 3f 21 e7 41 91 cf 67 70 ea 43 bb 
waiting for nonce: 98 04 d9 9e 85 bb af d4 bb 11 35 a1 04 47 73 b4 df 9f 1b a3 
waiting for nonce: 67 c7 de 71 ce ca ba 13 73 ba 5c 5d ce 2c b6 e4 ae 12 ae bc 
Got ApNonce from device: ba ad fe df 43 9d 50 ae 06 1c 8a 3f 65 15 86 f4 94 36 f0 38 
Got ApNonce from device: 6e 2e 24 23 1d 1e 70 1f 7e d8 fd 2f ae 10 02 17 0e eb db 1d 
Got ApNonce from device: 75 d4 46 94 43 4b 20 ca ec 06 17 ce 11 5a e7 f6 05 1f 52 e9 
Got ApNonce from device: f9 5d ed a5 39 d8 92 f2 4d 3b 63 1e 5b bd 21 40 67 1e 59 3a 
Got ApNonce from device: 82 90 96 ae ef ef f1 4c d7 29 71 dc 1b b0 72 19 8c cc f3 00 
Got ApNonce from device: 8e 62 2c 6a 8f 1b 81 5f c1 ea 79 ee 3c 98 c3 57 33 bc c7 c8 
Got ApNonce from device: 02 22 b0 19 92 e6 dc e5 da ed b8 75 9f 90 30 d4 0c f6 a5 9e 
Got ApNonce from device: 48 27 07 fb a5 5f 7b c5 4d 29 68 5d 79 06 4c 6c 2d 79 26 17 
Got ApNonce from device: f8 23 79 d6 3b ee 7f 37 21 a0 2f 03 f4 a5 09 df ee 23 70 e2 
Got ApNonce from device: f1 ee 70 aa bf 6b c0 5e 2c ea ce 7d 84 da a4 5e cb f3 7c 33 
Got ApNonce from device: 59 13 b5 5a b1 70 c7 c1 8b 34 10 8d 02 ca 7c 9a be 57 d7 5e 
Got ApNonce from device: 8f ce 49 e5 c4 6c ec b4 77 1c 3b a7 8c b8 1f b6 7c 1e 7b 0f 
Got ApNonce from device: 3e 05 0a 0c f4 b2 55 48 b8 35 e5 4b ef 14 a2 59 d8 9f d5 4e 
Got ApNonce from device: 4e 10 db 1a 4a 6d 13 84 92 6f 73 ac 0a 37 4c 20 4f fa 15 e2

**Comment by adi2k17** [comment]
Help same thing happen to me too.

**Comment by tihmstar** [comment]
This is neither a bug, nor an issue with futurerestore

**Comment by latinti81** [comment]
What is it ? Just let it run for ever ?

**Comment by mdau2508** [comment]
@latinti81 I ran it for 14hrs no collision not sure what to do
