### ISSUE TITLE
Stuck at waiting for message from FDR

### ISSUE THREAD

**Issue by Fanatiikon** [tihmstar/futurerestore#356]
I forgot to sign out from icloud. Now futurerestore is stuck at waiting for message from FDR and my iphone is stuck at the update progress bar. Should i leave it and hope for an error or "stop futurerestore" reboot and hope it doesn't brick so i can sign out?

**Comment by masckmaster2007** [comment]
Was it like 60% loaded ? on what stage was it stuck ? Was it gg.apple.com:443 payload ?

**Comment by Fanatiikon** [comment]
This should be closed. I don't remember what I did but I got it working back then.

**Comment by Fanatiikon** [comment]
Irrelevant
