### ISSUE TITLE
I can't downgrade 

### ISSUE THREAD

**Issue by Conoize** [tihmstar/futurerestore#36]
./futurerestore_osx -t 2296988119901222_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1
Segmentation fault: 11

I've been 2 days trying to downgrade from 10.2.1 to 10.2, had several issues that managed to resolve, but now im stuck on this issue just about when it's gonna do the process. I did everything well but , I don't know if the ticket [TSSR] is requesting is a wrong one(it should be 7,2)... for the collision to start happening until it maches...or i am wrong? P.D. I am very interested of doing the process, any help? please?

**Comment by psyco1095** [comment]
Use the latest version of futurerestore --- >  http://api.tihmstar.net/builds/futurerestore/futurerestore-latest.zip
( in the description in this youtube video https://www.youtube.com/watch?v=BIMx2Y13Ukc&t=265s&ab_channel=tihmstar )

**Comment by Conoize** [comment]
now it is starting the process but for some reason, the numbers don't change, its on a infinite loop...


downgrade conoize$ ./futurerestore_macos -t 2296988119901222_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore
Version: 6aa188cd06789de1573263aa301a4242db044ceb - 89
futurerestore init done
reading ticket 2296988119901222_iPhone7,2_n61ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is FFMPQ538G5MG
waiting for nonce: 7a dd 9e 6f 48 dd 53 bf 52 9b 71 84 39 ee c7 95 93 62 16 79 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 
Got ApNonce from device: 77 57 8a 54 d8 69 0c a0 4d 49 84 1d 24 99 28 46 9a da fa 2e 


how do I stop it now?

**Comment by dev135** [comment]
ctrl c

**Comment by Conoize** [comment]
ok thanks! that did it, now...I have to figure why its on a loop, I also got the Bbgoldcertid just in case I needed it...

**Comment by dev135** [comment]
try restoring your phone

**Comment by dev135** [comment]
wait

**Comment by dev135** [comment]
it tried to request a ticket for the iPhone 6s

**Comment by Conoize** [comment]
Yeah, I thought so too but for some reason Changing futurerestore to its latest version now it does it but I get the 100% nonce collision, what does it means? Also I have yalu102 installed... so, can I downgrade?

Get Outlook for iOS<https://aka.ms/o0ukef>

________________________________

**Comment by dev135** [comment]
change the nvram

**Comment by dev135** [comment]
watch tihmstars nonceenabler video

**Comment by dev135** [comment]
yalu 102 has tfp0

**Comment by dev135** [comment]
and nonce enabler built in

**Comment by latinti81** [comment]
someone pls help:

./futurerestore –t 4016551287718438_iPad5,1_j96ap_10.2-14C92.shsh2 –b Mav7Mav8-7.21.00.Release.bbfw –pBuildManifest.plist –s sep-firmware.j81.RELEASE.im4p –m BuildManifest.plist –w iPad_64bit_TouchID_10.2_14C92_Restore.ipsw -w
Found device in Recovery mode
Device already in Recovery mode
[Error] No IM4M loaded
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap: 6

**Comment by modz2014** [comment]
ERROR: Unable to receive message from FDR 0x7fe3025471b0 (-2). 0/2 bytes this is my error

**Comment by tihmstar** [comment]
Title's like "i can't downgrade" are not helpfull in finding out what the issue is. Also this i not a place where downgrading can be discussed, please go on /r/jailbreak or theiphonewiki if you need help downgrading. 
Also you don't seem to be using latest futurerestore. 
If you belive there is a bug in (the latest version of) futurerestore, please open another issue here and describe the bug as detailed as possible. Also describe what you are doing exactly and what behavior you observe on your phone.

**Comment by mdau2508** [comment]
were you able to get a collision

**Comment by latinti81** [comment]
No, i got to run for 13 hrs and now is just running numbers.

**Comment by Conoize** [comment]
nope, i've tried nearly all day, I built a report of failed collisions and sent them to tihmstar's gmail, in order to apport... but nothing :/ Im now trying the nonceenabler method as for the open ssh that he shows on that video I haven't installed it yet, maybe that's what keeping me from doing it, I thought It would be more easy to get the right collision...



Best,


-Christian Vargas

Mixing/Mastering Engineer &

Systems Analyst & Programmer



________________________________
