### ISSUE TITLE
Futurerestore_macos permission denied 

### ISSUE THREAD

**Issue by latinti81** [tihmstar/futurerestore#37]
Can someone help ?  this is with the new file

./futurerestore_macos –t 4016551287718438_iPad5,1_j96ap_10.2-14C92.shsh2 –b Mav7Mav8-7.21.00.Release.bbfw –pBuildManifest.plist –s sep-firmware.j82.RELEASE.im4p.plist –m BuildManifest.plist –w iPad_64bit_TouchID_10.2_14C92_Restore.ipsw
-bash: ./futurerestore_macos: Permission denied

**Comment by BarakaAka1Only** [comment]
You need to change futurerestore_macos to an executable with chmod
`chmod +x futurerestore_macos`
