### ISSUE TITLE
Help NO  IM4M loaded 

### ISSUE THREAD

**Issue by latinti81** [tihmstar/futurerestore#38]
this is with the old file:

 ./futurerestore –t 4016551287718438_iPad5,1_j96ap_10.2-14C92.shsh2 –b Mav7Mav8-7.21.00.Release.bbfw –pBuildManifest.plist –s sep-firmware.j81.RELEASE.im4p –m BuildManifest.plist –w iPad_64bit_TouchID_10.2_14C92_Restore.ipsw -w

Found device in Recovery mode
Device already in Recovery mode
[Error] No IM4M loaded
libc++abi.dylib: terminating with uncaught exception of type int
Abort trap:

**Comment by dev135** [comment]
Put a space between-p and build manifest

**Comment by latinti81** [comment]
Thank you ! Now is searching to nonce past 7 hrs is ok ?

**Comment by dev135** [comment]
YeA

**Comment by latinti81** [comment]
Oh Jesus's ! 😭💦😇 is it like trying to find  middle in the middle of the city
