### ISSUE TITLE
Iphone 5s downgrade Nonce 

### ISSUE THREAD

**Issue by adi2k17** [tihmstar/futurerestore#39]
How long does it take to find the nonce and restore it to iphone 5s 10.2 from 10.2.1? Help

How lone does the process takes?

**Comment by adi2k17** [comment]
Bro somebody say something

**Comment by latinti81** [comment]
I ran the numbers per 7 hrs and I had to restarted. Don't know if anything is working or nkt

**Comment by mdau2508** [comment]
@adi2k17 @latinti81 I ran it overnight for 14hrs still nothing

**Comment by tihmstar** [comment]
Please only use git issues to actually report issues. If you want to discuss downgrading go to /r/jailbreak
