### ISSUE TITLE
Unable to get BasebandFirmware node / unable to find BbGoldCertId

### ISSUE THREAD

**Issue by anykernelpanic** [tihmstar/futurerestore#4]
futurerestore -t 14B150.shsh2 -b memes -p BuildManifest.plist -s sep-firmware.n56.RELEASE.im4p -m BuildManifest.plist -w iPhone_5.5_10.1.1_14B150_Restore.ipsw 
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1 **(wrong model, should be 7,1)**
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[TSSC] opening bbgcid.json
[DOWN] downloading file http://api.tihmstar.net/bbgcid?condensed=1
**ERROR: Unable to get BasebandFirmware node**
**ERROR: Unable to find required BbGoldCertId in parameters**
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=126&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=126, message=An internal error occurred.)
Sending TSS request attempt 1... **[Error] baseband firmware isn't signed**

Program then halts, --latest-baseband causes same issue. Still signed (10.2), so issue is probably due to the program using the first property it finds in the BuildManifest which causes problems when two (or more) models are present?

Not sure how to fix. Advice appreciated.

**Comment by anykernelpanic** [comment]
@tihmstar would you be able to look at the 6+ 10.2 firmware to see if it's incompatible with the tool?

**Comment by tihmstar** [comment]
This was an issue with tsschecker, which should be fixed now.
