### ISSUE TITLE
Taking long to find nonce 

### ISSUE THREAD

**Issue by adi2k17** [tihmstar/futurerestore#42]
why is it talking so long to find the right nonce and downgrade?

**Comment by latinti81** [comment]
I had my iPad mini 4 running for 3 days and I got nothing ! , just running numbers. 
I heard I should stop after 2 hrs enough . 
I am death ! , I guess this doesn't work with my device or doesn't work at ALL

**Comment by dev135** [comment]
Close this it isn't a issue with FutureRestore
