### ISSUE TITLE
iPhone 6 Plus updating from 9.3.3 to 10.2 device does not restore.

### ISSUE THREAD

**Issue by Pokemaster623** [tihmstar/futurerestore#43]
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 7165337494308902_iPhone7,1_n56ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is F2LNT01RG5QK
waiting for nonce: 75 61 8d 23 09 6a c3 40 fd fc 02 29 0f 64 45 18 fa 57 1b 48 
Got ApNonce from device: 75 61 8d 23 09 6a c3 40 fd fc 02 29 0f 64 45 18 fa 57 1b 48 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n56ap, iPhone7,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_5.5_10.2_14C92_Restore/058-54339-094.dmg'
Extracting iBEC.n56.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (632436 bytes)...
waiting for device to reconnect... ....
Getting SepNonce in recovery mode... 27 38 1a 82 91 d3 96 ba ca 54 36 55 69 14 3f 72 2c 61 a5 46 
Getting ApNonce in recovery mode... 75 61 8d 23 09 6a c3 40 fd fc 02 29 0f 64 45 18 fa 57 1b 48 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.30.8
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.t7000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (18834 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330739 bytes)...
Extracting DeviceTree.n56ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (124133 bytes)...
Extracting kernelcache.release.n56...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12368816 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

The device will green screen, enter restore mode, freeze for a few minutes, then return to recovery mode.

**Comment by scach** [comment]
Same issue here for upgrading iPad Mini 2 (WIFI) from 10.1.1 to 10.2:

Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket ../8308796393808_iPad4,4_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as j85ap, iPad4,4
INFO: device serial number is F4KLT30PFCM7
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from '../iPad_64bit_10.2_14C92_Restore/058-54456-094.dmg'
Extracting iBEC.j85.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (640151 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... dc a0 ba 82 88 56 38 e8 53 e5 bd ac 3e 58 fc 0a e6 65 48 10 
Getting ApNonce in recovery mode... 1d 04 78 d4 2c 0b 1a 53 c9 99 18 25 d9 0d 72 f4 fb fc 9e 3b 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.20.16
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (22709 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40342550 bytes)...
Extracting DeviceTree.j85ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (102980 bytes)...
Extracting kernelcache.release.j85...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12033537 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by i0sa** [comment]
"The device will green screen, enter restore mode, freeze for a few minutes, then return to recovery mode."

So can you open the device again anymore with 9.3.3 jailbreak ? just off-question

**Comment by scach** [comment]
In my case (iPad Mini 2 WIFI on 10.1.1) no green screen, no freeze not even any reaction. It simply stays in the restore mode. I am using the JB method with nonce generator.

**Comment by scach** [comment]
And yes. I can boot the device back using iRecovery.

**Comment by tihmstar** [comment]
Are you using a virtual machine?
As soon as the device boots into restore mode it's "recovery mode usb connection" will disconnect and then futurerestore needs to reconnect in restore mode.
If this new USB connection isn't tunneld to the VM too, then it can't find the device.

**Comment by Flattus** [comment]
Same problem at my Iphone 6 Plus at 9.3.3 using JB Me website to open tfp0. I use a VMware Machine with Mac OS Sierra. The VM showes the Iphone as connected (Apple Mobile Device (Recovery Mode)), but I also get errorcode =-11 at futurerestore. I used the jailbreak method with nonceEnabler.

I tried two different SHSH2 blobs with the same result.

mojados-Mac-2:downgrade mojado$ ./futurerestore_macos -t iPhone7,1_n56ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n56.RELEASE.im4p -m BuildManifest.plist -w iPhone_5.5_10.2_14C92_Restore.ipsw
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket iPhone7,1_n56ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is xxxxx
waiting for nonce: 08 60 5a 71 fc b7 a7 30 05 2a 3d 50 ca 3a a1 cd c6 89 ee 1d 
Got ApNonce from device: 08 60 5a 71 fc b7 a7 30 05 2a 3d 50 ca 3a a1 cd c6 89 ee 1d 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n56ap, iPhone7,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_5.5_10.2_14C92_Restore/058-54339-094.dmg'
Extracting iBEC.n56.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (632434 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 41 3f 00 d4 ae 88 b6 b9 aa 62 6c 09 77 0f 03 df 0c 1b 4c b2 
Getting ApNonce in recovery mode... 08 60 5a 71 fc b7 a7 30 05 2a 3d 50 ca 3a a1 cd c6 89 ee 1d 
Recovery Mode Environment:
iBoot build-version=iBoot-2817.60.2
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@3x~iphone.t7000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (18832 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330737 bytes)...
Extracting DeviceTree.n56ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (124131 bytes)...
Extracting kernelcache.release.n56...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12368814 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by scach** [comment]
No. I am not using a VM but a real MacBook.

**Comment by joie1** [comment]
Same problem too :) , who the usb tunneling can be it reconnize again?

"Pc-de-jo-intel-i7:downgrade job$ ./futurerestore_macos -t  235106579578619512_iPad5,4_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j82.RELEASE.im4p -m BuildManifest.plist iPad_64bit_TouchID_10.2_14C92_Restore.ipsw
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 235106579578619512_iPad5,4_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is DMPQG0RVG5YL
Found device in Recovery mode
Identified device as j82ap, iPad5,4
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPad_64bit_TouchID_10.2_14C92_Restore/058-54825-094.dmg'
Extracting iBEC.j82.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (644725 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 9f 5b 7d 9f a6 13 35 5f ac 8a ad 4d fa d2 8f ea 33 05 b0 0d 
Getting ApNonce in recovery mode... c7 9d c9 bb 30 d1 2a b1 04 4d 28 f6 87 0f 4d 79 a8 74 fb 2e 
Recovery Mode Environment:
iBoot build-version=iBoot-2817.60.2
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.t7001.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (23187 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40347124 bytes)...
Extracting DeviceTree.j82ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (121014 bytes)...
Extracting kernelcache.release.j82...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12557601 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11"

**Comment by scach** [comment]
Where is "cached filesystem from '../iPad_64bit_10.2_14C92_Restore/058-54456-094.dmg'" located so that I can delete the cache and start the process from scratch?

**Comment by joie1** [comment]
i put "sudo" before ./futurerestore, and it's the same log, errorcode=-11

**Comment by NM4hdi** [comment]
Dear thimstar, most of people using vm and they'er already succses restoring, so what should we do to solve this error??.

**Comment by ryu16** [comment]
I've had a same problem with @Pokemaster623, but at last I successfully upgraded  my iPhone6s(n71ap)/9.0.2 to 10.2 using MacOS on VM.

I modified futurerestore's codes and I found `restore_device_event_cb()` never received any events, even if my iPhone looks like in restore mode with apple logo and progress bar.
Next, I install libimobiledevice and I run `ideviceinfo`, it returns _"No device found, is it plugged in?"_. It always returns _"No device found"_, so I thought it was kind of problem between usb devices and MacOS.

<a href="http://stackoverflow.com/questions/36139020/macos-doesnt-recognize-ios-device-on-vmware">MacOS doesn't recognize iOS device on VMware (stackoverflow.com)</a> helps me.
Just I did is in the VM Settings:
- Set the USB compatibility to be 2.0 instead of 3.0
- Check the setting "Show all USB input devices"

After that, `ideviceinfo` returns many informations successful.
Now it's a time to run futurerestore again, and it should be successfully finished.

If you have a same problem, check out what `ideviceinfo` command says.

**Comment by jj9901180** [comment]
I am stuck in the exact same situation... iTunes and ReiBoot detects the iphone perfectly and could prompt the iphone out of recovery mode... so I believe it may be a bug within future restore and unrelated to the VM

**Comment by aicjofs** [comment]
Same issue. Iphone 6 with 9.3.3 attempting to go to 10.2.  I have tried El Capitan on a Mac, Ubuntu 16 on PC and VM, and Sierra on VM.  All the same result "waiting for device", there was no green flash as it looks like should happen from viewing the code.   Do we need a post of a "-d" flag to get some debugging info? The device is always detected because I can immediately kick it back out of recovery with irecovery -n.  Let me know what you need as it would be nice to figure this out before the SEP for 10.2.1 is no longer signed.

**Comment by TexasSvejk** [comment]
iPhone 6 jb v9.3.3 trying to reach v10.2 using Sierra on a Mac yields

  _Received SHSH blobs
  About to restore device... 
  Waiting for device...
  ERROR: Unable to connect to device in restore mode
  ERROR: Unable to open device in restore mode
  [Error] ERROR: Unable to restore device
  Done: restoring failed.
  Failed with errorcode=-11__

I'll be checking here daily, thnx.

**Comment by ryu16** [comment]
I'll restore iPhone 6 this weekend 8.1 -> 10.2, I'll see if this problem occurs again and I'll report the result.
In my understanding...
`futurerestore` is waiting a "iPhone reconnected" event from <a href=https://www.theiphonewiki.com/wiki/Usbmux>usbmux</a> which indicates iPhone's mode changed to "RESTORE" mode showing apple logo and progress bar from "RECOVERY" mode showing lightning cable logo.
If you see your iPhone shows apple logo and progress bar, the reason stuck in this situation is usbmux has a problem about detecting iPhone and reporting event.
Because `irecovery` does not depend on usbmux and it directly communicates with iPhone, `futurerestore` could fail even if `irecovery` works fine.
Because `ideviceinfo` asks usbmux to show result, `ideviceinfo` is useful to check if usbmux has a problem or not.

**Comment by ryu16** [comment]
Now my iPhone 6 is 10.2. There are no problem upgrading 8.1 -> 10.2. Sorry for no hints.

**Comment by zdrole** [comment]
@ryu16 , did you run Cydia eraser and installed JB on fresh system before futurerestore? Which OS: linux,vm or mac?

**Comment by ryu16** [comment]
@zdrole , Yes I did Cydia eraser, but I don't recommend it if you have old iOS like 8.1.
I re-jailbreaked by PPJailbreak v1.0.2 on Windows 10. It was too unstable but succeeded.
I ran futurerestore on latest macOS Sierra which is in vm on Windows 10. I succeeded running futurerestore at first time.

Below is just FYI.
At first my iPhone 6 was jailbreaked by Pangu. I thought nonceEnabler wouldn't work even after I applied saurik's patch, so I wanted to re-jailbreak by Taig and I ran Cydia eraser. It was fault because both of Pangu and Taig had been ended iOS 8.1 jailbreaking. Also, I heard at reddit that nvrampacher worked fine against Pangu with saurik's patch.

**Comment by tihmstar** [comment]
So i decided to not support futurerestore inside a VM. If it doesn't work, try on real hardware before opening an issue.
Also version 95 of futurerestore attempts to fix the other problem causing "Unable to connect to device in restore mode", so please try again with that version.
If that still doesn't work please refer to #77 which is basically the same problem (for those who don't use a VM)
