### ISSUE TITLE
FutureRestore for Linux keeps throwing a segmentation fault

### ISSUE THREAD

**Issue by Pollsmor** [tihmstar/futurerestore#45]
As far as I can tell, no one has gotten FutureRestore to work on Linux - made a Reddit post on /r/jailbreak to ask, tried to look for videos of people using it on Linux, but no. I can only find people who have had successes with macOS.

I'm using Bash for Windows, but it shouldn't be any different from running Ubuntu itself. I managed to get to the last step where I have to type the ./FutureRestore command, but then attempting to restore gives me a segmentation fault (core dumped) message. As far as I can tell, I am using the latest compiled version of FutureRestore (v90).

Screenshot: 
https://gyazo.com/43c2243d33146df0ee8b31d4a1614f91

**Comment by turnerrocks1** [comment]
Yea the problem is delete the space between -90

**Comment by vec1phyr** [comment]
Where exactly can I delete this space? I'm not finding it

**Comment by Pollsmor** [comment]
Me neither. The whole version 90 thing isn't anything that I typed into the console. 

Kind of a stretch, but maybe FutureRestore doesn't work on AMD? lol

**Comment by tihmstar** [comment]
There might actually be bugs in the code which segfault when certain (not properly checked) conditions fail. Though i'm not looking into debugging this on windows. Try it on a real linux machine. If you still get a segfault, i'll look into it at some point. There is no windows support atm.

**Comment by Pollsmor** [comment]
I actually just wanted to test if this would work (nothing wrong with my device on 10.2 now). On a totally unrelated note, I decided to try Ubuntu instead of installing it (as I don't want to deal with having Linux along with Windows) and just about nothing worked inside it. So I'll just stick for now.

**Comment by mailinglists35** [comment]
>I'm using Bash for Windows, but it shouldn't be any different from running Ubuntu itsel

yes it is different. on win10 bash you don't have hardware devices, including usb.
