### ISSUE TITLE
[Error] argument parsing failed! agrc=14 optind=2

### ISSUE THREAD

**Issue by kingofkilled** [tihmstar/futurerestore#48]
Hi, I tried restore my ip 5s to ios 10.2 but i'm getting those error, please help.

`./futurerestore_macos –t /Users/xer/Desktop/Downgrade/first.shsh –b /Users/xer/Desktop/Downgrade/Mav7Mav8-7.21.00.Release.bbfw –p /Users/xer/Desktop/Downgrade/BuildManifest.plist –s /Users/xer/Desktop/Downgrade/sep-firmware.n51.RELEASE.im4p –m /Users/xer/Desktop/Downgrade/BuildManifest.plist –w -d iPhone_4.0_64bit_10.2_14C92_Restore.ipsw
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
[Error] argument parsing failed! agrc=14 optind=2
argv[0]=./futurerestore_macos
argv[1]=-d
argv[2]=–t
argv[3]=/Users/xer/Desktop/Downgrade/first.shsh
argv[4]=–b
argv[5]=/Users/xer/Desktop/Downgrade/Mav7Mav8-7.21.00.Release.bbfw
argv[6]=–p
argv[7]=/Users/xer/Desktop/Downgrade/BuildManifest.plist
argv[8]=–s
argv[9]=/Users/xer/Desktop/Downgrade/sep-firmware.n51.RELEASE.im4p
argv[10]=–m
argv[11]=/Users/xer/Desktop/Downgrade/BuildManifest.plist
argv[12]=–w
argv[13]=iPhone_4.0_64bit_10.2_14C92_Restore.ipsw`

is there anything wrong with my command ?

**Comment by tihmstar** [comment]
I've seen this before. Quite a few people seem to have this issue. I have no idea what is causing the issue, but i'm aware it's there.

**Comment by Dollar2011** [comment]
last update futurerestore error argument parsing failed! agrc=14 optind=2

**Comment by huyle0406** [comment]
please, anyway to fix this bug, now?

**Comment by joie1** [comment]
download reiboot to kick out

**Comment by tof205** [comment]
i have the same argument parsing failed! :( 
i tried to run it from 2 different vm (el capitan and sierra) and a linux (not in a vm) all get the same error :(
can it be related to openssl? or to my hardware acer aspire E5-575g?
i got this output from noncestatistic : 
./noncestatistics: /usr/lib/libcrypto.so.1.0.0: no version information available (required by ./noncestatistics)
./noncestatistics: /usr/lib/libssl.so.1.0.0: no version information available (required by ./noncestatistics)
Version: 4d63cd472ecc4087d4443df208bc5e99eeb25e89 - 37
Identified device as n53ap, iPhone6,2 in normal mode... Trying to get in recovery...
INFO: device serial number is 

No ECID was specified. Checking if any device is connected.
Getting nonce statistics for device with ECID: 
000001	ApNonce=fba7ececbd5f60fdee835ecd89c1d93ae8cac256
cheers

**Comment by tihmstar** [comment]
Still haven't figured out the root cause of the problem. I know it happens when using my public compiled version, but i never had the issue compiling it right on my system.
Yesterday i successfully restore with the public build so in case this happens again, please open another issue
