### ISSUE TITLE
Error=-20 Devicenonce does not match APTicket nonce

### ISSUE THREAD

**Issue by prodigymd** [tihmstar/futurerestore#49]
Im trying to upgrade from 9.3.3--> 10.2 using my saved SHSH2 tickets on a 6S+.
having done all the other steps correctly I'm stuck at:

Any idea where the problem is? 

Many thanks!!!

./futurerestore_macos -t iPhone8,2_HELLO_14C92.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n66m.RELEASE.im4p -m BuildManifest.plist iPhone_5.5_10.2_14C92_Restore.ipsw 
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket iPhone8,2_HELLO_14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as n66map, iPhone8,2
INFO: device serial number is HELLO
[Error] Devicenonce does not match APTicket nonce
[Error] maybe you forgot -w ?
Done: restoring failed.
Failed with errorcode=-20

#**_**The tsschecker tool gives me this:**_**
Apnonce: a0b5c2125bc452599acd8f23f9d16d1402d74c9b
Build Number: 14C92
Board Configuration: n66map
Restore Behaviour: Erase
Rosi Tag: true

[IMG4TOOL] file is valid!

arg :--verify
Version: 17060e500a853a9b4ed860f246d3aa0a90258e31 - 85
Version: 0
MANB
MANP: MANP: ------------------------------
BNCH: BNCH: a0b5c2125bc452599acd8f23f9d16d1402d74c9b
BORD: BORD: 6
CEPO: CEPO: 1
CHIP: CHIP: 32771
CPRO: CPRO: true
CSEC: CSEC: true
ECID: ECID: HELLO
SDOM: SDOM: 1
snon: snon: a0b5c2125bc452599acd8f23f9d16d1402d74c9b
srvn: srvn: 0683fab915f7689d2aa3d72fc2c15c8330515e30

[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware

IM4M is valid for the given BuildManifest for the following restore:
BuildNumber : 14C92
BuildTrain : Corry
DeviceClass : n66map
FDRSupport : YES
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

[IMG4TOOL] file is valid!

**Comment by dev135** [comment]
Add -w 😑

**Comment by prodigymd** [comment]
With the -w it starts checking for a collision isn't that right? it starts going through a constant boot loop checking for the nonce matching. Whats the point of having my generator/shsh2 if its not going to hit the right apnonce the first time? Or am i understanding it wrong? I did run it with -w for an hour yesterday but there was no luck.

**Comment by dev135** [comment]
That's not how it works... you need the -w to find the nonce to downgrade the shsh2 blob is just to sign it

**Comment by dev135** [comment]
When the apnonce and the devicenonce match it downgrades

**Comment by dev135** [comment]
Lol nvm the iPhone 6s won't work you can't use collision

**Comment by dev135** [comment]
Unless your jailbroken

**Comment by prodigymd** [comment]
I am jail broken, and I use nonceEnabler :)

**Comment by shadww** [comment]
did you confirm the correct nonce is loaded?
try `nvram -p` it will show you the current values.

usually you need to set these two values before you proceed with futurerestore.
nvram com.apple.System.boot-nonce=your_nonce_in_the_blobs
nvram auto-boot=false

**Comment by prodigymd** [comment]
Yea! 
I did confirm that too. Those two values are set. The nonce is the generator at the end of the blob. 
Somethings just not right. i think the device resets the nvram on reboot to recovery. I'm not sure.

**Comment by dev135** [comment]
Invaild blob

**Comment by prodigymd** [comment]
If it's an invalid blob then tsschecker and img4tool are wrong to say that it's valid because it matches my board model, and the ROSI tag, and restore build (10.2)

**Comment by tihmstar** [comment]
Can you try adding the -w flag so that futurerestore displays what apnonce it expects to see and what apnonce it actually got from device.
Can you also check whether the *wrong* apnonce you get from device is always the same *wrong* nonce when you write the generator to nvram? (check what nonce you get. You can also do that with igetnonce or recent version of irecovery)
Do you get an error when writing the generator to nvram?
Can you post the generator you're using? i wanna check if the generator is wrong.

**Comment by prodigymd** [comment]
This is the step by step results:

**nonceEnabler:**

-iPhone:~ root# ./nonceEnabler
separt=com.apple.System.sep.art
kbase=0xffffff801e604000
kbase=0xffffff801e604000
kbase=0xffffff801f604000
[*] found bytes at 0x               0
kmem=-----com.apple.System.sep.art-----
nextstr=-----com.apple.System.boot-nonce-----
[*] found com.apple.System.sep.art at 0xffffff80202b2da7
[*] found com.apple.System.boot-nonce at 0xffffff80202b2dc0
kbase=0xffffff801e604000
kbase=0xffffff801f604000
[*] found bytes at 0x               0
kmem=-----?-+ ????-----
[*] patching bytes at=0xffffff8020317b70
[*] done patching


Then setting generator in nvram result:

-iPhone:~ root# nvram -p
boot-args	
com.System.boot-nonce	0xb362f962744b8b11
auto-boot	false
backlight-level	1527

**The first apnonce I get from the device is not always the same. It actually always changes. 
Here's the latest one:**
waiting for nonce: ca 77 de b0 66 7d e7 b5 35 b5 fb 4a 04 6f fc b5 71 fd 4c 3f 
Got ApNonce from device: d1 c7 68 8f fe 28 6c 96 04 24 53 1d 83 45 c8 8c a4 64 d9 4b 
Got ApNonce from device: 77 4e 78 ce 78 c2 01 3e db 06 1b f9 05 aa 6b 6d c0 59 6f 8a 
 and so on......


**on irecovery:**

irecovery -q
CPID: 8003
CPRV: 01
BDID: 06
ECID: 6272886052192806
CPFM: 03
SCEP: 01
IBFL: 1d
SRNM: F2LRR1KKGRWY
IMEI: N/A
NONC: b7e070427491df4698a50b7dd668720d85f92163
SNON: 2728f65d00acf2f121a0514404c2dcd5ed6e4dc3
MODE: Recovery

**Now the next time i run future restore (without rebooting):**
waiting for nonce: ca 77 de b0 66 7d e7 b5 35 b5 fb 4a 04 6f fc b5 71 fd 4c 3f 
Got ApNonce from device: b7 e0 70 42 74 91 df 46 98 a5 0b 7d d6 68 72 0d 85 f9 21 63 


I have two SHSH2 files (one update and the other erase) both with generators:
0xb362f962744b8b11
0x326a6d963bf5e2c3

I tried futurerestore with both files, same result. I tried nvram_patcher, i tried nonceEnabler from cydia, I tried it with SSH.

**Comment by dev135** [comment]
Same happens to me on my iPhone six but the nonce didn't change

**Comment by prodigymd** [comment]
I think if the generator checks out, then the issue lies with nonceEnabler. or that the generator resets when the phone enters into recovery mode. 
Is there a way to set the generator in nvram while in recovery mode? 
Or, is there a way to run "nvram -p" in recovery mode to check if the generator is still set?

**Comment by TwentyFour-24** [comment]
I'm having sort of the same problem. Did you save your SHSH2 files with Ticketbox?
Cause that was the program I used...

Always the first ApNonce is the same, so I think the nonceEnabler works fine. After that, the Phone generates always a new one, as intended, I guess. Prolly that generator value is screwed, making the wrong ApNonce.

Question is, can anything be done about that, or can we just throw those blobs into the trash?

**Comment by prodigymd** [comment]
Yes Indeed i did use ticketbox. No I dont think it has to do with that generator. the blobs are valid. The issue is in the phone resetting the nvram on entering recovery. when you check the nonce in the phone using (irecovery -q) I think its nothing like the generator gives. 
Try using https://www.dropbox.com/s/306l6ldyw5hvdri/nvrampatcher?dl=0 
Instead of nonceEnabler. Still doesn't work for me though.

**Comment by TwentyFour-24** [comment]
Oh okey, then I missread something. I am always getting the same first ApNonce, but it's not matching the ApNonce needed for the blob, though I'm using the generator value from that exact same file.
But I guess my problem lies at Ticketbox 0.4.2 having a bug, that's meanwhile fixed.

**Comment by prodigymd** [comment]
You're absolutely right! I updated ticket box re requested SHSH2 and the new files had a different generator. the restore however did not go through. it failed halfway and now i have an iPhone in continuous boot loop that refuses to exit. oh well. so this issue can now be closed!
