### ISSUE TITLE
issue on futurerestore to downgrade 10.2 from 10.2.1

### ISSUE THREAD

**Issue by Ghawasib** [tihmstar/futurerestore#50]
when itry to downgrade from 10.2.1 to 10.2 its shown this error 

./futurerestore_macos -t 2985776024748_iPhone8,2_N66AP_10.2-14C92.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n66.RELEASE.im4p -m BuildManifest.plist -w iPhone_5.5_10.2_14C92_Restore.ipsw
**# ## Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
[Error] argument parsing failed! agrc=12 optind=10**

can you advise what the issue please.

**Comment by dev135** [comment]
You can't downgrade from 10.2.1 to 10.2 it's patched

**Comment by p0werd0wn** [comment]
-w ?

**Comment by tihmstar** [comment]
This is probably the same bug as in #48
