### ISSUE TITLE
iP6 failed restore and error  -11 on VM

### ISSUE THREAD

**Issue by gkeyes** [tihmstar/futurerestore#54]
`sworddeMac:downgrade sword$ ./futurerestore_macos -t 4316080029587442893_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist  -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w ios10.2.ipsw
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 4316080029587442893_iPhone7,2_n61ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is F17NTFBLG5MR
waiting for nonce: bc 14 34 44 fa 42 9c 8b e9 60 ae 76 81 0e 06 e1 a6 0b 57 a7 
Got ApNonce from device: bc 14 34 44 fa 42 9c 8b e9 60 ae 76 81 0e 06 e1 a6 0b 57 a7 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'ios10.2/058-54986-095.dmg'
Extracting iBEC.n61.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (632437 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... d5 84 ac 37 3c a7 f6 cf 03 cd ad bf c6 f5 3c 70 dc 53 11 a9 
Getting ApNonce in recovery mode... bc 14 34 44 fa 42 9c 8b e9 60 ae 76 81 0e 06 e1 a6 0b 57 a7 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.30.8
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.t7000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12117 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330740 bytes)...
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (123930 bytes)...
Extracting kernelcache.release.n61...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12368817 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11`

this is my code 
`./futurerestore_macos -t 4316080029587442893_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist  -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w ios10.2.ipsw`

i want to update iPhone 6 from 10.2 to 10.2 on VM, and have tried many times but failed.

i have check my shsh2 and the website show it is valid .

my device is on recovery mode and DeviceUtilz shows recovery device connected. but futurerestore can't detect my divece and are always show 'wait for device'.

When i made my device exit recovery mode, futurerestore shows the device connected was  in normal mode. i also tried let my device enter recovery mode manually, but  useless.

**Comment by gkeyes** [comment]
i have set USB 2.0 compatibility,  iTunes on VM works fine.

**Comment by gkeyes** [comment]
Tried on virtualbox macOS 10.11 , got the same return -11

**Comment by prodigymd** [comment]
Dont enter recovery before you run futurerestore. Some have found that to be useful. Also try using iPhoneTunnel in VM.

**Comment by gkeyes** [comment]
Yes, i know it. Thank you .
Before asked this question , I have tried to enter future restore command when my device was in normal mode in jailbreak. And with the future restore run, device entered  recovery mode automatically, then showed  "wait for device " . Meanwhile, device had no reaction.  So, i  have did what you say, failed .

**Comment by DanTheGamer123** [comment]
I am also having this problem #59 and I also don't know what the problem is. I know its not my virtual machine because I installed VMware tools, I have USB 2.0 compatitability enabled, iTunes recognizes my device and my iPhone is plugged into a USB 2.0 slot and futurerestore still won't recognize my device. If I ever fix this problem, I could eventually downgrade from ios 10.2.1 to 10.2 essentially using the NonceEnabler method

**Comment by dev135** [comment]
DanTheGamer123 there is no iOS 10.2.1 jb and you can't downgrade from iOS 10.2.1 to iOS 10.2 it's patched idiot

**Comment by charles-passille-smartnets** [comment]
Same issue here, going from Taig 8.4 -> 10.2

Any idea? It's saying skipping baseband also, goes with the recovery and stuck at Waiting for device...

**Comment by Pollsmor** [comment]
You have to add your iPhone as a USB device filter. However, remove everything in the columns except for the "Name" (fill in Apple Inc. iPhone) and "Manufacturer", which should stay as Apple Inc. All the others should be blank.

This is because for some reason the device ID or whatever changes after every restore.

**Comment by charles-passille-smartnets** [comment]
@Pollsmor i tried it on an actual Mac as well and same error, seems like my blobs shsh2 arent valid, I did it using an online tool and apparently there was some bug with it...img4tool seems to think it's valid though.

**Comment by tihmstar** [comment]
Same as https://github.com/tihmstar/futurerestore/issues/41#issuecomment-287762026 
no support for VM
