### ISSUE TITLE
Stuck with error code -44

### ISSUE THREAD

**Issue by TwentyFour-24** [tihmstar/futurerestore#57]
Hello guys,

as you can see in the log down here, I just have a valid shsh2 blob file for "update" instead of "erase". My other, complete set from 1Conans TSS-tool are for the wrong board.

So here my question, is there any way to get futurerestore done with that file, or am I just screwed? :)
I read something about the -u parameter of futurerestore to just use the update mode (where my blob would work in theory), but can that work on a major upgrade from 9.0.2 -> 10.2?

Thanks for you're time and best regards

```
[Error] BuildIdentity selected for restore does not match APTicket

BuildIdentity selected for restore:
BuildNumber : 14C92
BuildTrain : Corry
DeviceClass : j72ap
FDRSupport : NO
RestoreBehavior : Erase
Variant : Customer Erase Install (IPSW)

BuildIdentiy valid for the APTicket:
BuildNumber : 14C92
BuildTrain : Corry
DeviceClass : j72ap
FDRSupport : NO
RestoreBehavior : Update
Variant : Customer Upgrade Install (IPSW)

[Error] APTicket can't be used for this restore
Done: restoring failed.
Failed with errorcode=-44
```

**Comment by tihmstar** [comment]
Yea so -u should work, even though i don't recommend doing major upgrade.
Simply pass that flag and it should do the upgrade instead erase.
