### ISSUE TITLE
iPhone 6s errorcode=11 VM

### ISSUE THREAD

**Issue by DanTheGamer123** [tihmstar/futurerestore#59]
Im trying to downgrade from ios 10.2.1 to 10.2 using a custom shsh blob, everything works out but futurerestore doesn't detect my device, I know its nothing wrong with my virtual machine since iTunes can detect my device.

Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket iPhone8,1_n71ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is 
waiting for nonce: aa 1a c8 5c 42 9d 40 de 2c a7 c2 72 40 7c f9 02 61 47 ab 18 
Got ApNonce from device: aa 1a c8 5c 42 9d 40 de 2c a7 c2 72 40 7c f9 02 61 47 ab 18 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n71ap, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=rfta
[Warning] hasBuildidentityElementWithHash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_4.7_10.2_14C92_Restore/058-54986-095.dmg'
Extracting iBEC.n71.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (333507 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... c3 23 9f cb 02 57 fc 2a 7d 7d 49 08 39 23 70 4c 38 c9 de 11 
Getting ApNonce in recovery mode... aa 1a c8 5c 42 9d 40 de 2c a7 c2 72 40 7c f9 02 61 47 ab 18 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.42.5
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.s8000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12195 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330818 bytes)...
Extracting DeviceTree.n71ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (132848 bytes)...
Extracting kernelcache.release.n71...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12592991 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by gkeyes** [comment]
maybe something is wrong with your shsh2.

**Comment by DanTheGamer123** [comment]
It shouldn't be, the process goes through for the most part, all i did was copy my 10.2.1 apnonce and paste it with my valid 10.2 blob using the apnonce I requested. I'm not sure but it might be something with futurerestore

**Comment by Brigdeez** [comment]
Please explain how you made a custom shsh2 blob.   I've been searching everywhere on how to do it. I am on iOS 10.2 and I have lost my 10.2 blob so I'm trying to figure out a way to customize a 10.2.1 blob to work as a 10.2 blob.    At that point, I'm guessing I could use future restore to get back to 10.1.1. Am I way off base here?

**Comment by dev135** [comment]
Can't downgrade from 10.2.1 to 10.2 it's patched close this

**Comment by dev135** [comment]
And the 6s doesn't work with it either you should really learn how it works before you report a "problem"

**Comment by DanTheGamer123** [comment]
dev135 the 6s does work, i'm using a different custom method for downgrading and a downgrade from 10.2.1 or 10.3 to 10.2 does work as it has been confirmed by other people using noncecollision. I'm trying a method similar to NonceEnabler. I believe the problem is that i'm using a virtualmachine and it doesn't detect the device in recovery mode, i'll need to borrow a mac and test this but once I do, I should be able to sucessfully downgrade from 10.2.1 to 10.2. If a downgrade from 10.2.1 to 10.2 doesn't work, then how can I sucessfully go through with futurerestore until it can't detect the device? I'm not trying to roast you or anything but i'm seriously curious. Do you have to be jailbroken in order for futurerestore to detect your device in recovery mode or is it just my virtual machine. Also my shsh file shouldn't be corrupted as first of it goes through futurerestore and second off in the iOS 10 SHSH Blob Checker by 1Conan where I saved by shsh2 blob file, with my custom file, everything it valid so it shouldn't be the shsh file. I also posted 2 reddit tutorials on this matter if you are still confused on what i'm talking about.(https://www.reddit.com/r/jailbreak/comments/5utjfy/tutorial_how_to_request_a_repeating_apnonce_in/ and https://www.reddit.com/r/jailbreak/comments/5uil5n/help_almost_found_a_way_to_go_from_1021_to_102/).

**Comment by Pollsmor** [comment]
You have to add your iPhone as a USB device filter. However, remove everything in the columns except for the "Name" (fill in Apple Inc. iPhone) and "Manufacturer", which should stay as Apple Inc. All the others should be blank. 

This is because for some reason the device ID or whatever changes after every restore.

**Comment by DanTheGamer123** [comment]
@Pollsmor Can you make a guide on this? I'm confused on what you are telling me to do and how to do it.

**Comment by tihmstar** [comment]
Same as #41 (comment)
no support for VM
