### ISSUE TITLE
TSS server returned: STATUS=126&MESSAGE=An internal error occurred.

### ISSUE THREAD

**Issue by argp** [tihmstar/futurerestore#6]
Can't replicate with the following setup:

```
$ futurerestore -t iPhone8,1_10.1.1-14B150.shsh -b Mav13-2.41.00.Release.bbfw \
     -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p -m BuildManifest.plist \
     -w iPhone8,1_4.7_10.1.1_14B150_Restore.ipsw

[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone8,1
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[TSSC] opening bbgcid.json
[DOWN] downloading file http://api.tihmstar.net/bbgcid?condensed=1
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=126&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=126, message=An internal error occurred.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed
```

**Comment by anykernelpanic** [comment]
6s+ should be using the other baseband file (starts with 5), I believe - copy it from 10.2 FW and see if you still have this issue?

**Comment by anykernelpanic** [comment]
Actually, second thoughts, wouldn't resolve this issue since they're both signed. Is a bug.

**Comment by medkintos** [comment]
@anykernelpanic, @argp use the right baseband file. Mav10.5.23 is for iPhone 6 & 6+

i got that error too, so i'm waiting tihmstar to fix it...

`Medios-iMac:futurerestore mediorahmat$ ./futurerestore_osx -t 3793109107531814_iPhone7,2_10.1.1-14B150.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.1.1_14B150_Restore.ipsw
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone7,2
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] opening BuildManifest.plist
[TSSR] requesting ticket for iPhone7,2
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[TSSC] opening bbgcid.json
[DOWN] downloading file http://api.tihmstar.net/bbgcid?condensed=1
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
TSS server returned: STATUS=126&MESSAGE=An internal error occurred.
ERROR: TSS request failed (status=126, message=An internal error occurred.)
Sending TSS request attempt 1... [Error] baseband firmware isn't signed`

**Comment by argp** [comment]
v67 works for me now:

```
$ ./futurerestore -t iPhone8,1_10.1.1-14B150.shsh \
    -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p \
    -m BuildManifest.plist -w iPhone8,1_4.7_10.1.1_14B150_Restore.ipsw

Version: bdc7cc1542c5fecb9ddac4c9134a0c546687caa9 - 67
futurerestore init done
reading ticket iPhone8,1_10.1.1-14B150.shsh done
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is XXXXXXXXXXXX
waiting for nonce: da 21 82 06 49 8f f7 60 01 c8 ae 2e 22 47 13 c2 93 c5 05 6c
Got ApNonce from device: 36 34 82 f4 09 f4 b7 fc de 9f 12 74 da b9 13 95 d4 c7 ba 25
Got ApNonce from device: e8 5e bd 9b df 17 bb f3 ef a5 e0 91 45 96 c3 d8 98 d5 f5 1a
Got ApNonce from device: 2e 82 dd 70 f9 64 22 86 84 4a 2f e8 64 91 37 e3 9f 22 9e bd
...
```

Cheers!

**Comment by izaman1** [comment]
> v67 works for me now:
> 
> ```
> $ ./futurerestore -t iPhone8,1_10.1.1-14B150.shsh \
>     -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p \
>     -m BuildManifest.plist -w iPhone8,1_4.7_10.1.1_14B150_Restore.ipsw
> 
> Version: bdc7cc1542c5fecb9ddac4c9134a0c546687caa9 - 67
> futurerestore init done
> reading ticket iPhone8,1_10.1.1-14B150.shsh done
> Did set sep+baseband path and firmware
> [TSSC] opening BuildManifest.plist
> WARNING: Unable to find BbSkeyId node
> [TSSR] User specified not to request a Baseband ticket.
> Request URL set to https://gs.apple.com/TSS/controller?action=2
> Sending TSS request attempt 1... response successfully received
> [TSSC] opening BuildManifest.plist
> WARNING: Unable to find BbSkeyId node
> [TSSR] User specified to request only a Baseband ticket.
> ERROR: Unable to get BasebandFirmware node
> ERROR: Unable to find required BbGoldCertId in parameters
> Request URL set to https://gs.apple.com/TSS/controller?action=2
> Sending TSS request attempt 1... response successfully received
> Found device in Normal mode
> Entering recovery mode...
> INFO: device serial number is XXXXXXXXXXXX
> waiting for nonce: da 21 82 06 49 8f f7 60 01 c8 ae 2e 22 47 13 c2 93 c5 05 6c
> Got ApNonce from device: 36 34 82 f4 09 f4 b7 fc de 9f 12 74 da b9 13 95 d4 c7 ba 25
> Got ApNonce from device: e8 5e bd 9b df 17 bb f3 ef a5 e0 91 45 96 c3 d8 98 d5 f5 1a
> Got ApNonce from device: 2e 82 dd 70 f9 64 22 86 84 4a 2f e8 64 91 37 e3 9f 22 9e bd
> ...
> ```
> 
> Cheers!

how what was the error
