### ISSUE TITLE
errorcode=-11 tried everything, please look

### ISSUE THREAD

**Issue by mdk250** [tihmstar/futurerestore#68]
Hello, first i'd like to thank your for all the hard work you put in the tools. 

I have tried to use future restore on 2 different iMacs, a vm mac and now vm linux. All these systems gave me the exact same code. I am using a iPhone 6 with n61ap, and it is on ios 9.0.2. I set the nonce using cl0ver and nonceEnabler and have even used nvram patcher, setting the nonce is a succes. I have also checked the shsh2 blob and it is valid. But when i run future restore it gives me the same error code over and over again. Also, i have read almost all the Issues regarding this and the solutions and it still won't work. Can you help ? Thanks in advance.

--@ubuntu:~/Desktop/downgrade$ sudo ./futurerestore_linux -t 1162218836_iPhone7,2_n61ap_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n61.RELEASE.im4p -m BuildManifest.plist iPhone_4.7_10.2_14C92_Restore.ipsw 
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 1162218836_iPhone7,2_n61ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is --------
Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from 'iPhone_4.7_10.2_14C92_Restore/058-54986-095.dmg'
Extracting iBEC.n61.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (632432 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 53 de e7 e9 65 05 ea e4 20 a9 01 d6 9c 43 f9 35 6b 68 32 ec 
Getting ApNonce in recovery mode... af 82 7b f3 03 49 5c 16 c3 8a 18 64 d8 8a 86 3f f8 3e b2 e9 
Recovery Mode Environment:
iBoot build-version=iBoot-2817.1.94
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.t7000.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12112 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330735 bytes)...
Extracting DeviceTree.n61ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (123925 bytes)...
Extracting kernelcache.release.n61...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12368812 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by Pollsmor** [comment]
Did you set your USB filter correctly?

**Comment by brymonster** [comment]
same issue on mac. 
[error 11.txt](https://github.com/tihmstar/futurerestore/files/823169/error.11.txt)

**Comment by tihmstar** [comment]
Please try again with version 95 of futurerestore

**Comment by tihmstar** [comment]
Should be fixed by now
