### ISSUE TITLE
errorcode -15, failed to read SEP - N71mAP 10.2 - Linux Debian 8.7.1

### ISSUE THREAD

**Issue by GeekBreak** [tihmstar/futurerestore#69]
Hi, I'm trying futurerestore with my iPhone 6S (TSMC n71map), tried various things to fix, like re-downloading the 10.2.1 iPSW to extract again required files, also tried different blobs (I have 3/4 for this device, all verified)
On macOS works fine.
Obviously "ECID" is my *real* ECID

root@GeekBreak-PC:/home/geekbreak/Scrivania/Downgrade# ./futurerestore_linux -t ECID_iPhone8,1_n71map_10.2-14C92.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71m.RELEASE.imp4 -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket ECID_iPhone8,1_n71map_10.2-14C92.shsh2 done
[Error] failed to read SEP
[Error] Fail code=-15
Failed with errorcode=-15

**Comment by GeekBreak** [comment]
Fixed, instead of writing just the filename of the files, I wrote the complete path

**Comment by TkaRoman** [comment]
Hi, GeekBreak! I have the same problem. What do you mean "wrote the complete path"? Could you write an exemple, please. Thanks.

**Comment by GeekBreak** [comment]
@TkaRoman instead of just "-t file.shsh2 -b File.bbfw" > "-t /home/user/file.shsh2 -b File.bbfw"

**Comment by TkaRoman** [comment]
Ok, big thanks
