### ISSUE TITLE
ERROR: device "iPhone9,2" is not in bbgcid.json

### ISSUE THREAD

**Issue by IntricateD** [tihmstar/futurerestore#7]
ERROR: device "iPhone9,2" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet. If you own such a device please consider contacting @tihmstar (tihmstar@gmail.com) to get instructions how to contribute to this project.

please help!

**Comment by leo98gomez** [comment]
he said future restore wasn't going to be compatible with the iPhone 7 once it came out. He has to update it, so you have to wait for that update that adds compatibility.

**Comment by tihmstar** [comment]
Currently the iPhone 7 is not compatible with futurerestore.
