### ISSUE TITLE
[SOLUTION] errorcode=-11

### ISSUE THREAD

**Issue by jeonghyeonchoe** [tihmstar/futurerestore#70]
terminal message...

> Sending TSS request attempt 1... response successfully received
> Received SHSH blobs
> About to restore device...
> Waiting for device...

and you can see the apple logo.
then **reconnect the lightning cable.**

I solved the problem.

**Comment by mdk250** [comment]
Could you be more specific on when to disconnect the cable and when to connect the cable again ? Thanks

**Comment by brymonster** [comment]
no kidding.. that would be great.

**Comment by tihmstar** [comment]
Why would you disconnect the cable in first place?
This sounds like a really bad idea during a restore. 
This is not how a problem should be fixed. Also this is not an issue, thus does not belong here
