### ISSUE TITLE
Failed with errorcode=-3

### ISSUE THREAD

**Issue by Reus2Tech** [tihmstar/futurerestore#71]
I found this problem 
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 1iPad5,1_8471256063672870_14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[Error] [TSSC] ERROR: device "iPad5,1" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.
[Error] [TSSR] failed to get BasebandGoldCertID, but requested to get only baseband ticket. Aborting here!
[Error] [TSSR] faild to build tssrequest
[Error] baseband firmware isn't signed
Failed with errorcode=-3
Lu2ys-MacBook-Pro:DowniPad lu2yal7azina$ ./futurerestore_macos -t 1iPad5,1_8471256063672870_14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.j96.RELEASE.im4p -m BuildManifest.plist -w iPad_64bit_TouchID_10.2_14C92_Restore.ipsw 
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 1iPad5,1_8471256063672870_14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
[Error] [TSSC] ERROR: device "iPad5,1" is not in bbgcid.json, which means it's BasebandGoldCertID isn't documented yet.
If you own such a device please consider contacting @tihmstar to get instructions how to contribute to this project.
[Error] [TSSR] failed to get BasebandGoldCertID, but requested to get only baseband ticket. Aborting here!
[Error] [TSSR] faild to build tssrequest
[Error] baseband firmware isn't signed
Failed with errorcode=-3

Can you solve it

**Comment by Kagemasuru** [comment]
seems like you used a false baseband version. you need to use the one from ios 10.2.1, because its the only one which it is signed(because it only works with signed bbfws)

**Comment by tihmstar** [comment]
Looks like iPad5,1 BasebandGoldCertID is not in my database yet. You can either try starting the restore while the device is in normal mode, so futurerestore can read out that value from device, or read it out manually and send it to me so i can put it into the database.
