### ISSUE TITLE
error with iPhone connecting on VM

### ISSUE THREAD

**Issue by Kagemasuru** [tihmstar/futurerestore#73]
dear tihmstar,

ive got an issue today with connecting my iphone 6 with futurerestore. when i started it (like in your youtube video), there came a error: unable to discover device model Failed with errorcode-2.
afte that, i checked for the right sep, bbfw and im4p and it was correct. so i tried it again, and there came a new error: 
Version:  b35d3e1245da49950028d753bdb40fce5d21d5 - 90
error: normal_idevice_new: cant connect to lockdownd on device with udid......
error: restore_idevice_new: cant connect to restored on device wit udid......
cant init, no device found
Failed with errorcode=-3

do you know this problem?
maybe with the  cant init, no device found?

there also comes the error: itunes could not connect to this iphone. could not send a message to the device

**Comment by tihmstar** [comment]
Same as https://github.com/tihmstar/futurerestore/issues/41#issuecomment-287762026
no support for VM
