### ISSUE TITLE
Error -11 while trying to restore to iOS 10.3

### ISSUE THREAD

**Issue by Teuns** [tihmstar/futurerestore#74]
Hello,

I am trying to restore to ios 10.3 b 1 with saved blops, but it didn't succeed somehow:

Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 1.shsh done
reading ticket 2.shsh done
reading ticket 3.shsh done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is F9FQD8FGFCM8
waiting for nonce: 85 14 e4 66 16 6d 7c c8 63 2e 26 cc 49 37 6a de a7 98 ba 56 
waiting for nonce: 85 14 e4 66 16 6d 7c c8 63 2e 26 cc 49 37 6a de a7 98 ba 56 
waiting for nonce: 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
Got ApNonce from device: 48 1b 69 41 a0 5c 2b a9 f4 d0 dc de d8 48 7d 5b 3e f3 cc 79 
Got ApNonce from device: 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as j85ap, iPad4,4
Extracting BuildManifest from IPSW
Product Version: 10.3
Product Build: 14E5230e Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Developer Erase Install (IPSW)
This restore will erase your device data.
Extracting filesystem from IPSW
[==================================================] 100.0%
Extracting iBEC.ipad4b.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (660633 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 18 92 c8 91 8e a0 82 90 ee 46 34 85 5b 01 d7 de 89 50 ef 26 
Getting ApNonce in recovery mode... 9e 4c 51 80 09 d0 0d f1 90 a4 50 b3 b4 76 91 76 88 12 36 0c 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.50.223
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~ipad.s5l8960x.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (22709 bytes)...
ramdisk-size=0x10000000
Extracting 058-68765-027.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (41575446 bytes)...
Extracting DeviceTree.j85ap.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (102949 bytes)...
Extracting kernelcache.release.ipad4b...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12203763 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbChipID node
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
Device cd6d7283515c19074d19f4f82473ff2e41c0c0a1 is now connected in restore mode...
Connecting now...
Connected to com.apple.mobile.restored, version 14
Device cd6d7283515c19074d19f4f82473ff2e41c0c0a1 has successfully entered restore mode
Hardware Information:
BoardID: 10
ChipID: 35168
UniqueChipID: 4454574737800
ProductionMode: true
Previous restore exit status: 0x100
Starting FDR listener thread
About to send NORData...
Found firmware path Firmware/all_flash
Getting firmware manifest Firmware/all_flash/manifest
ERROR: zip_name_locate: Firmware/all_flash/manifest
ERROR: Unable to extract firmware manifest from ipsw
ERROR: Unable to send NOR data
ERROR: Unable to successfully restore device
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

Any suggestions?

Thanks!

**Comment by aicjofs** [comment]
I don't think the idevicerestore need 10.3 support for no manifest would be my guess.

https://github.com/libimobiledevice/idevicerestore/commit/aaec66651aba5f617c5c2c22b019d115e2db8e8f

**Comment by tihmstar** [comment]
Yea futurerestore is not yet ready to restore to 10.3 beta. I'm on it

**Comment by tihmstar** [comment]
updated idevicerestore in 481d959a5e36f22aa0b2bcb58914ab84b8107f4d
restoring to iOS 10.3 beta should work now
