### ISSUE TITLE
FutureRestore doesn't detect iPhone in recovery mode after putting it in recovery mode

### ISSUE THREAD

**Issue by DyKrass** [tihmstar/futurerestore#78]
Whenever I put my phone in recovery mode for futurerestore, it fails to detect it and gives errorcode=-3. 

I'm using Linux and am trying to restore an iPhone 6s Plus on 9.3.3 to 10.2.

**Comment by tihmstar** [comment]
Did you try running as root?

**Comment by DyKrass** [comment]
You know, it's been so long since I've posted this that I've forgotten to update it.

In the end running as root had everything working correctly.
