### ISSUE TITLE
Futurerestore stopped

### ISSUE THREAD

**Issue by huyle0406** [tihmstar/futurerestore#79]
I'm trying to restore my ip6s 10.2 jb to 10.2 on Virtualbox Ubuntu version 16.10 (64bit). I have done everything need for futurerestore like set nonce and install libzip. I was looking at my code and everything was right but after reading shsh2 ticket terminal just stopped, no error or anything. I tried to change cable or usb slot but no luck. Please help me

osboxes@osboxes:~/Desktop/restore102$ sudo ./futurerestore -t 850816454339622_14C922.shsh2 -b baseband.bbfw -p BuildManifest.plist -s sep.im4p -m BuildManifest.plist iPhone_4.7_10.2_14C92_Restore.ipsw
[sudo] password for osboxes: 
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket 850816454339622_14C922.shsh2 done
osboxes@osboxes:~/Desktop/restore102$

**Comment by tihmstar** [comment]
No support for using futurerestore in a VM
