### ISSUE TITLE
errorcode -11, iPhone 6S N71mAP, Debian/Ubuntu Linux (NOT VM)

### ISSUE THREAD

**Issue by GeekBreak** [tihmstar/futurerestore#84]
Tried really everything, restored my PC 3 times with Ubuntu and 2 times with Debian, tried various guide with linked tools to install dependencies (same tutorials worked for some friends), nonce correctly setted, tried many iOS 10.2 SHSH, nothing changed, keep getting error -11.
Terminal output (Censored ECID/Serial Number):
```
geekbreak@geekbreak-pc:~/Scrivania/downgrade$ sudo ./futurerestore_linux -t '/home/geekbreak/Scrivania/downgrade/ECID_iPhone8,1_n71map_10.2-14C92.shsh2' -b '/home/geekbreak/Scrivania/downgrade/Mav13-2.41.00.Release.bbfw' -p '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' -s '/home/geekbreak/Scrivania/downgrade/sep-firmware.n71m.RELEASE.im4p' -m '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' '/home/geekbreak/Scrivania/downgrade/iPhone_4.7_10.2_14C92_Restore.ipsw'
Version: b35d3e1245da49950028d753b1bdb40fce5d21d5 - 90
futurerestore init done
reading ticket /home/geekbreak/Scrivania/downgrade/ECID_iPhone8,1_n71map_10.2-14C92.shsh2 done
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
Found device in Recovery mode
Identified device as n71map, iPhone8,1
INFO: device serial number is SERIAL NUMBER
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] findAnyBuildidentityForFilehash: skipping element=BasebandFirmware
[Warning] findAnyBuildidentityForFilehash: skipping element=ftap
[Warning] findAnyBuildidentityForFilehash: skipping element=ftsp
[Warning] findAnyBuildidentityForFilehash: skipping element=rfta
[Warning] findAnyBuildidentityForFilehash: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=ftap
[Warning] getBuildIdentityForIM4M: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=ftap
[Warning] hasBuildidentityElementWithHash: skipping element=ftsp
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] getBuildIdentityForIM4M: skipping element=rfta
[Warning] getBuildIdentityForIM4M: skipping element=rfts
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
[Warning] hasBuildidentityElementWithHash: skipping element=BasebandFirmware
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from '/home/geekbreak/Scrivania/downgrade/iPhone_4.7_10.2_14C92_Restore/058-54986-095.dmg'
Extracting iBEC.n71m.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (317143 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... c0 2f 0a 1b 44 9d 15 83 5a 4f 75 ed 40 5a 51 b9 59 48 d5 26 
Getting ApNonce in recovery mode... 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.30.8
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.s8003.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12215 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330838 bytes)...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (132780 bytes)...
Extracting kernelcache.release.n71m...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12592961 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11
geekbreak@geekbreak-pc:~/Scrivania/downgrade$ 
```

**Comment by tihmstar** [comment]
Please describe what happens to the device. Does the screen flash green?
Do you see the spinning wheel or the progressbar below the apple logo?
Or does the screen maybe stay the same the whole progress?
Please try to mention every detail

**Comment by GeekBreak** [comment]
Nope, just Recovery Mode, I have to use irecovery -n to boot again

**Comment by brymonster** [comment]
https://github.com/tihmstar/futurerestore/issues/77
same issue on macOS, no change on screen, no green, no reboot. Just recovery screen. 
Tried starting in Recovery, or in normal boot and allow `futurerestore` to enter recovery mode. 
Neither worked. 
@GeekBreak sorry to hijack your issue.

**Comment by GeekBreak** [comment]
Compiled v92, nothing changed, output: 

root@geekbreak-pc:/home/geekbreak/Scrivania/downgrade/futurerestore/futurerestore# sudo ./futurerestore -t '/home/geekbreak/Scrivania/downgrade/ECID_iPhone8,1_n71map_10.2-14C92.shsh2' -b'/home/geekbreak/Scrivania/downgrade/Mav13-2.41.00.Release.bbfw' -p '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' -s '/home/geekbreak/Scrivania/downgrade/sep-firmware.n71m.RELEASE.im4p' -m '/home/geekbreak/Scrivania/downgrade/BuildManifest.plist' -w '/home/geekbreak/Scrivania/downgrade/iPhone_4.7_10.2_14C92_Restore.ipsw'
Version: 36be0769f2eb48290bdc7b57c912458c3b334fb4 - 92
futurerestore init done
reading ticket /home/geekbreak/Scrivania/downgrade/ECID_iPhone8,1_n71map_10.2-14C92.shsh2 done
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening /home/geekbreak/Scrivania/downgrade/BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is SERIAL NUMBER
waiting for nonce: 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Got ApNonce from device: 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n71map, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
Verified APTicket to be valid for this restore
Variant: Customer Erase Install (IPSW)
This restore will erase your device data.
Using cached filesystem from '/home/geekbreak/Scrivania/downgrade/iPhone_4.7_10.2_14C92_Restore/058-54986-095.dmg'
Extracting iBEC.n71m.RELEASE.im4p...
Personalizing IMG4 component iBEC...
Sending iBEC (317143 bytes)...
waiting for device to reconnect... 
Getting SepNonce in recovery mode... 54 ff dd 66 eb db 18 00 73 d5 bb 29 f8 6b 75 24 eb f9 3e cf 
Getting ApNonce in recovery mode... 82 2a 2d 1e db 51 de 15 a1 30 69 a1 0d 4d 7e b8 93 d4 ce e2 
Recovery Mode Environment:
iBoot build-version=iBoot-3406.30.8
iBoot build-style=RELEASE
Sending RestoreLogo...
Extracting applelogo@2x~iphone.s8003.im4p...
Personalizing IMG4 component RestoreLogo...
Sending RestoreLogo (12215 bytes)...
ramdisk-size=0x10000000
Extracting 058-54560-094.dmg...
Personalizing IMG4 component RestoreRamDisk...
Sending RestoreRamDisk (40330838 bytes)...
Extracting DeviceTree.n71map.im4p...
Personalizing IMG4 component RestoreDeviceTree...
Sending RestoreDeviceTree (132780 bytes)...
Extracting kernelcache.release.n71m...
Personalizing IMG4 component RestoreKernelCache...
Sending RestoreKernelCache (12592961 bytes)...
Trying to fetch new SHSH blob
WARNING: Unable to find BbSkeyId node
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received SHSH blobs
About to restore device... 
Waiting for device...
ERROR: Unable to connect to device in restore mode
ERROR: Unable to open device in restore mode
[Error] ERROR: Unable to restore device
Done: restoring failed.
Failed with errorcode=-11

**Comment by brymonster** [comment]
Can u post the compiled v92? Please I can't seem to do it. Noob

**Comment by brymonster** [comment]
..Or describe how I can compile it with auto tools. I couldn't figure it out. 

You set 'nvram auto-boot=false' before starting correct?
Seems like you started in normal mode, did also try already in Recovery Mode?

**Comment by GeekBreak** [comment]
@brymonster follow this https://www.reddit.com/r/jailbreak/comments/5kxa1e/discussion_needed_dependencies_for_futurerestore/, then https://www.reddit.com/r/PrometheusDowngrade/comments/5m9whj/tutorial_how_to_compile_futurerestore_for/

In the first guide there's a typo, It's 
`git clone https://github.com/tihmstar/libcrippy && cd ./libcrippy && bash autogen.sh && make install`
not 
`git clone https://github.com/tihmstar/libcrippy && cd ./crippy && bash autogen.sh && make install`

Anyway, I tried v93 also and nothing changed, and yes, tried starting in Recovery Mode instead of Normal Mode

**Comment by brymonster** [comment]
Thanks a lot. I appreciate the help.

**Comment by brymonster** [comment]
trying to install libcrippy:

checking for libplist >= 1.0... no
configure: error: Package requirements (libplist >= 1.0) were not met:

No package 'libplist' found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libplist_CFLAGS
and libplist_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

macOS 10.12.3
<img width="416" alt="screen shot 2017-03-25 at 9 16 11 pm" src="https://cloud.githubusercontent.com/assets/12586478/24328500/52c6eb7e-11a0-11e7-9ce9-5a98fb22a342.png">

**Comment by brymonster** [comment]
an when trying to compile furturerestore, the same:
<img width="512" alt="screen shot 2017-03-25 at 9 18 05 pm" src="https://cloud.githubusercontent.com/assets/12586478/24328512/a4c43e90-11a0-11e7-974b-1a76bfc93e2b.png">

**Comment by tihmstar** [comment]
Try with version 95 of futurerestore. If you still have the same error, please report back in issue #77
