### ISSUE TITLE
Segmentation Fault: 11

### ISSUE THREAD

**Issue by iscofield** [tihmstar/futurerestore#86]
iPhone 6+ currently jailbroken on 9.3.3 with SHSH blobs saved on a macbook pro.

Tried 5 times all with the same result after setting nonce manually.  After it reboots into recovery mode, iTunes pops up saying it detected a phone in recovery mode.  This is the exact same time the segmentation fault is thrown.  Not sure if iTunes opening is causing future restore to fail.  I have iTunes set to not automatically open, but that seems to be trumped by the phone when it's in recovery mode.

`sh-3.2# ./futurerestore_macos -t <removed for privacy>_iPhone7,1_10.2-14C92.shsh2 -b Mav10-5.32.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n56.RELEASE.im4p -m BuildManifest.plist iPhone_5.5_10.2_14C92_Restore.ipsw
Version: 36be0769f2eb48290bdc7b57c912458c3b334fb4 - 92
futurerestore init done
reading ticket <removed for privacy>_iPhone7,1_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is FK1NDF8TG5QJ
Found device in Recovery mode
Identified device as n56ap, iPhone7,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
Segmentation fault: 11`

**Comment by tihmstar** [comment]
Same issue as #85
