### ISSUE TITLE
[errorcode=-45] APTicket is valid for 2972911401772 but device is 2b42f53fb2c

### ISSUE THREAD

**Issue by hsharghi** [tihmstar/futurerestore#87]
I have downloaded and check 10.2 shsh2 blobs for iPhone 6s and It's valid. 
> Apnonce: 318c5974ad87e3fdd61caa6a29cc77322d4b6bb9
Build Number: 14C92
Board Configuration: n71ap
Restore Behaviour: Erase
Rosi Tag: true
[IMG4TOOL] file is valid!
arg :--verify
Version: 17060e500a853a9b4ed860f246d3aa0a90258e31 - 85
Version: 0
MANB
MANP: MANP: ------------------------------
BNCH: BNCH: 318c5974ad87e3fdd61caa6a29cc77322d4b6bb9
BORD: BORD: 4
CEPO: CEPO: 1
CHIP: CHIP: 32768
CPRO: CPRO: true
CSEC: CSEC: true
ECID: ECID: 729152592287602
SDOM: SDOM: 1
snon: snon: e0c65760b8a4077a10ba29bc310a0ff433a6f850
srvn: srvn: d7e54792bce5390282d7f196b039df911977c6d0

But when I tried to restore from 9.0.1 to 10.2 I got this error message

I've managed to enable tfp0 using cl0ver tool before using futurerstore.

> APTicket is valid for 2972911401772 but device is 2b42f53fb2c

**The strange thing is the first number is the same as the second number in hex. Practically they are the same!**

> ~/Desktop/futurerestore$ ./futurerestore_macos -t 729152592287602_iPhone8,1_n71ap_10.2-14C92.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw 

> Version: '9fcf613f8fe68b15be7fd19c267e7351523eb387' - 95
futurerestore init done
reading ticket 729152592287602_iPhone8,1_n71ap_10.2-14C92.shsh2 done
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified not to request a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Did set sep+baseband path and firmware
[WARNING] failed to read BasebandGoldCertID from device! Is it already in recovery?
[WARNING] using tsschecker's fallback to get BasebandGoldCertID. This might result in invalid baseband signing status information
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is F17QH8TFGRYF
waiting for nonce: 31 8c 59 74 ad 87 e3 fd d6 1c aa 6a 29 cc 77 32 2d 4b 6b b9 
Got ApNonce from device: 31 8c 59 74 ad 87 e3 fd d6 1c aa 6a 29 cc 77 32 2d 4b 6b b9 
Device has requested ApNonce now
Found device in Recovery mode
Identified device as n71ap, iPhone8,1
Extracting BuildManifest from IPSW
Product Version: 10.2
Product Build: 14C92 Major: 14
Device supports Image4: true
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for    2972911401772 but device is      2b42f53fb2c
[Error] APTicket can't be used for restoring this device
Done: restoring failed.
Failed with errorcode=-45

**Comment by boobang** [comment]
@tihmstar: this is it..

**Comment by tihmstar** [comment]
The problem is that both numbers are shown as hex. As you can see here both times the hex represantation of the number is printed c271a71524d05d181c099c426264809c7e1c3917
I'm changin this to decimal to make this more obvious. i admit it was confusing.

Also if you check your output from img4tool  "ECID: ECID: 729152592287602"
you'll notice that the ECID there doesn't look like either of the two numbers in your restore log "APTicket is valid for 2972911401772 but device is 2b42f53fb2c"
This is because img4tool actually prints in decimal.
So actually 0x2972911401772 is same as 729152592287602, which is the ecid in your APTicket.
But your device is 0x2b42f53fb2c (which is 2972911401772 in decimal).

i assume this is because of some hex-dec dec-hex conversions beeing performed with the tools you used to save your shsh files. 
tsschecker actually shows you the string you entered and the result of the parsing in both, dec and hex:
`tihms-MBP:~ tihmstar$ tsschecker -d iPhone6,2 -l -e 2b42f53fb2c`
`[TSSC] manually specified ecid to use, parsed "2b42f53fb2c" to dec:2972911401772 hex:2b42f53fb2c`

`tihms-MBP:~ tihmstar$ tsschecker -d iPhone6,2 -l -e 2972911401772`
`[TSSC] manually specified ecid to use, parsed "2972911401772" to dec:2972911401772 hex:2b42f53fb2c`
 So this is really convinient to check whether the ecid was interpreted correctly. If you used other tools then maybe something went wrong there.
But in the end it's the users task to check whether their shsh files are correctly (device model, ecid, upgrade/erase mode etc.), so i don't think you can blame anyone but you here.
In this case you're just out of luck.

**Comment by 1Conan** [comment]
tihmstar pretty much explained everything. If OP used my site, he could've selected the wrong ecid type on the dropdown.

**Comment by brymonster** [comment]
Nothing? 
As I mentioned this issue only presented itself in the later update. My device quickly passed the APTicket verification, with no error. 

But suddenly now my blobs aren't good..?

**Comment by DragonHole** [comment]
@1Conan so why is there a hex option and it is set as default then?? And what's the point of saving it if futurerestore can't use decimal type shsh??? i just dont fcking get it

**Comment by chygrynskiy** [comment]
2years later @brymonster im getting the same error message...


Did set SEP+baseband path and firmware
[TSSC] opening E:\Downloads\iRestore-master\iRestore-master\BuildManifest.plist
[TSSR] User specified to request only a Baseband ticket.
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... Request URL set to https://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 2... Request URL set to https://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 3... Request URL set to http://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 4... Request URL set to http://17.171.36.30/TSS/controller?action=2
Sending TSS request attempt 5... Request URL set to http://17.151.36.30/TSS/controller?action=2
Sending TSS request attempt 6... Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 7... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is C7JP4K3HG5MQ
Found device in Recovery mode
Identified device as n61ap, iPhone7,2
Extracting BuildManifest from IPSW
Product Version: 12.1.1
Product Build: 16C50 Major: 16
Device supports Image4: true
Got ApNonce from device: 3a 88 b7 c3 80 2f 2f 05 10 ab c4 32 10 4a 15 eb d8 bd 71 54
checking APTicket to be valid for this restore...
[Error] ECID inside APTicket does not match device ECID
APTicket is valid for 7031687491031009090 (dec) but device is 6195928482760742 (dec)
[Error] APTicket can't be used for restoring this device
Done: restoring failed.
Failed with errorcode=-45.....

**Comment by artemy12** [comment]
I have the same error. OS Lubuntu 19.10

`Supported Device                                                                                     
iPhone6,1                                                                                            
Supported device found.                                                                              
Version: 6755d86ef89526a33abeb4ac1f36e37996015a7e - 6                                                
Identified device as n51ap, iPhone6,1 in dfu mode...                                                 
ecid=67409310690                                                                                     
ApNonce=efd3060f847c13dbd79b955cc9761a76bb6b9653                                                     
SepNonce=e6fc17f71b2c2cf7fcecf34399319f759731dc91                                                    
[+]Copy and paste ecid and press enter: 67409310690                                                  
67409310690                                                                                          
переименован 'ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p' -> './iBEC.iphone6.RELEASE.im4p'          
переименован 'ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p' -> './iBSS.iphone6.RELEASE.im4p'          
'ipsw/Firmware/all_flash/sep-firmware.n51.RELEASE.im4p' -> './sep-firmware.n51.RELEASE.im4p'         
'iBSS.img4' -> 'ipsw/Firmware/dfu/iBSS.iphone6.RELEASE.im4p'                                         
'iBEC.img4' -> 'ipsw/Firmware/dfu/iBEC.iphone6.RELEASE.im4p'                                         
Version: 6755d86ef89526a33abeb4ac1f36e37996015a7e - 6                                                
Identified device as n51ap, iPhone6,1 in dfu mode...                                                 
ecid=67409310690                                                                                     
ApNonce=efd3060f847c13dbd79b955cc9761a76bb6b9653                                                     
SepNonce=e6fc17f71b2c2cf7fcecf34399319f759731dc91                                                    
[+]Copy and paste apnonce and press enter: efd3060f847c13dbd79b955cc9761a76bb6b9653                  
[+]Copy and paste your idevice example and press enter 'iPhone6,2': iPhone6,1                        
67409310690                                                                                          
[==================================================] 100.0%                                          
[==================================================] 100.0%                                          
Version: 78c1203bcb326dcc813cc24cce2df6b88c01eef4 - 301                                              
libfragmentzip version: 0.58-ffec726ea514d8b8f3f3e42d04ce1430f3889747                                
[TSSC] manually specified ECID to use, parsed "67409310690" to dec:67409310690 hex:fb1e873e2         
[TSSC] manually specified apnonce to use, parsed "efd3060f847c13dbd79b955cc9761a76bb6b9653" to hex:efd3060f847c13dbd79b955cc9761a76bb6b9653                                                               
[TSSC] opening manifests/BuildManifest_iPhone6,1_1033_OTA.plist                                      
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2                               
[TSSR] Sending TSS request attempt 1... success                                                      
also requesting APTicket for installType=Update                                                      
[Error] [TSSR] Error: could not get id0 for installType=Update                                       
[WARNING] [TSSR] failed to build tssrequest for alternative installType                              
[TSSR] User specified doesn't to request a baseband ticket.                                          
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2                               
[TSSR] Sending TSS request attempt 1... failure                                                      
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)                  
Saved shsh blobs!                                                                                    
                                                                                                     
iOS 10.3.3 for device iPhone6,1 IS being signed!                                                     
переименован '67409310690_iPhone6,1_10.3.3-14G60_efd3060f847c13dbd79b955cc9761a76bb6b9653.shsh' -> 'shsh/apnonce.shsh'                                                                                    
Done prepping files! Time to downgrade!!!                                                            
****RESTORING!****                                                                                   
Waiting for device to reconnect...                                                                   
Version: 7e66824796f697ea54597dadbdba462382f004b9 - 247                                              
Odysseus support: no                                                                                 
INFO: device serial number is DNPMK854FF9V                                                           
[INFO] 64-bit device detected                                                                        
futurerestore init done                                                                              
reading signing ticket shsh/apnonce.shsh is done                                                     
Found device iPhone6,1 n51ap                                                                         
[TSSC] opening manifests/BuildManifest_iPhone6,1_1033_OTA.plist                                      
[TSSR] User specified not to request a baseband ticket.                                              
Request URL set to https://gs.apple.com/TSS/controller?action=2                                      
Sending TSS request attempt 1... response successfully received                                      
Did set SEP+baseband path and firmware                                                               
[WARNING] Failed to read BasebandGoldCertID from device! Is it already in recovery?                  
[WARNING] Using tsschecker's fallback BasebandGoldCertID. This might result in invalid baseband signing status information                                                                                
[WARNING] Failed to read BasebandSerialNumber from device! Is it already in recovery?                
[WARNING] Using tsschecker's fallback BasebandSerialNumber size. This might result in invalid baseband signing status information                                                                         
[TSSC] opening manifests/BuildManifest_iPhone6,1_1033_OTA.plist                                      
[TSSR] User specified to request only a baseband ticket.                                             
Request URL set to https://gs.apple.com/TSS/controller?action=2                                      
Sending TSS request attempt 1... response successfully received                                      
Found device in Recovery mode                                                                        
Device already in Recovery mode                                                                      
Found device in Recovery mode                                                                        
Identified device as n51ap, iPhone6,1                                                                
Extracting BuildManifest from iPSW                                                                   
Product version: 10.3.3                                                                              
Product build: 14G60 Major: 14                                                                       
Device supports IMG4: true                                                                           
Got ApNonce from device: ef d3 06 0f 84 7c 13 db d7 9b 95 5c c9 76 1a 76 bb 6b 96 53                 
checking APTicket to be valid for this restore...                                                    
[Error] ECID inside APTicket doesn't match device ECID                                               
APTicket is valid for      67409310690 (dec) but device is    7095440180880 (dec)                    
[Error] APTicket can't be used for restoring this device                                             
                                                                                                     
To exit recovery mode, use --exit-recovery                                                           
                                                                                                     
Done: restoring failed.                                                                              
Failed with errorcode=-45                                                                            
Cleaning up :D                                                                                       
If you see this, we're done! Shoutout to the devs and LukeDev for making this possible! - twilightmoon4                                                                                                   
Usage: ./restore.sh PathToIpsw (ipsw must be in this directory)                                      
Example: ./restore.sh iPhone_4.0_64bit_10.3.3_14G60_Restore.ipsw     `
