### ISSUE TITLE
not updated to v100 in the futurerestore link

### ISSUE THREAD

**Issue by osxusr** [tihmstar/futurerestore#89]
its still giving us v95, not v100

**Comment by Shrubbity** [comment]
you have to compile it:

https://www.reddit.com/r/PrometheusDowngrade/comments/5m9whj/tutorial_how_to_compile_futurerestore_for/

**Comment by osxusr** [comment]
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for pkg-config... /usr/local/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for libplist... yes
checking for libzip... yes
checking for libimobiledevice... no
configure: error: Package requirements (libimobiledevice-1.0 >= 1.2.1) were not met:

Requested 'libimobiledevice-1.0 >= 1.2.1' but version of libimobiledevice is 1.2.0

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables libimobiledevice_CFLAGS
and libimobiledevice_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details

**Comment by albyvar** [comment]
Same problem

**Comment by Shrubbity** [comment]
Open terminal,

cd /users/[USERNAME]/desktop

git clone https://github.com/libimobiledevice/libimobiledevice.git

cd libimobiledevice

./autogen.sh

make

sudo make install

**Comment by albyvar** [comment]
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in common
  CC       socket.lo
  CC       thread.lo
  CC       debug.lo
  CC       userpref.lo
  CC       utils.lo
  CCLD     libinternalcommon.la
Making all in src
  CC       idevice.lo
idevice.c:105:2: warning: 'ERR_remove_thread_state' is deprecated
      [-Wdeprecated-declarations]
        ERR_remove_thread_state(NULL);
        ^
/usr/local/include/openssl/err.h:246:25: note: 'ERR_remove_thread_state' has
      been explicitly marked deprecated here
DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
                        ^
idevice.c:706:33: warning: 'TLSv1_method' is deprecated
      [-Wdeprecated-declarations]
        SSL_CTX *ssl_ctx = SSL_CTX_new(TLSv1_method());
                                       ^
/usr/local/include/openssl/ssl.h:1665:45: note: 'TLSv1_method' has been
      explicitly marked deprecated here
DEPRECATEDIN_1_1_0(__owur const SSL_METHOD *TLSv1_method(void)) /* TLSv1.0 */
                                            ^
idevice.c:760:2: warning: 'ERR_remove_thread_state' is deprecated
      [-Wdeprecated-declarations]
        ERR_remove_thread_state(NULL);
        ^
/usr/local/include/openssl/err.h:246:25: note: 'ERR_remove_thread_state' has
      been explicitly marked deprecated here
DEPRECATEDIN_1_1_0(void ERR_remove_thread_state(void *))
                        ^
idevice.c:55:13: warning: unused function 'locking_function' [-Wunused-function]
static void locking_function(int mode, int n, const char* file, int line)
            ^
idevice.c:63:22: warning: unused function 'id_function' [-Wunused-function]
static unsigned long id_function(void)
                     ^
5 warnings generated.
  CC       service.lo
  CC       property_list_service.lo
  CC       device_link_service.lo
  CC       lockdown.lo
  CC       afc.lo
  CC       file_relay.lo
  CC       notification_proxy.lo
  CC       installation_proxy.lo
  CC       sbservices.lo
  CC       mobile_image_mounter.lo
  CC       screenshotr.lo
  CC       mobilesync.lo
  CC       mobilebackup.lo
  CC       house_arrest.lo
  CC       mobilebackup2.lo
  CC       misagent.lo
  CC       restore.lo
  CC       diagnostics_relay.lo
  CC       heartbeat.lo
  CC       debugserver.lo
  CC       webinspector.lo
  CC       syslog_relay.lo
  CCLD     libimobiledevice.la
Making all in include
make[2]: Nothing to be done for `all'.
Making all in tools
  CC       idevice_id-idevice_id.o
  CCLD     idevice_id
  CC       ideviceinfo-ideviceinfo.o
  CCLD     ideviceinfo
  CC       idevicename-idevicename.o
  CCLD     idevicename
  CC       idevicepair-idevicepair.o
  CCLD     idevicepair
  CC       idevicesyslog-idevicesyslog.o
  CCLD     idevicesyslog
  CC       ideviceimagemounter-ideviceimagemounter.o
  CCLD     ideviceimagemounter
  CC       idevicescreenshot-idevicescreenshot.o
  CCLD     idevicescreenshot
  CC       ideviceenterrecovery-ideviceenterrecovery.o
  CCLD     ideviceenterrecovery
  CC       idevicedate-idevicedate.o
  CCLD     idevicedate
  CC       idevicebackup-idevicebackup.o
  CCLD     idevicebackup
  CC       idevicebackup2-idevicebackup2.o
  CCLD     idevicebackup2
  CC       ideviceprovision-ideviceprovision.o
  CCLD     ideviceprovision
  CC       idevicedebugserverproxy-idevicedebugserverproxy.o
  CCLD     idevicedebugserverproxy
  CC       idevicediagnostics-idevicediagnostics.o
  CCLD     idevicediagnostics
  CC       idevicedebug-idevicedebug.o
  CCLD     idevicedebug
  CC       idevicenotificationproxy-idevicenotificationproxy.o
  CCLD     idevicenotificationproxy
  CC       idevicecrashreport-idevicecrashreport.o
  CCLD     idevicecrashreport
Making all in docs
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.
iMac-di-alby:libimobiledevice alby$ sudo make install
Password:
Making install in common
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
Making install in src
 .././install-sh -c -d '/usr/local/lib'
 /bin/sh ../libtool   --mode=install /usr/bin/install -c   libimobiledevice.la '/usr/local/lib'
libtool: install: /usr/bin/install -c .libs/libimobiledevice.6.dylib /usr/local/lib/libimobiledevice.6.dylib
libtool: install: (cd /usr/local/lib && { ln -s -f libimobiledevice.6.dylib libimobiledevice.dylib || { rm -f libimobiledevice.dylib && ln -s libimobiledevice.6.dylib libimobiledevice.dylib; }; })
libtool: install: /usr/bin/install -c .libs/libimobiledevice.lai /usr/local/lib/libimobiledevice.la
libtool: install: /usr/bin/install -c .libs/libimobiledevice.a /usr/local/lib/libimobiledevice.a
libtool: install: chmod 644 /usr/local/lib/libimobiledevice.a
libtool: install: ranlib /usr/local/lib/libimobiledevice.a
 .././install-sh -c -d '/usr/local/lib/pkgconfig'
 /usr/bin/install -c -m 644 libimobiledevice-1.0.pc '/usr/local/lib/pkgconfig'
Making install in include
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/include'
 .././install-sh -c -d '/usr/local/include/libimobiledevice'
 /usr/bin/install -c -m 644  libimobiledevice/libimobiledevice.h libimobiledevice/lockdown.h libimobiledevice/afc.h libimobiledevice/file_relay.h libimobiledevice/notification_proxy.h libimobiledevice/installation_proxy.h libimobiledevice/sbservices.h libimobiledevice/mobile_image_mounter.h libimobiledevice/screenshotr.h libimobiledevice/mobilesync.h libimobiledevice/mobilebackup.h libimobiledevice/house_arrest.h libimobiledevice/mobilebackup2.h libimobiledevice/misagent.h libimobiledevice/restore.h libimobiledevice/webinspector.h libimobiledevice/heartbeat.h libimobiledevice/diagnostics_relay.h libimobiledevice/debugserver.h libimobiledevice/syslog_relay.h libimobiledevice/property_list_service.h libimobiledevice/service.h '/usr/local/include/libimobiledevice'
Making install in tools
 .././install-sh -c -d '/usr/local/bin'
  /bin/sh ../libtool   --mode=install /usr/bin/install -c idevice_id ideviceinfo idevicename idevicepair idevicesyslog ideviceimagemounter idevicescreenshot ideviceenterrecovery idevicedate idevicebackup idevicebackup2 ideviceprovision idevicedebugserverproxy idevicediagnostics idevicedebug idevicenotificationproxy idevicecrashreport '/usr/local/bin'
libtool: install: /usr/bin/install -c .libs/idevice_id /usr/local/bin/idevice_id
libtool: install: /usr/bin/install -c .libs/ideviceinfo /usr/local/bin/ideviceinfo
libtool: install: /usr/bin/install -c .libs/idevicename /usr/local/bin/idevicename
libtool: install: /usr/bin/install -c .libs/idevicepair /usr/local/bin/idevicepair
libtool: install: /usr/bin/install -c .libs/idevicesyslog /usr/local/bin/idevicesyslog
libtool: install: /usr/bin/install -c .libs/ideviceimagemounter /usr/local/bin/ideviceimagemounter
libtool: install: /usr/bin/install -c .libs/idevicescreenshot /usr/local/bin/idevicescreenshot
libtool: install: /usr/bin/install -c .libs/ideviceenterrecovery /usr/local/bin/ideviceenterrecovery
libtool: install: /usr/bin/install -c .libs/idevicedate /usr/local/bin/idevicedate
libtool: install: /usr/bin/install -c .libs/idevicebackup /usr/local/bin/idevicebackup
libtool: install: /usr/bin/install -c .libs/idevicebackup2 /usr/local/bin/idevicebackup2
libtool: install: /usr/bin/install -c .libs/ideviceprovision /usr/local/bin/ideviceprovision
libtool: install: /usr/bin/install -c .libs/idevicedebugserverproxy /usr/local/bin/idevicedebugserverproxy
libtool: install: /usr/bin/install -c .libs/idevicediagnostics /usr/local/bin/idevicediagnostics
libtool: install: /usr/bin/install -c .libs/idevicedebug /usr/local/bin/idevicedebug
libtool: install: /usr/bin/install -c .libs/idevicenotificationproxy /usr/local/bin/idevicenotificationproxy
libtool: install: /usr/bin/install -c .libs/idevicecrashreport /usr/local/bin/idevicecrashreport
make[2]: Nothing to be done for `install-data-am'.
Making install in docs
make[2]: Nothing to be done for `install-exec-am'.
 .././install-sh -c -d '/usr/local/share/man/man1'
 /usr/bin/install -c -m 644 idevice_id.1 ideviceinfo.1 idevicesyslog.1 idevicebackup.1 idevicebackup2.1 ideviceimagemounter.1 idevicescreenshot.1 idevicepair.1 ideviceenterrecovery.1 idevicedate.1 ideviceprovision.1 idevicedebugserverproxy.1 idevicediagnostics.1 idevicecrashreport.1 idevicename.1 idevicedebug.1 idevicenotificationproxy.1 '/usr/local/share/man/man1'
make[2]: Nothing to be done for `install-exec-am'.
make[2]: Nothing to be done for `install-data-am'.
iMac-di-alby:libimobiledevice alby$

**Comment by albyvar** [comment]
Thanks now it seems to work

**Comment by albyvar** [comment]
EDIT:
iMac-di-alby:futurerestore alby$ sudo make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in external/idevicerestore
make[2]: *** No rule to make target `all'.  Stop.
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

**Comment by Shrubbity** [comment]
No problem, you can also use 'irecovery -n' to exit recovery mode.

**Comment by osxusr** [comment]
futurerestore_macos v100 http://www.mediafire.com/file/76s1izgevdi5rbi/FutureRestore_macos_v100.zip
