### ISSUE TITLE
Error code -15, 32-bit and no-baseband downgrade

### ISSUE THREAD

**Issue by Shrubbity** [tihmstar/futurerestore#90]
This is on an iPad Mini 1 with the latest version 100 attempting to generate the nonces probabilistically, iOS 9.0.2 - 6.1.3. I'm not entirely sure this is even possible but here's my error log anyway.

The 'pointer being freed was not allocated' error seems irrelevant to whether the device is connected or not as running './futurerestore' also generates it.

There is a corresponding .plist file under .known_devices folder which I imagine is not being taken into account. Here's an example of this file, there only appears to be one and it states 6.1 but I'd imagine they're interchangeable between a few iOS iterations: https://pastebin.com/vD24vbPc

------------------------------------------------------

Admins-Mac:futurerestore admin$ **./futurerestore -t 42481595784-ipad2,5-6.1.3.shsh -w --is-32bit --no-baseband iPad2,5_6.1.3_10B329_Restore.ipsw**

Version: c271a71524d05d181c099c426264809c7e1c3917 - 100
[INFO] setting 32bit device flag
futurerestore init done
**Entity: line 1: parser error : Start tag expected, '<' not found
?
^**
reading ticket 42481595784-ipad2,5-6.1.3.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is XXXXXXXXXXX
**[Error] Got empty IM4M
[Error] Fail code=-15
Failed with errorcode=-15
futurerestore(481,0x7fffee7a43c0) malloc: *** error for object 0x9000000000000000: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6**
Admins-Mac:futurerestore admin$

**Comment by albyvar** [comment]
Same problem with 9.3.4 and 8.4.1 blobs on the same device iPad2,5

**Comment by MrARM** [comment]
Bump, iPhone5,3 with 9.0.2 and 8.4.1

**Comment by albyvar** [comment]
Commit 105 fixes this

**Comment by Shrubbity** [comment]
I'm now getting error code -38 which is apparently 'Error: failed to load shsh file'

**Comment by MrARM** [comment]
@Shrubbity Are you using a tinyumbrella blob? I am getting a problem with mine.

**Comment by lwlsw** [comment]
use 105 version

**Comment by MrARM** [comment]
@lwlsw Im using 105.

**Comment by lwlsw** [comment]
你这用的就是100版本的，你自己下载最新的源码，编译一下，就是105版本的

**Comment by Shrubbity** [comment]
@MrARM Yes I'm using blobs saved from TinyUmbrella a long time ago. There is also an accompanying .plist in the .known_devices folder.

**Comment by lwlsw** [comment]
你能把你的shsh发给我，我看一下吗？

**Comment by Shrubbity** [comment]
Okay here's a link: https://ufile.io/2d541

**Comment by MrARM** [comment]
@Shrubbity Odd. Mine is in a one file shsh. After some reasearch I found it was in a GZip file. I found a program to extract mine. It didn't work.

I'm trying to make my own for now unless somebody comes up with one faster. 
https://github.com/MrARM/SHSHatter

**Comment by lwlsw** [comment]
用9.x的shsh的试试

**Comment by tihmstar** [comment]
Added support for gzip compressed tickets in version 112 ace8ae144f78f53b2cc6558e057b9be32f073595
Can you check if it works?

**Comment by Anniyan** [comment]
I'm getting error code -38 which is apparently [Error] Error: failed to load shsh file xxxxxxx.shsh2

**Comment by Shrubbity** [comment]
Now getting:

**Comment by Shrubbity** [comment]
Now appears to be working correctly but alas I have no way of knowing what nonce the .shsh blob was generated with.

**Comment by albyvar** [comment]
You restored to 6.1.3 successfully?

**Comment by Shrubbity** [comment]
No because I have no means of knowing what nonce my 6.1.3 blob holds and thus what nonce my device needs for a match. It's an .shsh file which only holds a nonce, whereas an .shsh2 includes a nonce and a generator. I don't think for me there's a way of getting the nonce without knowing the generator or having specified it when you requested the blob in the first place. I think you can decrypt the blob (since it's img3) and see the nonce if you have the device firmware keys but these still haven't been released for most of the S5L8942 devices (e.g. iPad Mini). Is this correct @tihmstar?

Furthermore, -w doesn't work on 32 bit devices so there's no automatic way of probabilistically trying to get a match.


However, previous error codes that I'd get have all been solved.

**Comment by MrARM** [comment]
Do you know how to decrypt an img3 blob? I have a 8.4 blob for my 5c(5,3).
________________________________

**Comment by Shrubbity** [comment]
To be honest that might of been wrong of me, I'm not actually sure whether you can decrypt them. I'd hope so but I might be remembering Tihmstar's slides wrongly.

You'd need to try something like this:
https://github.com/matteyeux/Decrypt0r

I'd be interested to know how you get on.

**Comment by albyvar** [comment]
@Shrubbity You can use this to check the blob nonce:
https://github.com/axi0mX/apticket-nonce-checker
