### ISSUE TITLE
Segmentation Fault: 11 on 32 bit device

### ISSUE THREAD

**Issue by albyvar** [tihmstar/futurerestore#93]
I got this on iPad2,5 with iOS 8.4.1 OTA Blobs, saved with Tinyumbrella and converted with SHSHAker.

iMac-di-alby:futurerestore-latest alby$ ./futurerestore -t cydia.shsh --is-32bit --no-baseband -w ota.ipsw
Version: 12066c924e4b564669fbaaa9dd6585db525c959c - 105
[INFO] setting 32bit device flag
futurerestore init done
reading ticket cydia.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is --
waiting for nonce: 
Got ApNonce from device: de 28 c1 b9 14 64 ce 41 0c d1 d3 9e e0 e3 a3 d9 b0 ca f4 85 
Segmentation fault: 11

**Comment by lwlsw** [comment]
应该是shsh的问题，使用9.x的shsh

**Comment by albyvar** [comment]
With 9.3.4 shsh it search for nonce to match

**Comment by haniag** [comment]
Getting same result in futurerestore 105. I am on 4S at 9.3.5 and trying to go to 9.3.4:

rMBP:futurerestore User$ ./futurerestore-105 -t 777591858056_iPhone4,1_9.3.4-13G35.shsh -b Trek-6.0.00.Release.bbfw -p BuildManifest.plist -w --is-32bit iPhone4,1_9.3.4_13G35_Restore.ipsw
Version: 12066c924e4b564669fbaaa9dd6585db525c959c - 105
[INFO] setting 32bit device flag
futurerestore init done
reading ticket 777591858056_iPhone4,1_9.3.4-13G35.shsh done
Did set sep+baseband path and firmware
[TSSC] opening BuildManifest.plist
WARNING: Unable to find BbSkeyId node
[TSSR] User specified to request only a Baseband ticket.
ERROR: Unable to get BasebandFirmware node
ERROR: Unable to find required BbGoldCertId in parameters
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Found device in Normal mode
Entering recovery mode...
INFO: device serial number is C8PJT830DTD0
waiting for nonce: 
Got ApNonce from device: 0b 4a fe bb a0 9f cd 67 d5 e9 d3 e3 d1 fe 0c e5 c9 44 c8 63 
Segmentation fault: 11

Also the same if I am not including bb:

rMBP:futurerestore User$ ./futurerestore-105 -t 777591858056_iPhone4,1_9.3.4-13G35.shsh -w --is-32bit --no-baseband iPhone4,1_9.3.4_13G35_Restore.ipsw
Version: 12066c924e4b564669fbaaa9dd6585db525c959c - 105
[INFO] setting 32bit device flag
futurerestore init done
reading ticket 777591858056_iPhone4,1_9.3.4-13G35.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is C8PJT830DTD0
waiting for nonce: 
Got ApNonce from device: 50 53 dd be 21 ad 7c 3c 2a 1a 79 57 88 bf 61 54 76 f0 9d 36 
Segmentation fault: 11

In both cases, the device goes into recovery.

**Comment by serges93** [comment]
I'm having the same issue also, I was trying in an iPad 3,1 from 9.3.5 to 6.1.3.
I guess I'm trying to go to down, I guess:

Rev-Palacios-MacBook-Pro:fr serges$ ./futurerestore -t blobs.shsh --is-32bit --no-baseband -w iPad3,1_6.1.3_10B329_Restore.ipsw
Version: 12066c924e4b564669fbaaa9dd6585db525c959c - 105
[INFO] setting 32bit device flag
futurerestore init done
reading ticket blobs.shsh done

WARNING: user specified not to flash a baseband. This can make the restore fail if the device needs a baseband!
if you added this flag by mistake you can press CTRL-C now to cancel
continuing restore in 5 4 3 2 1 
Found device in Recovery mode
Device already in Recovery mode
INFO: device serial number is DMPHP406DJ8T
waiting for nonce: 
Got ApNonce from device: 42 23 d7 d4 7f d3 fd 06 10 5e b0 59 99 20 c6 68 10 4e c5 27 
Segmentation fault: 11

**Comment by da1996** [comment]
Same issue: iPad 3,1  iOS 9.3.5 -> iOS 8.3/6.1

**Comment by tihmstar** [comment]
Is the issue still present int version 111 eeefc9ef410c8563eda6ac7e51ecc8f23f2abb1f ?

**Comment by da1996** [comment]
From 106 it stuck in waiting for device, i think it is solved

**Comment by serges93** [comment]
version 114 fixed it for me, however now I'm stuck in the 'waiting for device' but that is another issue
