### ISSUE TITLE
I'm pretty sure this isnt a problem with futurerestore but figured this was the place to ask.

### ISSUE THREAD

**Issue by osxusr** [tihmstar/futurerestore#94]
futurerestore(9520,0x7ffff2d953c0) malloc: *** error for object 0x7f8708c053e0: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
Abort trap: 6

I heard this was due to using openssl 1.0.2k and you need to use 1.0.1

**Comment by MrARM** [comment]
Please provide the full log.
