### ISSUE TITLE
Can't restore 64-bit device with latest (106) version

### ISSUE THREAD

**Issue by xeroxoid** [tihmstar/futurerestore#99]
Hi all,

Firstly, thanks for all the great work.

I am trying to downgrade my iphone 6s from 10.2.1 to 10.2 using the blobs I had saved with the latest futurerestore (106). I am getting the following error:

```
$ ./futurerestore_macos -t 1.shsh2 -b Mav13-2.41.00.Release.bbfw -p BuildManifest.plist -s sep-firmware.n71m.RELEASE.im4p -m BuildManifest.plist -w iPhone_4.7_10.2_14C92_Restore.ipsw

Version: d8b69365ecb78414d8a6bf024d449133f581b6d4 - 106
[INFO] 32bit device detected
futurerestore init done
[Error] Error: failed to load shsh file 1.shsh2
[Error] Fail code=-38
Failed with errorcode=-38
```

Any clues?

**Comment by tihmstar** [comment]
Can you check whether the issue still exists in version eeefc9ef410c8563eda6ac7e51ecc8f23f2abb1f (111)

**Comment by xeroxoid** [comment]
Danke! Is there a binary available or do I have to compile it?

**Comment by tihmstar** [comment]
Daily builds are available at http://api.tihmstar.net/builds/futurerestore/futurerestore-latest.zip

**Comment by mdang24zz** [comment]
Hi, i used the latest version on Iphone 6 plus 10.2.1  downgrade but the error still persist

**Comment by shsh2** [comment]
Is there any solution for downgrade  ios 10.3.2 to 10.2 using shsh2 blobs
(My iPod on iOS 10.3.2 ) and thanks👌👌👌
